### ISSUE TITLE
Change "election" references to "contest"

### ISSUE THREAD

**Issue by HEdingfield** [BrightSpots/rcv#107]
Agree with @moldover in the [UI doc](https://docs.google.com/document/d/1jQmhIoHNo0cNxD8h3xDHmiGyvxaUwbFi0Ieh3-W-2_U/edit?ts=5b5d375c#) that "contest" is a better term than "election" for our tool if we want to be as general as possible.

Recommend a superficial refactor of all uses of the word "election" in the code and documentation to "contest".

@tarheel sound good?

**Comment by tarheel** [comment]
Um, yeah, that's fine.

**Comment by CalebKleppner** [comment]
I think contest make sense (it refers to one race, as opposed to all the 
races in a single election). We tabulate the CVRs in a single contest.

I think we should stick with "Candidates" and "Seats".  ("Number to be 
elected" is a bit wordier than "Seats".  I don't know of any alternative 
to "Candidates")

Caleb Kleppner
MK Election Services, LLC
203-376-4080
