### ISSUE TITLE
Use standardized project structure

### ISSUE THREAD

**Issue by HEdingfield** [BrightSpots/rcv#110]
I've been having trouble getting the Help button I'm working on to call up the config documentation txt file. It would help out a lot if we moved to a more standard directory structure like that used by [Apache's Maven project](https://maven.apache.org/guides/introduction/introduction-to-the-standard-directory-layout.html). [Here's](https://github.com/TheItachiUchiha/MediaPlayerFX) a simple example of the layout in action.

@tarheel @moldover sound reasonable?

**Comment by HEdingfield** [comment]
I was researching [Maven](https://maven.apache.org/what-is-maven.html) more, and it seems like migrating to this structure will allow us to build out tests, manage dependencies, and deploy more efficiently. It also integrates well with IntelliJ. Check out the quick video [here](https://www.jetbrains.com/help/idea/maven-support.html).

**Comment by CalebKleppner** [comment]
This is above my pay grade, but if the 3 of you think this makes sense, I am fully supportive.

**Comment by HEdingfield** [comment]
If we convert to Maven, we can probably delete the libs directory.

**Comment by HEdingfield** [comment]
#239 is related, since we discuss migrating everything to Gradle.

**Comment by tarheel** [comment]
Converting to Maven/Gradle to own the libs.

**Comment by HEdingfield** [comment]
Gradle migration complete with #272.
