### ISSUE TITLE
Replace com.rcv with unique domain

### ISSUE THREAD

**Issue by HEdingfield** [BrightSpots/rcv#111]
Realized that our package is `com.rcv` currently. Since I'm guessing none of us own the rcv.com domain, we should change it to something unique (i.e. a domain that we actually own). Does anyone own brightspots.org? If so, we could use org.brightspots.rcv. Context [here](https://stackoverflow.com/questions/4620045/why-is-the-root-package-in-source-code-called-com).

**Comment by tarheel** [comment]
No, we don't have brightspots.org, unfortunately. But maybe we should get it...

**Comment by HEdingfield** [comment]
Looks like it's taken unfortunately, but some cool ones are available, like brightspots.network: https://www.namecheap.com/domains/registration/results.aspx?domain=brightspots.org

**Comment by tarheel** [comment]
I emailed the owner of brightspots.us a few weeks ago, but they haven't replied.

**Comment by gngilbert** [comment]
Sounds like something we need to resolve.

**Comment by HEdingfield** [comment]
These all seem like good candidates, and appear to be available on Namecheap:

- .group
- .community
- .us
- .dev
- .engineering

**Comment by HEdingfield** [comment]
Per discussion with Louis and Jon, we like brightspots.network. Louis to buy that domain, then we'll change the package from `com.rcv` to `network.brighspots.rcv`.

**Comment by HEdingfield** [comment]
@tarheel please confirm here once you've bought the domain, and then I'll go forward with these changes. [Google Domains](https://support.google.com/domains/answer/6296464?hl=en) also offers .network, but [NameCheap](https://www.namecheap.com/domains/registration/results.aspx?domain=brightspots.network) is (surprise) cheaper, and I've had good experiences with them. WHOIS privacy protection is free for both services.

**Comment by tarheel** [comment]
OK, I bought it.
