### ISSUE TITLE
support Dominion format

### ISSUE THREAD

**Issue by tarheel** [BrightSpots/rcv#119]
George's comment from #96: "I believe the guys at FairVote have the Dominion data from Santa
Fe."

**Comment by tarheel** [comment]
@gngilbert @CalebKleppner do you know how we can get this data?

**Comment by gngilbert** [comment]
I believe I have the data from Santa Fe. I will try to get it uploaded tomorrow and we can discuss it. I could not figure it out. We may have to talk to Dominion.

**Comment by gngilbert** [comment]
I think I have attached the Santa Fe CVR files here.  Not sure how this works.  If they are not attached, I can send them attached to an e-mail.

[drive-download-20181214T175737Z-001.zip](https://github.com/BrightSpots/rcv/files/2734516/drive-download-20181214T175737Z-001.zip)

**Comment by nealmcb** [comment]
Thanks - fascinating.
Wow - that is such an awful way to deliver CVRs of ranked ballots: a bloated set of CSVs with 205 columns for perhaps 21 candidates, enormous column names over 40 chars each, and so much extraneous and badly-organized data.
I dare say I'd much prefer the json-format output that I expect they have (and used to produce this output).

**Comment by gngilbert** [comment]
That was my reaction as well and why we have not taken on the task of converting it to run in the RCVRC Tabulator.  At some point, however, we need to do this and I am looking for recommendations as to how to do this in the most efficient manner.

**Comment by gngilbert** [comment]
Jon, should you bring David in on this issue?  (I would but don't know how. Thanks.)

**Comment by tarheel** [comment]
@davidryal

**Comment by gngilbert** [comment]
We'll keep this on the shelf for now.

**Comment by chughes297** [comment]
Pedro at FairVote has been working with the San Francisco CVRs I'm attaching to this post, and developed this process for converting the JSON in to a human readable format: 
https://docs.google.com/document/d/1uR94xFn-oB3B_17lftP2gZkLZAGtvs6Wu5rw2vryDsE/edit?usp=sharing. Wanted to share in case it's useful as you guys get started on Dominion
[CVR_Export_20191125163446.zip](https://github.com/BrightSpots/rcv/files/4123087/CVR_Export_20191125163446.zip)

**Comment by tarheel** [comment]
More questions from @moldover:

do we need to handle multiple contests?
how are column headers parsed?  there's a bunch of different text:
Original/Cards/0/Contests/0/Marks/0/Rank
Original/Cards/0/PaperIndex
Original/Cards/0/Contests/0/Marks/8/MarkDensity
do we need to interpret selections, using outstack condition manifest?

**Comment by gngilbert** [comment]
I'm not familiar enough with any of this to provide answers.  Do we need to
bring Keith in on this?

George Gilbert
RCV Resource Center
george.gilbert@rankedchoicevoting.org
336-906-0047

**Comment by tarheel** [comment]
These are the same questions that Jon asked previously over email; I'm just reproducing them here to keep things organized. Presumably Keith has already shared them with Dominion folks.

**Comment by gngilbert** [comment]
Thanks, Louis.

George Gilbert
RCV Resource Center
george.gilbert@rankedchoicevoting.org
336-906-0047

**Comment by nealmcb** [comment]
Thanks for digging out the data and a parsing method. I'm pretty sure I've parsed similar Dominion JSON files before in Python.

Also, as yet another approach, the RLA (SHANGRLA) audit of the election seems to have used the Javascript in this file to parse out just the votes on each ballot in a given contest:

https://github.com/pbstark/SHANGRLA/blob/master/ConvertCVRToRAIRE.html

> The RAIRE format (for later processing) is a CSV file.
> First line: number of contests.
> Next, a line for each contest
> Contest,ID,N,C1,C2,C3 ...
ID is the contest ID
N is the number of candidates in that contest
and C1, ... are the candidate id's relevant to that contest.
Then a line for every ranking that appears on a ballot:
 Contest ID,Ballot ID,R1,R2,R3,...
where the Ri's are the unique candidate IDs.

Yielding [this output file for Mayor](https://github.com/pbstark/SHANGRLA/blob/master/Code/Data/SFDA2019_PrelimReport12VBMJustDASheets.raire)

But I've only glanced at that stuff - I might have misinterpreted something there....

**Comment by CalebKleppner** [comment]
All --  I see that you've gotten
      started on working with Dominion json files for CVRS.  This is
      good, as I'm sure hope you've heard that the Dem RCV contests in
      Alaska, Wyoming and Kansas have recently switched from ClearBallot
      to Dominion equipment.  Yes, we are just 7 weeks away from the
      elections, and the contractor has changed equipment.  This means
      that the cast vote records will be in the json format that San
      Francisco uses (
https://www.sfelections.org/results/20191105/data/20191125/CVR_Export_20191125163446.zip
      ).  
      
      I will probably be conducting the RCV tallies for these 3 states
      and will be relying on the Universal Tabulator.  I'm very eager to
      start testing it with San Francisco data.  
      
      Should I plan on obtaining CVRs in Dominion json format,
      converting them to a human readable format as Pedro worked out
      below, and then tabulating in the Universal Tabulator?
    
    I believe that I'll be receiving a
      large set of CVRs that include both mail ballots and precinct
      ballots, so it will be necessary for me to break the CVRs into
      separate files based on county (Wyoming) or CD (Kansas). 
      
      Thanks for any info you can provide.  I'm happy to discuss anytime
      (203-376-4080, ck@fairvote.org).
      
      Best,
      Caleb
    
    Caleb Kleppner
203-376-4080


    On 1/28/2020 10:21 AM, chughes297
      wrote:
    
    
      
      Pedro at FairVote has been working with the San Francisco CVRs
        I'm attaching to this post, and developed this process for
        converting the JSON in to a human readable format:
        https://docs.google.com/document/d/1uR94xFn-oB3B_17lftP2gZkLZAGtvs6Wu5rw2vryDsE/edit?usp=sharing.
        Wanted to share in case it's useful as you guys get started on
        Dominion
        CVR_Export_20191125163446.zip
      —
        You are receiving this because you were mentioned.
        Reply to this email directly, view it on GitHub, or unsubscribe.
      [
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/BrightSpots/rcv/issues/119?email_source=notifications\u0026email_token=AJ4HUXHFKSGUOXAWXXXEBA3RABEOZA5CNFSM4FPFLTVKYY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOEKDV5IA#issuecomment-579296928",
"url": "https://github.com/BrightSpots/rcv/issues/119?email_source=notifications\u0026email_token=AJ4HUXHFKSGUOXAWXXXEBA3RABEOZA5CNFSM4FPFLTVKYY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOEKDV5IA#issuecomment-579296928",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]

**Comment by gngilbert** [comment]
All, obviously this is very short notice on this change of vendor.  I think
we need to plan a conference call with Caleb for later this week.  I'll ask
chris to send out a doodle poll.

George Gilbert
RCV Resource Center
george.gilbert@rankedchoicevoting.org
336-906-0047

**Comment by tarheel** [comment]
Here's a parser that @catrope wrote for the new format: https://github.com/catrope/sf-rcv/blob/master/parse-new-format.js

And the rest of the code in that repo handles the old format.

More explanation from him:

I apologize for the lack of documentation, so I'll briefly explain it here instead.
Download a ZIP file from the SF elections web site (e.g. this one)
Create a new directory and extract the ZIP file into it
Run my script in this directory, and capture its output in a file
So, in a terminal/shell:

$ wget https://www.sfelections.org/results/20191105/data/20191114/CVR_Export_20191114160248.zip
$ mkdir sf-20191114
$ cd sf-20191114
$ unzip ../CVR_Export_20191114160248.zip
$ node parse-new-format.js > reformatted.json

The attached screenshot illustrates what the output looks like. It's a big array, where every element is a ballot card, and every race is an array of choices. For RCV contests, the first element is the first choice, the second element the second choice, etc; for non-RCV contests (including measures), there is only one element. If a choice is null that means it was left blank (undervote), if the choice is itself an array of multiple values that means multiple choices were selected (overvote). So in the attached example, the District Attorney rankings were 1) blank, 2) Loftus, 3) overvote for both Tung and Boudin, 4) Dautch, and their Mayor rankings were 1) Breed, 2) Pang, 3) Ventresca, 4) blank, 5) Zhou, 6) Jordan+Robertson overvote.

I haven't yet adapted my RCV code to ingest this format, but it shouldn't be too much work, and the format should be relatively easy to deal with for other scripts as well. Since the data for non-RCV races is also all there, you should also be able to compute correlations between contests that appear on the same card (e.g. local measures: how many people voted Yes on A but No on E or vice versa, and where were they located?). One thing I want to look at at some point is the geographic distribution of Nancy Tung's transferred votes: Tung->Loftus, Tung->Boudin and Tung->exhausted were each over 30%, and I'm curious to see if those three groups are concentrated anywhere in particular. I also want to look at the second choices of Boudin and Loftus voters.

**Comment by HEdingfield** [comment]
Latest update: I believe we mostly have this issue addressed with the closing of #404, #406, #407, #408, and #415.

Remaining related open issues (which could probably supersede the need to keep this one open): #434, #437, #438.

@moldover @tarheel, could you please look closely over this issue and file any other necessary issues to address any last loose ends here? Then I think we should be good to close it.

**Comment by tarheel** [comment]
Sounds right to me. Will let @moldover make the final call.

**Comment by moldover** [comment]
Closed via #470
