### ISSUE TITLE
Audit logs are too big to open

### ISSUE THREAD

**Issue by HEdingfield** [BrightSpots/rcv#125]
After doing a single big run (e.g. config_minneapolis_2013_scale.json), the audit log is too big for even Notepad++ to open (700 MB!). We need to figure out a better way to generate these; maybe splitting at 50 MB or some other more reasonable number. Recommend looking up limits for basic text editors and complying with the lowest one.

**Comment by moldover** [comment]
@CalebKleppner do you have a take on this?  I just ran the scale test (by disabling the duplicate CVR check) and the new cleaner audit log format clocks in at  ~252MB.  Is it worth breaking this up into multiple output files?

**Comment by CalebKleppner** [comment]
Yes, we need to break them up into smaller chunks.  Any maybe create 3 
separate log files:

1. full ballot info (rankings, precincts) and how ballot was counted in 
round 1,
2. a file containing all transfers (round 3, ballot id 12345, 
transferred from XX to YY, weight .37), and
3. a file showing how each ballot counted in each round  (ballot ID, 
counted in round 1, counted in round 2, etc).

Or something like that so we don't have such huge files.  One and 3 
would probably be pretty big, but should be easy to import into a 
database program.

Caleb Kleppner
MK Election Services, LLC
203-376-4080

**Comment by moldover** [comment]
@CalebKleppner @tarheel 

Our understanding was to replace the existing audit format with what you are describing as #2 here. 
I spent several hours on this Saturday: https://github.com/BrightSpots/rcv/issues/146 
It seems like now you're saying you want BOTH formats in two or (three??) log files, which was not something we discussed.  Please be really specific about what you're looking for so we can build the right thing.

**Comment by CalebKleppner** [comment]
Sorry, really was just thinking out loud about multiple audit files.  I 
wasn't trying to give specific direction.

So I'd say that any file that exceeds 50MB should probably be broken 
into chunks.

Jon, how 'bout if you give me a link to your 252MB audit log from your 
scale test and I check it out for usability, etc.  Then we can think 
more about the information and format we really want for the log files.

PS I've attached a config file for the scale test that references 13 
unique CVR files (with names 2013-minneapolis-mayor-cvr1.xlsx, 
2013-minneapolis-mayor-cvr2.xlsx, etc.)  So you just need to copy 
2013-minneapolis-mayor-cvr.xlsx 13 times with the right name.

If we do 1 and 2 below in one or two files, then we certainly don't need 
a separate file for 3.

### Possible audit log files for contemplation

1. full ballot info (rankings, precincts) and how ballot was counted in 
round 1,
2. a file containing all transfers (round 3, ballot id 12345, 
transferred from XX to YY, weight .37), and
3. a file showing how each ballot counted in each round  (ballot ID, 
counted in round 1, counted in round 2, etc).

Caleb Kleppner
MK Election Services, LLC
203-376-4080

**Comment by moldover** [comment]
We can make sure any log file bigger than 50MB gets split up. 

Here's the latest output from the fake Mayor race.  I think this will be easier to work with than the "scale" test output.

[2018-09-17_21-51-43_audit.log](https://github.com/BrightSpots/rcv/files/2393214/2018-09-17_21-51-43_audit.log)

**Comment by moldover** [comment]
Fixed.

**Comment by moldover** [comment]
I'm going to just re-purpose this issue keep the history since it's more relevant to any updates to audit log format.

**Comment by CalebKleppner** [comment]
George and I discussed audit log formats and want to play around with some actual files to see if we can come up with log formats that are best-suited for how election administrators and election auditors will sue them.  Let's not play around with the actual file format any more until George and I get back to you.  As for the method of breaking up the audit logs into 50MB chunks and the file names that result, we'll either live with decreasing numbers or you'll figure out how to fix that.  But not pressing right now.

**Comment by moldover** [comment]
SLI has flagged an issue where any validation errors result in no audit log.  This was done because we need to parse the audit log location from the config before we can create the audit log (so there is some reason for this) however we should explore  adding validation errors to the audit or finding a better way to communicate this to the user.
