### ISSUE TITLE
Better handling of undeclared write-ins (UWIs)

### ISSUE THREAD

**Issue by HEdingfield** [BrightSpots/rcv#127]
Currently UWIs are eliminated in the first round automatically, apparently even if they're in the majority. @tarheel suggests:

> At some point we probably need to add a config param for this. Maybe a boolean indicating whether UWIs are allowed to win.

**Comment by tarheel** [comment]
@CalebKleppner said: "I do believe that's the concept of UWI:  it goes out in the first round no matter what, and can't win."

But if someone really wants to give UWI the chance to win in our tabulator, they can just not use undeclaredWriteInLabel, and UWI will be treated like a normal candidate.
