### ISSUE TITLE
Address UI loose ends

### ISSUE THREAD

**Issue by HEdingfield** [BrightSpots/rcv#128]
Review [UI design doc](https://docs.google.com/document/d/1jQmhIoHNo0cNxD8h3xDHmiGyvxaUwbFi0Ieh3-W-2_U/edit#heading=h.f0b27cp98y5j) with everyone and see if anything else should be taken from it. Now that all the pieces are in place, we can think a bit more about label language, user-friendliness, organization, flow, etc.

**Comment by gngilbert** [comment]
Obviously we need to specify the "loose ends."

**Comment by HEdingfield** [comment]
I think this is all purely quality-of-life stuff, so no big deal. I'll review the design doc again down the line just to make sure we didn't miss any cool ideas.

**Comment by HEdingfield** [comment]
Superseded by #461.
