### ISSUE TITLE
Maybe add progress bar for GUI tabulation

### ISSUE THREAD

**Issue by HEdingfield** [BrightSpots/rcv#133]
See:
https://stackoverflow.com/questions/34357005/javafx-task-update-progress-from-a-method

And:
https://stackoverflow.com/questions/23701639/call-tasks-updateprogress

**Comment by chughes297** [comment]
I think this would be really great UI/UX - right now it's not obvious where to look for any signs of tabulation progress

**Comment by yezr** [comment]
#679 and #825 have been written to implement this! Closing as a dupe
