### ISSUE TITLE
GUI closing confirmation pop-up

### ISSUE THREAD

**Issue by HEdingfield** [BrightSpots/rcv#135]
Should probably add for both main menu and config creator, e.g.:
https://www.youtube.com/watch?v=ZuHcl5MmRck&index=8&t=0s&list=PL6gx4Cwl9DGBzfXLWLSYVy8EbTdpGbUIG

Probably ties into #134.

**Comment by HEdingfield** [comment]
Closing the GUI when in the middle of tabulating needs to kill all threads.

**Comment by chughes297** [comment]
Added deliverable because I expect it's likely people will accidentally attempt to close the app frequently, would like to keep that from happening.

**Comment by HEdingfield** [comment]
Closed with #320.
