### ISSUE TITLE
Align default values in ElectionConfig with GUI, and consider default values for all

### ISSUE THREAD

**Issue by HEdingfield** [BrightSpots/rcv#136]
1. Make sure all the de facto default values in the `ElectionConfig` getters/setters align with the documentation and config creator GUI
2. Discuss pre-populating / offering default values for all fields

**Comment by chughes297** [comment]
Doesn't sound like this is necessary for cert but happy to provide feedback on what default values make the most sense.

**Comment by HEdingfield** [comment]
May be related to #211, and may be a moot point now. Verify.

**Comment by moldover** [comment]
@HEdingfield @tarheel circling back to part 2 of this.  In general I think default-values-for-all is the right way to go, but I'm not sure if it's too late for this given the flurry of recent settings changes, and the fact that this would break all the unit tests again.

The way I envision it, every setting would have a default specified in the documentation.txt, which would be applied when config is loaded into the gui, to any missing values.  For example, today a config is valid without any undervoteLabel setting, or if undervoteLabel=null.  We would change this to require undervoteLabel be present to validate.  On loading a file into the GUI a null undervoteLabel would be replaced with "".

**Comment by HEdingfield** [comment]
I'm 95% sure what you just described is indeed the case now that I've switched a lot of the fields to Strings. If you load a config without `undervoteLabel` present, or with the value set to `null` in the JSON, it'll then ask you to save before you tabulate and when you save it'll replace it with "".

The only other situation I can think of that might be relevant is when a key isn't present for something like `maxRankingsAllowed`, you load it, then it tells you you need to save; it saves it as `maxRankingsAllowed` = "", instead of `maxRankingsAllowed` = "max", which is the GUI suggested value. I think that's fine though, as the idea is that the GUI should save whatever's in the fields and do no subbing behind the scenes. The suggested values should only apply when you start a new config file.

**Comment by moldover** [comment]
So saving shouldn't apply deafult, but loading would, right?
In this example the max rankings key isn't present (null) on loading GuiConfigController.loadConfig would notice, and set "max" into the text editor instead and log it.  The ui edit listener counts this as an edit and will prompt to save.  User can now make any edits.  On saving, no defaults are applied, simply write whatever is in the boxes.  They should all be strings at this point.

**Comment by tarheel** [comment]
I believe that @moldover's maxRankingsAllowed example is analogous to what I did with winnerElectionMode: the UI populates it with "standard" by default, and if you load a config that has a missing or invalid value, the config value gets ignored and the selector stays set to "standard".

**Comment by HEdingfield** [comment]
@tarheel aha, you're exactly right. So I'd argue that if it has a bad or unknown value for `winnerElectionMode`, it should present a blank value for the box instead of "standard", and then force the user to knowingly choose the correct value in order to pass validation. But it sounds like you guys both prefer it'd overwrite any bad or not present values with a suggested value? I'm in favor of the former because it forces the user to consider what could be off with their config file. Silently injecting suggested values could cause this to completely go over their heads.

I think we already had this discussion a while back (the whole "suggested vs. default" debate), and this was what we landed on.

**Comment by tarheel** [comment]
> So I'd argue that if it has a bad or unknown value for winnerElectionMode, it should present a blank value for the box instead of "standard", and then force the user to knowingly choose the correct value in order to pass validation.

I would actually be fine with this approach; in fact, it's what I was trying to implement originally, but I couldn't get it to work. As I mentioned, if you let the code set the choice box to the unknown value when loading a config, the UI selector will still show "standard" even though the underlying value has been changed. I suspect that we'd have to refactor the code for these form elements a bit to make this work properly.

**Comment by HEdingfield** [comment]
Gotcha, it's an easy fix:

`choiceWinnerElectionMode.setValue(config.getWinnerElectionMode() == WinnerElectionMode.MODE_UNKNOWN ? null : config.getWinnerElectionMode());`

I'll include that in my next PR.

So sounds like we're on the same page, @tarheel. That sound good to you @moldover? If so, I think we can close this issue.

**Comment by moldover** [comment]
@HEdingfield works for me.  Thanks.
