### ISSUE TITLE
Better resizing reactivity in GUI

### ISSUE THREAD

**Issue by HEdingfield** [BrightSpots/rcv#138]
- If window is super small, it should have scrollbars
- If window is fully expanded on desktop it should use the space better (especially config creator)
- It should adjust to resizing in between as expected too

**Comment by gngilbert** [comment]
I have had persistent problems viewing the bottom line of the GUI screen

**Comment by HEdingfield** [comment]
Will make an effort and repro by changing resolutions. May need to drop off essential tag due to time constraints.

**Comment by HEdingfield** [comment]
Closed with #297.
