### ISSUE TITLE
Address Tabulator TODOs and FIXMEs

### ISSUE THREAD

**Issue by HEdingfield** [BrightSpots/rcv#142]
**Tabulator.tabulate()**
```
// TODO: better encapsulation
// TODO: avoid recomputing these every round (since they should be static for a given candidate once that candidate has won)?
```

**Tabulator.identifyWinners()**
`// TODO: some rules require >= instead of just > here`

**Comment by HEdingfield** [comment]
#306 made progress on this, but we also need to remove FIXMEs.

**Comment by tarheel** [comment]
Ah, nuts. OK.

**Comment by tarheel** [comment]
@HEdingfield could you explain the FIXMEs in GuiConfigController? They both say "FIXME: If user enters bad data, value is nulled out instead of reverting to previous value." But when I test the app, it does indeed revert to the previous value if I try to enter a non-integer string. Is there anything to fix here?

**Comment by HEdingfield** [comment]
Repro:
1) Use the CVR GUI to enter values for all six fields, then add it to the list
2) Double-click each field and attempt to enter bad data (e.g. text for each column index) and then press enter
3) Observe that, for First Vote Column and Row, the value reverts back to what was in there before; but for ID Column and Precinct Column, the bad data is just replaced with a null value... this likely has to do with the latter two not being required fields

This also caused me to discover another small bug. Filing #325.

**Comment by HEdingfield** [comment]
Addressing this in #328. I'll get rid of the FIXMEs there.

**Comment by HEdingfield** [comment]
All good now.
