### ISSUE TITLE
review overvote options

### ISSUE THREAD

**Issue by tarheel** [BrightSpots/rcv#151]
Caleb thinks we only need these three:
- always exhaust
- always skip to next rank
- exhaust if multiple continuing

He'll review with George.

**Comment by gngilbert** [comment]
Agreed but we did not settle on whether to leave the other options for possible future use or to remove them.  


Also discussed, without resolution, the implications of the third option, "exhaust if multiple continuing."  This is, or has been, used by a couple of jurisdictions.  The problem I have with it is that it treats ballots differently in early tabulation rounds than later rounds.  Clearly any overvoted ballot would have multiple continuing candidates in Round 1 with the likelihood of single continuing candidates remaining increasing in later rounds.


My answer to this unequal treatment is to suspend overvoted ballots pending the possible elimination of all but one of the candidates selected in the overvote.  This is not, and has not been used, in RCV elections anywhere to our knowledge so, for the time being, I guess we will just live in an imperfect world.  I bring it up just to alert you to the potential problem and a possible solution for future reference.

**Comment by tarheel** [comment]
OK. I guess my vote would be to leave support for all the variants in place in the code... unless we think they're going to confuse people.

**Comment by CalebKleppner** [comment]
My belief is that the following options are currently used in statute, so they should be listed first and in this order

exhuastImmediately
alwaysSkipToNextRank
exhaustIfMultipleContinuing

The following options are not currently being used (as far as I know).  If we want to keep them, let's list them last, and perhaps adds a (not supported), so they appear like this on the drop-down:

exhuastIfAnyContinuing (not supported)
ignoreIfAnyContinuing (not supported)
ignoreIfMultipleContinuing (not supported)
