### ISSUE TITLE
GUI redesign

### ISSUE THREAD

**Issue by HEdingfield** [BrightSpots/rcv#152]
* Get rid of the startup menu screen in favor of going straight to the config creator
* Move buttons to top above tabs; add buttons for new, load, tabulate, and quit
* Save button should read "Save..." to indicate that it'll summon a dialog
* A label at the top should communicate what's currently loaded (else say something like <new config>)
* Save listener (see #134) checks need to occur on new, load, tabulate, quit and alert user asking if they want to save first
* Add and Delete buttons need to be placed so that they are more intuitive (for CVR sources and possibly candidates)
* Delete Selected buttons should be disabled if nothing is selected
* Ability to drag and edit rows (e.g. for candidate permutations)

**Comment by gngilbert** [comment]
Can't tell how much of this has been addressed.

**Comment by HEdingfield** [comment]
This has mostly all been addressed and is superseded by #461 anyway. Moving any last unresolved items to that issue.
