### ISSUE TITLE
Output correct execution logging path when program starts

### ISSUE THREAD

**Issue by HEdingfield** [BrightSpots/rcv#158]
From conversation in #156:

> @HEdingfield 13 hours ago  Member
> For some reason this isn't parsing %g properly in the log message:
> 2018-09-03 22:05:23 PDT INFO: RCV Tabulator logging execution to C:\...\rcv\rcv_%g.log
> Even though it's logging (properly) to the file rcv_0.log. Not worth blocking this commit on if it's not a quick fix; please just file a small issue if you go forward without fixing.
> 
> @moldover
> moldover 2 hours ago  Member
> %g isn't a String format code; FileHandler uses it, so this is "correct". It's just debug output so I think it's fine. If we ever show it to the user I'll clean it up somehow.

Confirmed that this is visible to the user if they're using the console. Also looks like [it might be painful](https://stackoverflow.com/questions/38154158/how-can-i-output-the-name-of-the-current-java-util-logging-logger-log-file-name) to get the actual filename.

**Comment by gngilbert** [comment]
Is this resolved or not?

**Comment by HEdingfield** [comment]
Still an issue, but probably not super critical to deal with right now unless it can be done easily.

**Comment by HEdingfield** [comment]
We agreed to just change %g to *, so it looks like:

> RCV Tabulator logging execution to C:...\rcv\rcv_*.log

**Comment by HEdingfield** [comment]
Note: this also occurs for audit logs and possibly in other cases too. Search comprehensively for this.

> Done logging tabulation to: C:\Users\MyName\IdeaProjects\rcv\src\test\resources\network\brightspots\rcv\test_data\2013_minneapolis_park\output\2019-06-13_23-03-28_audit_%g.log
