### ISSUE TITLE
in macOS, app doesn't quit properly if file dialog is open

### ISSUE THREAD

**Issue by tarheel** [BrightSpots/rcv#160]
If I have the load or save dialog open and close the main window, the dialog stays open. If I try to quit the app, nothing happens, even after I close the dialog. I have to kill the app by clicking the stop button in IntelliJ.

Similarly, if I have the dialog open and select java > Quit, it closes the main window, but not the dialog or the app as a whole, and I end up having to kill it.

**Comment by HEdingfield** [comment]
Note: this appears to be a MacOS issue, as I'm unable to repro it in
Windows; everything works as expected there. Will test in Linux and report
back.

**Comment by moldover** [comment]
Fixed.
