### ISSUE TITLE
Unable to run on Linux

### ISSUE THREAD

**Issue by HEdingfield** [BrightSpots/rcv#168]
When attempting to debug #160, I was unable to get the tabulator running on my Linux machine.

Couldn't verify because:
`$ /usr/local/buildtools/java/jdk10-64/bin$ ./java -jar ~/Downloads/RCV_UniversalTabulator_20180908/RCV_UniversalTabulator_20180908/rcv.jar `

Would cause:

> Error: Could not find or load main class com.rcv.Main
> Caused by: java.lang.NoClassDefFoundError: javafx/application/Application

I initially assumed it was because there's no MANIFEST.MF file in the version @moldover compiled, but I also tried the version I compiled which included a manifest and had the same problem.

**Comment by nealmcb** [comment]
I still see this problem, on Ubuntu 18.04 LTS Bionic:

```
openjdk 10.0.2 2018-07-17
OpenJDK Runtime Environment (build 10.0.2+13-Ubuntu-1ubuntu0.18.04.4)
OpenJDK 64-Bit Server VM (build 10.0.2+13-Ubuntu-1ubuntu0.18.04.4, mixed mode)

```
 And I don't have another system to run it on.
Any luck figuring out what's going on?

**Comment by tarheel** [comment]
Sorry, we haven't had a chance to debug this yet. :/ We'll try to get to it in the not-too-distant future...

**Comment by tarheel** [comment]
@HEdingfield or @nealmcb: could you try the approach I suggested in #239 and see if that fixes it for you?

Specifically: download the [JavaFX SDK for Linux](https://gluonhq.com/products/javafx/), then add command-line args to reference it. Something like this:

`java --module-path javafx-sdk-11.0.2/lib --add-modules=javafx.controls,javafx.fxml -jar rcv.jar`

I'm not sure if it will make a difference if you're running JRE 11 vs. 10.

I tried testing it myself on a remote Linux machine, but I got a different JavaFX error because I'm just sshing in ("java.lang.UnsupportedOperationException: Unable to open DISPLAY"), and I don't want to deal with setting up VNC or something similar right now.

**Comment by tarheel** [comment]
This rigmarole makes me wonder whether we should start releasing a separate build that's intended only for command-line operation and doesn't have any JavaFX dependencies.

**Comment by nealmcb** [comment]
Thank for follwoing up, @tarheel!

I did this on Ubuntu bionic 18.04, where I have OpenJDK 11:

    $ apt-get install openjfx
    $ java --module-path javafx-sdk-11.0.2/lib --add-modules=javafx.controls,javafx.fxml -jar ../rcv_20190302.jar
    Error occurred during initialization of boot layer
    java.lang.module.FindException: Module javafx.controls not found

Any more tips?

This looks perhaps relevant:

https://stackoverflow.com/questions/51843208/running-javafx-sample-on-jdk-11-with-openjfx-11-jmods-on-module-path

**Comment by tarheel** [comment]
Ah, great. Yeah, I saw your initial comment and was going to tell you to update the path.

So the only remaining question in this thread is why Linux has the JavaFX error under JRE 10. At least in @nealmcb's case, I believe the answer is that you were using OpenJDK 10, and that distribution also omits JavaFX. @HEdingfield: presumably something similar applies to your case?

**Comment by HEdingfield** [comment]
I propose we circle back on this issue once we resolve #239, because I think that will solve our problems here.

**Comment by tarheel** [comment]
If what I said in my last comment sounds right (my hypothesis for why it was failing even under JRE 10 for both of you), then yes, I agree -- this and #239 are duplicate issues.

**Comment by HEdingfield** [comment]
TODO: update `UserGuide.txt` when resolving this issue, because it mentions it directly.

**Comment by HEdingfield** [comment]
Just pulled PR #272 to my Linux machine, built a distZip using Gradle, and was able to get it running using OpenJDK 11!

**Comment by tarheel** [comment]
![bitmoji](https://render.bitstrips.com/v2/cpanel/a640399f-2837-485b-881e-3de373e8f801-0878c302-d67c-4bb7-80ba-b554896c3f48-v1.png?transparent=1&palette=1&width=246)

**Comment by HEdingfield** [comment]
PR #272 is now merged. Confirmed that versions built on a Linux system using Gradle's `distZip` or `jlink` tasks work on Linux. #57 and #282 focus on figuring out how to do Linux builds on any platform.
