### ISSUE TITLE
round number confusion

### ISSUE THREAD

**Issue by tarheel** [BrightSpots/rcv#169]
It looks like there's a bit of disagreement about which "round" an event happened in.

If you look at the [2013 Minneapolis Park results](http://vote.minneapolismn.gov/results/2013/2013-park-board-at-large-tab), the first eliminations and transfers are shown happening in round 2.

In the [2018 Maine results](https://www.maine.gov/sos/cec/elec/results/2018/democraticgovfinal.xls), the first eliminations and transfers are instead associated with round 1.

The vote totals shown are the same either way -- round 1 shows first preferences, and round 2 shows updated totals after the first set of eliminations -- but I'm not sure which round number we should use when we report when an elimination happened. Is it the round before the totals are updated with the transfers, or the round in which they're updated?

We're actually not even being consistent ourselves: in our audit log, we say that the first eliminations happen in round 1, but in our XLSX output, we associate these eliminations and transfers with round 2.

**Comment by moldover** [comment]
I just "fixed" the summary spreadsheets so they are consistent with Minneapolis and our audit log.  I agree this is more sensible, although I think a better format would not combine actions with counts in a single column:

Counts 1   Actions 1  Counts 2  Actions 2
 10                                15            winner
 5                eliminated  0 
 9                                   9            eliminated

**Comment by moldover** [comment]
Given that we don't display transfers on the summary report anymore, and the actions are consistent, can we close this issue, or is there something more to do here?

**Comment by tarheel** [comment]
I'll take this and do one more pass over everything to confirm that it's consistent.

**Comment by tarheel** [comment]
@moldover: OK, yeah, it seems like we're being consistent now.
