### ISSUE TITLE
New feature requested:  ability to exclude a candidate from a tabulation

### ISSUE THREAD

**Issue by CalebKleppner** [BrightSpots/rcv#177]
The concept is pretty simple:  sometimes a candidate withdraws from a race (or dies), and the candidate receives votes in the CVRs.  When you run the tabulation, you want to skip to the next ranking anytime a CVR would count for the withdrawn candidates.  (This is also the way Cambridge fills a vacancy when a council member resigns, gets elected to another office, or dies:  they re-do the tabulation excluding that candidate from the process.)

I would imagine that we could add a check box on the candidate tab of the GUI that would be labeled, "Exclude".  You could exclude any number of candidates and then run your tabulation.  The candidate could show up in the results but would have zero votes in every round.

I have no idea how tricky this will be to implement, but I imagine that you would create another state for candidates:  continuing, elected, eliminated and now "excluded".  If a CVR would count for an excluded candidate, you should skip to the next ranking, with no effect on skipped rankings or anything else.

Why don't you all think about this and see what milestone we should add it to. I put it in v 1.0, but that could change.

**Comment by CalebKleppner** [comment]
In the GUI, I imagine radio button or check marks next to cand names and codes to indicate excluded cands.

If you have states for cands, such as elected, eliminated and continuing, perhaps excluded becomes another.

---
Caleb Kleppner
MK Elections
203-376-4080


---- On Sat, 06 Oct 2018 17:19:49 -0500 notifications@github.com wrote ----

This is easy to support in the tabulation logic.

@HEdingfield: thoughts on how we should represent this in the config and in the UI?

**Comment by tarheel** [comment]
Yeah. I'm just wondering how we can make this option as unobtrusive as possible in the UI, since it will rarely be used.  But I guess it's OK if we have a checkbox or a dropdown with the normal option selected by default.

**Comment by CalebKleppner** [comment]
In the blank column to the right of "Code", let's just have a column labeled "Exclude?"  It's got check boxes that are by default empty.  If you want to exclude one or more candidates, you just check the box:

![image](https://user-images.githubusercontent.com/41450076/46893604-7cfcbd80-ce3f-11e8-9bac-7063da24debb.png)
