### ISSUE TITLE
Use event driven (read-only) model for parsing xlsx files

### ISSUE THREAD

**Issue by moldover** [BrightSpots/rcv#188]
https://stackoverflow.com/questions/13020658/error-while-reading-large-excel-files-xlsx-via-apache-poi

http://poi.apache.org/components/spreadsheet/index.html

**Comment by HEdingfield** [comment]
This was sparked by email thread "CVR from Maine CD2" where @CalebKleppner was unable to complete tabulation of `cvr_2018_maine_governor_primary_dem.xlsx` on a Win 7 machine with 8 GB of RAM. Anything above 200k records would cause the tabulator to run indefinitely.

We should circle back with this machine / config once the fix is in to verify.

**Comment by CalebKleppner** [comment]
Just had a discovery about the annoyance of Java updates:  I had JRE 10 on my Win 7 machine.  Java wanted me to update, which led to uninstalling Java 10. At which point, I had no Java on my machine.  So I installed JDK 11, but guess what?  JDK 11 no longer includes JRE, so our tabulator doesn't run.  So I think you can either install JDK 10 (which is no longer available from Oracle website) or you can actually install the last JRE that is listed on Oracle website, which is JRE 8.  To my surprise, the tabulator runs on my Win 7 machine with JRE 8.  Go figure!  What a waste of time.  I'll leave JRE 8 on my Win 7 machine and see if it causes any problems with tabulator performance. But first test of CD2 using 2 input files for the CVRs went fine.

**Comment by moldover** [comment]
@CalebKleppner could you try re-running your test with the latest version:

https://drive.google.com/drive/folders/1uwn6UrHPSsbIGj3XiWErSwg-ysag5TEm

**Comment by CalebKleppner** [comment]
I ran both Maine Dem gov primary and CD2 General, and they both ran very 
rapidly with no crashes or hangups, so I think you all solved the 
problem that was causing crashes on the Win 7 machine when the CVR files 
got too big.

Just ran an excellent multi-seat test:  2707 votes, 30 candidates, 
electing 12.  Using an integer threshold and 6 decimals for 
calculations, our numbers matched ChoicePlus Pro to 5 decimal places.  I 
think that shows that our calculations are solid except for possible 
rounding/truncation based on the number of decimals. I will try to rerun 
more of George and Herb's multi-seat tests, but I think we're in good shape.

Fine work, all,
Caleb

Caleb Kleppner
MK Election Services, LLC
203-376-4080
