### ISSUE TITLE
Create Herb60 and maybe tiebreak regression tests

### ISSUE THREAD

**Issue by moldover** [BrightSpots/rcv#197]
I'm not sure how these are supposed to play out.
Multi_winner_Herb60
test_tiebreak

**Comment by gngilbert** [comment]
I don't recall the reason for originating these suggested tests but they probably don't need to be pursued as long as we cover the needed functionality tests.

**Comment by HEdingfield** [comment]
Both tests were deleted in #295, but per my comments in that PR, I'd still like us to keep a copy of the tiebreaker files:

> Can we please keep `tiebreak_test_TODO` (and maybe just rename it to `test_interactive_tiebreaker`)? It's currently the only way I know of to trigger the interactive tiebreaker with our test files, and that's important for both development purposes and for allowing users to see the full extent of the software's capabilities (I'm planning to include this with the download).

Again, as I mentioned in the PR comments, I think we should make the distinction between "test" input and "example" input here. This is a case of example input; it's not directly related to a unit test, but I want to include it as a sample file for users to play with in #281.

@moldover please re-add and rename the config and CVR when you get a chance. I'll reorganize the unit tests and example input as part of #78.

**Comment by moldover** [comment]
@HEdingfield yeah that makes sense.  I'll put them in the next PR and close this since this issue has been addressed.

**Comment by HEdingfield** [comment]
I'd rather keep this one open as opposed to creating a new one to remember to get those files re-added. I'll add myself as an assignee too so I can remember to close it once the files are back in.

**Comment by HEdingfield** [comment]
Closed with #316.
