### ISSUE TITLE
Make Max Rankings and Max Skipped Rankings Optional

### ISSUE THREAD

**Issue by progressnerd** [BrightSpots/rcv#199]
Can these just default to unlimited, or equivalently, the number candidates?

**Comment by tarheel** [comment]
This seems reasonable to me.

@HEdingfield, @moldover: any objection?

**Comment by moldover** [comment]
No objections here, sounds like a good idea.  I'd suggest a default setting of 0 means limits are "number of declared candidates".  "Unlimited" seems confusing as terminology since one couldn't physically rank (or skip) more than max candidates on a ballot anyways.

**Comment by progressnerd** [comment]
"Number of candidates" sounds good to me. 0 is already a valid value for "max skipped rankings," though, I think.

**Comment by moldover** [comment]
I just realized that too, whoops.  Maybe just spell it out like "numDeclaredCandidates".

**Comment by tarheel** [comment]
I would prefer to use null/blank to denote no limit. That feels more intuitive to me, provided we can get the UI to handle it properly.

**Comment by tarheel** [comment]
(And note that the number of declared candidates isn't necessarily the same as unlimited, because there could be write-ins.)
