### ISSUE TITLE
Infinite loop with "Continue until two candidates remain"

### ISSUE THREAD

**Issue by progressnerd** [BrightSpots/rcv#200]
I hit an infinite loop when using "Continue until two candidates remain." The number of rounds never terminates.

My JSON config (as a txt because github doesn't allow .json attachments):
[president.json.txt](https://github.com/BrightSpots/rcv/files/2696284/president.json.txt)

My CVR:
[Test-Ballot-President.xlsx](https://github.com/BrightSpots/rcv/files/2696289/Test-Ballot-President.xlsx)

**Comment by tarheel** [comment]
Thanks for catching this! I'll take a look soon.
