### ISSUE TITLE
Safeguards against changing "if not supplied" behavior in future versions

### ISSUE THREAD

**Issue by HEdingfield** [BrightSpots/rcv#211]
PR #203 included the following conversation:

> @HEdingfield
> Something is telling me that it's better to keep the original design here (using ContestConfig). Maybe this stems from me thinking that explicit is always better than implicit, even for unspecified "default" settings.
> 
> For example, say we have a default value of 2 for a setting in one version of the software. By using ContestConfig, it would actually populate this default value in the GUI, then force the user to re-save before running the tabulator and there's a clear record of what all the settings were. Then in a later update to the software we change the default value to 3. If users don't have that explicitly-defined (default) value in the config, I can imagine them being very confused as to why they can't replicate past results unless they've been following the patch notes closely. Does that make sense?
> 
> Of course, this leaves us with the problem of how to indicate "unlimited" for maxSkippedRank. I think maybe -1 could be a good value for that, and just note the significance in the documentation.

> @tarheel
> I don't really like the idea of using -1 to signify unlimited. It's more intuitive to indicate no limit by just not specifying a limit. But I think we can handle this fine if we update the code so that we don't try to add the default value back when the user has cleared a non-required field.

> @HEdingfield
> I'd like to play around with it a bit once a commit is in to see how this feels, but I think that sounds reasonable.

This solution mostly addresses the problem I brought up, but it seems to me that we'd have to be very careful to not modify "if not supplied" behavior in future versions. Any thoughts on how to safeguard against this, or arguments against it being necessary?

**Comment by HEdingfield** [comment]
We discussed not allowing any "if not supplied", i.e. forcing the user to specify in every single case. The `unlimited` case can be handled by setting an upper limit for `MaxSkippedRanks`, like 10000, and instructing users to input that number.

The result is a config file that explicitly includes all arguments.

**Comment by moldover** [comment]
@HEdingfield @tarheel:  Thoughtful default values (particularly for the many arcane RCV variations we support) provide the most value to our users.  We shouldn't force everyone to spend time learning what a Hare Quota is to use our software.  It isn't scalable.  Put another way, if a user doesn't know or care enough about a parameter to set it, and we are thoughtful in our default values, and we communicate this behavior ("warning: config file doesn't specify 'useHareQuota' defaulting to 'false') we will be in good shape.

**Comment by moldover** [comment]
And for example, version 2 could say, "warning: config file doesn't specify 'useHareQuota' defaulting to 'true'.  Version 1 defaulted to 'false' because bla bla bla but now we default to 'true' because bla bla bla.

**Comment by tarheel** [comment]
We're effectively already doing this because we have a UI for generating a config, and it pre-populates values (called "suggested" in the code) for most fields. The user can ignore the Hare quota option and all the other booleans and it will save them all as false, which is a sensible default value for all of them. So I'm not sure what we actually need to change here... unless you think it's important to make the process of manually creating a config file more user-friendly. (I don't.)

**Comment by HEdingfield** [comment]
You both bring up good points; as long as our config files save ALL parameters (and yes, the GUI helps with suggested values), we're mostly good here, and we shouldn't need to engineer the complex sorts of error messages @moldover brings up above, as the previous "if not supplied" value will be clearly saved in the config, and will load accordingly.

I think the problem is specifically with, e.g., where undefined / no value has a special significance (e.g. "unlimited"). My point is that we can't allow undefined / no value as a valid option when saving a config (except for obvious things like "" strings for naming the contest, etc.).

This also reinforces how important it's going to be to include version number in the config file.

**Comment by moldover** [comment]
Gotcha.  So no problem changing default values.  You want to ensure that a missing or undefined parameter always results in the default value.
- all parameters have a default value
- null or missing should never be a valid value
- null or missing parameters get their default when a config is loaded (we should log this when it happens)

That sounds good to me.  I don't think any safeguards are needed, it's just a policy we enforce for the config parameters.

As for the config version I say use semantic versioning here as well.  It is stored as a top level key/string in the config json, "version" : "1.0.0"  

The first answer here is pretty on point as for how we should approach this [https://stackoverflow.com/questions/10042742/what-is-the-best-way-to-handle-versioning-using-json-protocol](url)

Related question: there's a comment in ContestConfig.java that all booleans should default to false, does anyone know why that is?

**Comment by tarheel** [comment]
> there's a comment in ContestConfig.java that all booleans should default to false, does anyone know why that is?

Not sure about that comment, but I do know that the Jackson parsing has the unfortunate behavior of supplying default values for missing fields. If a config file is missing one of the booleans, our code will still load it and just fill in false for that field. We should probably fix that...

> why the 'suggested' naming instead of 'default'?

Hylton recommended this for clarity. Default = filled in by the app if the field is missing from the config; suggested = prepopulated in the config editing UI. It's just semantics.

**Comment by HEdingfield** [comment]
@moldover as I mentioned above in detail, `MaxSkippedRanks` uses null to convey "unlimited", which is no bueno (there may be other settings that do this too, we should double-check). I also don't think we should ever fail to load a config in the GUI, as I recently addressed in one of my PRs, but we can fail during validation if we want.

I like the post you linked to; are you suggesting we use the gson library? Worth bringing it to the other thread we have going on versioning the config file.

The comment about setting booleans to false is something we discussed in depth in some other issues / PRs. I can't exactly recall it at the moment, but I think it most like has to do with what @tarheel said. I strongly recommend against rocking the boat on this while we're crunching for 1.0.0, as there's really no reason to do so at this point.

**Comment by moldover** [comment]
Got it.  Thanks for catching me up.  I'm just gonna go with Hylton's idea of an 'effectively unlimited' default value.  It covers all the bases in a reasonable way.  Then I'll check and make sure everything lines up between code, UI, and docs for #136.  

Moving config version convo to #43

**Comment by HEdingfield** [comment]
Got sucked into the rabbit hole and just spent a bunch of time auditing these settings. I made a config with zero of the "if not supplied" settings included, and then saved it in the GUI and found that many are already populated automatically and saved in the config. However, there are a number that we'll need to change to also explicitly save as well when not supplied. Here's what we'll need to do to fully address this issue:

- Change `maxSkippedRanksAllowed` to required (in validation and UI) and have the GUI suggest a value of 999999
- Either do the same for `maxRankingsAllowed` (as long as 999999 is cool, rather than the total number of candidates; I'm not sure if this makes it behave differently), or change it to behave like `outputDirectory` where it automatically injects the total number of candidates if left blank when you attempt to tabulate, and requires you to save again... potential edge case issue with this though: if you add a candidate later, and forget to bump up the `maxRankingsAllowed` setting
- Modify all the below so, if not supplied, the config file still saves keys in the JSON for them with "":

> outputSettings:
> "contestJurisdiction" (interestingly, "contestDate"  already saves a "" string if not defined, so maybe we can just duplicate that logic to most of these other fields)
> "contestOffice"
> 
> cvrFileSources:
> "idColumnIndex" (this could be tricky to save "" since it's not a string)
> "precinctColumnIndex" (this could also be tricky to save "" since it's not a string)
> "provider"
> 
> candidates:
> "code" (will likely require us to add a Java line somewhere to ignore this field if == "")
> 
> rules:
> "overvoteLabel"
> "undervoteLabel"
> "undeclaredWriteInLabel"
> "rulesDescription"

**Comment by tarheel** [comment]
> Change maxSkippedRanksAllowed to required (in validation and UI) and have the GUI suggest a value of 999999

This still feels weird to me. I still find myself wishing we had a clean way to represent a null value. One idea that just occurred to me (feel free to shoot it down): start representing *all* fields as strings in the config, so it's easy to use the empty string to signify null. Do the string to number/boolean/whatever conversion ourselves.

> potential edge case issue with this though: if you add a candidate later, and forget to bump up the maxRankingsAllowed setting

I would prefer to avoid creating this edge case.

> "idColumnIndex" (this could be tricky to save "" since it's not a string)
> "precinctColumnIndex" (this could also be tricky to save "" since it's not a string)

Yeah, how would this work?

**Comment by HEdingfield** [comment]
It's late at night and maybe I'm just not thinking straight, but I think that's an interesting idea actually, and it would get around the column index values issue since we could save the int as a string. Seems like it would probably take quite a bit of re-plumbing (and fixing up test configs), but maybe it's doable by the 1.0.0 deadline? @moldover (and less tired me) for sanity check please.

**Comment by tarheel** [comment]
I don't think it would be too painful. We'd just redefine every field in RawContestConfig as a String, and  then we'd have to update a bunch of the getters in ContestConfig and change some logic in the GUI. I'd be willing to attempt it after I finish my essential tasks.

**Comment by moldover** [comment]
> This still feels weird to me. I still find myself wishing we had a clean way to represent a null value. 
@tarheel There is a null value object in JSON, which can work with Integer and Jackson e.g. `"maxSkippedRanksAllowed" : null,`  We can go with that way but would need to remove those @JsonInclude(JsonInclude.Include.NON_NULL) annotations for it to write on save.  @HEdingfield do you remember why those were needed?  The commit message says 'now exclude all non-null fields in config files during save'

**Comment by HEdingfield** [comment]
I think I put two of those in there because I was just replicating what @tarheel had done originally in this commit: https://github.com/BrightSpots/rcv/commit/9d64c4ae6fd9dea384947c5a04592aa40a333ab7

So, it's hard for me to give a justification at this point, beyond cleaner, shorter config files, which obviously takes a back seat to this. So, if we go this route, I guess we a) don't need to stringify anything, and b) just need to allow null for `maxSkippedRanksAllowed` and `maxRankingsAllowed`? I think that seems reasonable to me. We should still definitely make all the changes in the third bullet point in my big comment above too.

**Comment by HEdingfield** [comment]
@moldover has done solid work in #322, but after looking at it in practice, I really don't think it's addressing the entire point of this issue... "Safeguards against changing "if not supplied" behavior in future versions".

If we allow stuff like:
>     "maxSkippedRanksAllowed" : null,
>     "maxRankingsAllowed" : null,    

And "if not supplied" changes in the future, what protection do we have?? We've got a case of non-replicable behavior resulting from not explicitly defining what we mean in the config, and to me that's just a seriously shitty situation. I don't want to see a bunch of "if version < 1.1.0 and the value of this property is this, then relay this special message" logic in the code either.

Anyway, I realize this is an incredibly annoying issue, and if you two disagree with my objections, we can just roll the dice and go with it.

**Comment by tarheel** [comment]
I respectfully disagree. I think the purpose of #322 is to eliminate cases in which the field isn't supplied in the config at all, and it accomplishes that. When the field is supplied but it's set to null, that's reasonable as long as the null value is communicating something specific. For these fields, it is: setting a maxSomething field to null is clearly saying that there should be no maximum, and it seems highly improbable that that would change.

**Comment by HEdingfield** [comment]
Ok, so here it seems like you're arguing that "if not supplied" strictly means when a config file doesn't contain the field at all. So if the field is in there but has a null value it's technically "supplied".

The problem is that the "if not supplied" behavior described in the .txt for the two fields I called out also triggers when the key is supplied but the value is null. Do you see the confusion? Maybe we can mitigate it a bit by noting in the .txt that null means unlimited, rewording "if not supplied", or whatever.

I definitely still stand by explicit being better. I worked as a database manager for years, and null was always garbage because you could never distinguish between it meaning "none" or assuming  that someone forgot to set something. Much better to explicitly say "none" to remove ambiguity.

**Comment by HEdingfield** [comment]
The more I think about this, the more strongly I feel that stringifying every field in `RawContestConfig` (as @tarheel suggested) is the correct way forward here. It gives us maximum flexibility, removes any chance of ambiguity, and effectively future-proofs changes to the config file. I also think it's really critical we get this right before certification, so I'm willing to take on this issue since I'm done with all my essentials now.

I know @moldover objected to this a few comments above, but I'm not exactly clear on why. Thoughts?

**Comment by moldover** [comment]
The objection was based on the risk of a major change just before a major release, which is real.  But I agree it removes ambiguity between null vs. missing which is good.  And I like Louis' suggestion of keeping 'default' logic in RawContestConfig, and 'normalization' logic in ContestConfig so maybe with both we might be good?  Thinking out loud here...

Everything is a string in the config json.
On load, missing params are parsed into null by jackson.
RawContestConfig applies "default" logic to missing params, and always returns Strings, so that serialization works:
missing (null) text field (contestOffice) return ""
missing precinctId returns ""
missing decimalPlacesForVoteArithmetic returns "4"
missing maxSkippedRanksAllowed returns "0"

Config loading / saving code will use RawContestConfig api to populate text fields in the ui.

User can edit them there, for example clearing maxRankingsAllowed, which will save/load as "".  (I think the edit text hint should say 'leave blank for unlimited')

ContestConfig will apply normalization logic:
maxRankingsAllowed="1" returns 1
maxRankingsAllowed="" returns numDeclaredCandidates()

Tabulation code will use these apis, and should never have to do null checks.

Ok, what am I missing?

**Comment by tarheel** [comment]
> And I like Louis' suggestion of keeping 'default' logic in RawContestConfig

Oh, sorry, I actually wasn't proposing this. I think RawContestConfig should reflect exactly what's parsed from the saved file, and it should be an error if you try to validate a config file that's missing any of the fields. But you should be able to load and edit a config that's missing fields, since otherwise you'd never be able to use the UI to fix the problem.

If the GUI needs to transform a field in order to render it in a text box or something, that logic should live in GuiConfigController.

**Comment by HEdingfield** [comment]
@moldover yes, I think what you lay out definitely heads in the right direction. I'd add the further stipulation that we only allow "" for optional fields that are legit Strings. I think `maxSkippedRanks` validation should fail for values like "", "-1", "2.4", "fjgkhl", and suggest in the message a value of "unlimited", "1", "2", etc. Similarly `maxRankingsAllowed` validation would fail with "", etc., and suggest "numCandidates", "1", "2", etc. This will truly future-proof it, because we'll obviously know to never modify code that checks for specific strings like that (and indeed, we'd have regression tests fail if so).

@tarheel I agree with you, I really like the idea of the `RawContestConfig` being exactly what's in the .json files, which is another point in the favor of using Strings for everything since it's the only field where we can guarantee that. The "default" logic should only exist as suggested values in the GUI as we worked out previously, and validation should just fail for values that aren't provided.

`ContestConfig` would handle all the casting to the "proper" type.

The other thing I'm a little wary of and will want to keep an eye on is how this will all play out with the CLI. I think it'll be ok, but just throwing that out there.

I definitely agree that this is a scary, big change, especially before a release. But, like I said before, I think it's more critical than anything else we do before certification, because we really don't want to be changing the config paradigm in a big way like this afterwards.

Do we want to abandon #322 for now while I dive into this today? Or finish merging it in before I make a pass at this?

**Comment by moldover** [comment]
Slacked with @HEdingfield and decided to 
- abandon #322.  Easier to start from scratch.  
- go ahead with stringifying everything and implementing proposals in the previous comment

**Comment by moldover** [comment]
@HEdingfield one tweak: @tarheel realized we can remove the special logic for getMaxRankingsAllowed and just have it be a "normal" int, required, 1..1000.  The gui can still suggest number of declared candidates.  I'm also ok with no suggestion, and forcing the user to make a decision here.  I'd lean toward the latter also cause it's simpler in code.

**Comment by HEdingfield** [comment]
I went ahead and got this working in my `string-config` branch with "max" for the total number of declared candidates. It works nicely.

**Comment by HEdingfield** [comment]
This is in a good place after #359. I converted everything but the booleans to Strings. Created issue #360 to maybe change the booleans over to Strings too some day, though the benefits seem negligible.
