### ISSUE TITLE
handle residual surplus

### ISSUE THREAD

**Issue by tarheel** [BrightSpots/rcv#215]
Once #214 is in, we'll have the possibility of "residual surplus": because we round down fractional vote transfers, we may end up subtracting slightly less than the full surplus from a winning candidate. For now we just leave that extra bit in the candidate's vote total, but @gngilbert has suggested that we could remove it and transfer it to a separate "residual surplus" tally.

**Comment by tarheel** [comment]
Questions:
- What should we show in the CSV? Should there be a separate row for residual surplus, perhaps just above or below the exhausted row?
- What should we show in the summary JSON and the visualizer? Hard to imagine that it would be useful to show this in the visualizer unless we can do it a really unobtrusive way.

**Comment by gngilbert** [comment]
@tarheel  
Lets include the residual surplus in the csv file.  I would put it on a line below "exhausted ballots" and change "exhausted" to "Inactive."

Definitely do not want to include it in the visualizer.  If leaving it out of the .json summary file is the easiest way to do that, that will be fine.

**Comment by gngilbert** [comment]
Is it a problem that residual surplus applies only to multi-winner contests! @tarheel

**Comment by tarheel** [comment]
> Is it a problem that residual surplus applies only to multi-winner contests

Um, I don't think so. What exactly is your concern? We just wouldn't show it at all for single-seat contests.

**Comment by gngilbert** [comment]
Not a problem.  Just don't want that line to appear in a single-winner contest .csv

**Comment by gngilbert** [comment]
Any way we can get this completed by early in the week?  We are getting down to our deadline with the Voting Methods Working Group and the VVSG development process.

**Comment by tarheel** [comment]
I'll do my best!

**Comment by gngilbert** [comment]
Thanks.

George Gilbert
RCV Resource Center
george.gilbert@rankedchoicevoting.org
336-906-0047

**Comment by tarheel** [comment]
OK, I've uploaded a new JAR here: https://drive.google.com/drive/folders/1uwn6UrHPSsbIGj3XiWErSwg-ysag5TEm

Please test it and let me know if it meets your expectations.

**Comment by gngilbert** [comment]
You do good work, sir!

[2019-02-24_18-55-33_summary.xlsx](https://github.com/BrightSpots/rcv/files/2898591/2019-02-24_18-55-33_summary.xlsx)
