### ISSUE TITLE
GUI adds fullFilePath to config

### ISSUE THREAD

**Issue by tarheel** [BrightSpots/rcv#217]
@moldover: this looks like an unintended consequence of your recent changes. If you save a config using the GUI, it adds both `filePath` and `fullFilePath` to each entry within `cvrFileSources`.

**Comment by moldover** [comment]
good catch.  seems like the objectWriter now calls every "getter" including getFullFilePath.  Changing the name to something else fixes it.  Will see if there's some other solution.

**Comment by moldover** [comment]
Fixed.
