### ISSUE TITLE
Replace deprecated XMLReaderFactory.createXMLReader()

### ISSUE THREAD

**Issue by HEdingfield** [BrightSpots/rcv#222]
According to [this](https://stackoverflow.com/questions/51072419/how-use-xmlreaderfactory-now-because-this-is-deprecated), it should be relatively straightforward to replace this line:

`XMLReader xmlReader = XMLReaderFactory.createXMLReader();`

with this one:

`XMLReader xmlReader = SAXParserFactory.newInstance().newSAXParser().getXMLReader();`

However, the `parseCVRFile` function returns an empty `cvrList` if this is done. I tried playing with it for long time but couldn't figure it out...

**Comment by aaime** [comment]
Trying to find a solution to this problem I stumbled into this ticket.
In the end, at least for me, the issue was that the sax parser factory had to be made namspace aware:

```
            SAXParserFactory parserFactory = SAXParserFactory.newInstance();
            parserFactory.setNamespaceAware(true);
            SAXParser parser = parserFactory.newSAXParser();
            XMLReader xmlReader = parser.getXMLReader();
```

Hope this helps.

**Comment by HEdingfield** [comment]
@aaime Yes, that worked perfectly, thanks so much!
