### ISSUE TITLE
Get rid of checkBoxCandidateExcluded

### ISSUE THREAD

**Issue by HEdingfield** [BrightSpots/rcv#225]
Get rid of checkBoxCandidateExcluded in the "add" section at the top of the Candidates table now that it's easy to toggle this in the list itself. Does this sound ok with you guys, @tarheel @CalebKleppner ?

**Comment by CalebKleppner** [comment]
Yes, a good idea, makes entering candidates easier and better to check 
and uncheck the exclude button in the list.

Thanks,

Caleb Kleppner
MK Election Services, LLC
203-376-4080

**Comment by tarheel** [comment]
Sure.
