### ISSUE TITLE
support sequential multi-seat tabulation

### ISSUE THREAD

**Issue by tarheel** [BrightSpots/rcv#229]
A.k.a. "winner-take-all," per Caleb.

**Comment by moldover** [comment]
https://www.youtube.com/watch?v=92cwKCU8Z5c

**Comment by tarheel** [comment]
@gngilbert @CalebKleppner I just posted an updated JAR that includes this config option. Please give it a try and let me know if it works as expected.

**Comment by gngilbert** [comment]
Worked fine.  The remaining question is, is there a way to display the
results in a single visualizer for public display?

George Gilbert
RCV Resource Center
george.gilbert@rankedchoicevoting.org
336-906-0047

**Comment by tarheel** [comment]
My suggestion is that we keep the tabulator output the way it is now, and add an option to the visualizer to handle multiple JSON files. @moldover @HEdingfield thoughts? We should also talk to Armin about this.
