### ISSUE TITLE
Dealing with residual surplus

### ISSUE THREAD

**Issue by CalebKleppner** [BrightSpots/rcv#235]
Introducing the idea of the residual surplus:  when a candidate gets elected and surplus transferred, but candidate ends up (due to rounding) with a vote total greater than the threshold.  At that point, we want to shave off the residual surplus from that candidate’s total and keeping a running total of all residual surplus.  This means we need to add one more bucket for votes:  residual surplus.  It should be listed below exhausted ballots in the .csv summary and ignored in the .json summary.

The net result is that all candidates elected end up with the threshold, and in the last line of the summary, we get a running total of all residual surplus that was removed from candidates.  Check out the attached pdf, which shows the current and revised concept in summary file.

[Multi_winner summary with residual surplus.pdf](https://github.com/BrightSpots/rcv/files/2922492/Multi_winner.summary.with.residual.surplus.pdf)

**Comment by tarheel** [comment]
@CalebKleppner: I did this recently in #228. The latest version of the JAR includes it: https://drive.google.com/drive/folders/1uwn6UrHPSsbIGj3XiWErSwg-ysag5TEm

**Comment by tarheel** [comment]
(please reopen if the way I implemented it doesn't match your expectations)

**Comment by moldover** [comment]
@tarheel should we include residual in summary json to ensure it is stable?

**Comment by tarheel** [comment]
Yeah, that would be the prudent thing to do. (And then we can tell Armin to filter it out of the visualizer.) I'll open a separate issue.
