### ISSUE TITLE
Revisions to .csv summary file

### ISSUE THREAD

**Issue by CalebKleppner** [BrightSpots/rcv#236]
Quick notes here, with more to follow, but here are two quick and easy changes (I hope) for our .csv summary file (not important for .json).

1.	List all winners above threshold (new row in report)
2.	Change the term “Exhausted ballots” to “Inactive ballots”

[Issue -- summary format changes.pdf](https://github.com/BrightSpots/rcv/files/2922494/Issue.--.summary.format.changes.pdf)

**Comment by tarheel** [comment]
I already changed "Exhausted" to "Inactive" in #228.

I can add the row listing the winners.

To minimize confusion, please open a new issue for any further changes you'd like to request.

**Comment by gngilbert** [comment]
Would like to have the "winner" row added for certified version

**Comment by freedomcounts** [comment]
Agree that we need the "winner" for certification.

**Comment by HEdingfield** [comment]
Fixed with #307.
