### ISSUE TITLE
bottoms-up primary variant [nsfw]

### ISSUE THREAD

**Issue by tarheel** [BrightSpots/rcv#240]
May be used for primaries in Utah. Allow the operator to specify the number of "winners" (e.g. 2X the number of seats they're actually trying to fill) then run a single-seat contest with no winning threshold until you have exactly the right number of continuing candidates, at which point you stop.

Open questions:
- Should we forbid batch elimination in this mode? Or should we allow it, but make it smart enough so that it doesn't mistakenly eliminate too many candidates?
- How should the operator specify that they want to run in this mode? Initial proposal: they set numWinners to the number of "winners," and there's a new checkbox labeled "bottoms-up mode" (or whatever) that can only be enabled when numWinners > 1.

**Comment by gngilbert** [comment]
I would not allow batch elimination.  That seems the easiest way to handle it.

Regarding your suggestions on implementation , I want to ask Chris to comment on the "bottoms-up mode" label.  There is a variety of RCV called "bottoms up" and we need to be sure we are not misapplying a label.  Can you add Chris to this discussion and ask for his input on this?  I did not see him on the list of those with access.

Normally when we specify numWinners>1 the tabulator enters multi-winner tabulation mode with the exception of selecting "Sequential Multi-seat."  How about modifying the code associated with "Continue until two candidates remain" such that the user may enter a number or select "2X Number of seats"  and relabel "Continue until N candidates remain?"  

Of course, I can already identify at least one problem with this.  Not all CVR's, at least at present, include the number of seats being filled.  I don't believe the current ES&S CVR includes this. This might be solved by an instruction that the "Number of winners" field should specify the number of seats to be filled if "2X Number of seats" rule is being used.  This might also be getting too complex.

Your original suggest might be the simplest if we can come up with a good "or whatever" label for it.

**Comment by tarheel** [comment]
This repository is publicly accessible, so I can just send Chris the link to this issue.

Hmm. Letting the operator choose "2X the number of seats" and then specify the number of seats elsewhere feels unnecessarily roundabout.

I guess if we wanted the config to be as explicit as possible for this case, we would have them set numWinners = 0 and then change the "continue until n candidates remain" field to an integer (as you suggested) and just let them enter the desired number. What do you think of that?

Open to suggestions from @moldover and @HEdingfield also.

**Comment by gngilbert** [comment]
Agree with your "too roundabout" assessment.  BTW, I sent Chris the link just in case it was open so, if you have not done so, there is no need.  Thanks.

**Comment by chughes297** [comment]
This method is what we've called bottoms up - when you have multiple winners but only eliminate candidates until you have as many candidates as winners/do no surplus transfer/have no operative threshold. The label is apt here.

Louis's suggestion of having checkboxes to opt out of STV and in to sequential or bottoms-up seems like a good solution to me.

**Comment by gngilbert** [comment]
Great! Let's go with it.

**Comment by tarheel** [comment]
OK, so I'm going to add a checkbox for bottoms-up. If the operator wants to use this mode, they'll enable the checkbox and set numWinners to the desired number of candidates who should remain when the tabulation terminates.

I'm also thinking -- now that we have a few mutually exclusive variants like this, I wonder if we should combine them into a pulldown. Something like "special winner determination variant," where the options would be:
None
Continue until two candidates remain
Sequential multi-seat
Bottoms-up

New issue for that: https://github.com/BrightSpots/rcv/issues/241

**Comment by tarheel** [comment]
@gngilbert: I've uploaded a new JAR that includes the bottoms-up option. Please test it out.

https://drive.google.com/drive/folders/1uwn6UrHPSsbIGj3XiWErSwg-ysag5TEm
