### ISSUE TITLE
Support NIST CDF input format

### ISSUE THREAD

**Issue by moldover** [BrightSpots/rcv#242]
CDF format includes not just votes (like ES&S files) but also the election data: candidates and contests.  Reading CDF format will involve first reading the election data to build the list of candidates / contests.  Then read the ballots, and match up ballot selections with candidates / contests.  Example file is attached.  A config file will of course be needed to specify all the other tabulator options.

I can imagine one solution which adds a flag to the config file to indicate that candidate info will be parsed from the CVR file at runtime.  Then the tabulator will open input CDF file and extract the candidate data and use it to populate the RawContestConfig candidates list.  Then a tabulation is performed.  

[Multi-winner_NIST_CVR_3.txt](https://github.com/BrightSpots/rcv/files/3025788/Multi-winner_NIST_CVR_3.txt)

**Comment by tarheel** [comment]
I agree that the latter would be cleaner.

**Comment by moldover** [comment]
@tarheel does it make sense to split this into the following?  If so, wanna pick one?  
1) parsing election data from CDF and populating rawConfig
2) parsing vote data into CastVoteRecord objects

**Comment by tarheel** [comment]
There's some overlap for reading in the file, yeah? Would it be easiest to do these two sequentially? Anyway, I probably can't make progress until Tuesday or Wednesday, so you can decide how to start.

**Comment by moldover** [comment]
Yeah maybe a bit over overlap.  Tell ya what, I've already made some progress on 2, so how about I wrap that up and push it tonight (Tuesday) and you can take over.  At that point I'll switch to working on the output, unless Hylton or Hemal are interested in doing that.
