### ISSUE TITLE
Support NIST CDF tabulation output

### ISSUE THREAD

**Issue by moldover** [BrightSpots/rcv#243]
The CDF format can indicate the results of a tabulation.  We need to support this to be a reference application.  For each round, we output the status of every ballot: who it counts for, and how much.  In the CDF json file, this is stored as a CVRSnapshot: a "snapshot" in time of CVR state, which changes during tabulation.  

Note: a CVRSnapshot is added to every CVR in the file, for every round, even if a particular CVR doesn't change state in a given round.  Yes, this means a LOT of duplication but we're not going to worry about that for now.  There is no live use-case yet, let alone anyone to asking for smaller file sizes.  This may be addressed when the standard itself is updated.

JSON details:

The structure of the CDF output is based directly on the input sample file attached here.  I am still working on creating a sample output file and will attach or commit it once it is ready.
[Multi-winner_NIST_CVR_INPUT.txt](https://github.com/BrightSpots/rcv/files/3026731/Multi-winner_NIST_CVR_INPUT.txt)

As mentioned, each CVRSnapshot represents the state of a particular CVR in a particular round.  The order of the snapshots implies the order of rounds.

Within the CVRSnapshot is a list of CVRContestSelections, one for each ranking a voter selected.  Each CVRContestSelection has a SelectionPosition object which contains the critical fields:
  **Rank: [positive integer rank]**  What is the ranking for this position (won't change)
  **NumberVotes: [non-negative number]** What is the vote value for this selection (could become fractional in multi-seat fractional transfer scenarios)
**IsAllocable: ["yes" | "no" | "unknown"]** Does this selection count in this round?  This will change when a vote is initially counted for a candidate or transfers.  When a vote is exhausted, ALL SelectionPosition objects will have IsAllocable:"no"

**Comment by tarheel** [comment]
When do you set isAllocable to unknown?

**Comment by moldover** [comment]
unknown is used by a ballot marking/creation device (e.g. at a polling place) when the ballot is first created, before any election rules are applied (e.g. no overvote determination has been applied).  Some other device (e.g. tabulator) or person (adjudicator) needs to apply specific election rules and determine how this cvr will actually be counted over the course of an election.

**Comment by tarheel** [comment]
So am I understanding this correctly? In the output, for each round we'll have a full copy of the CVR snapshot for each ballot, where the only difference from round to round is that IsAllocable and NumberVotes may change?

A couple more thoughts:
- As you mentioned, the amount of duplication here is just massive.
- The nature of this output requires that we add the round-by-round tracking back to the CastVoteRecord class. (I removed it a while ago to reduce the app's memory footprint.)

I definitely recommend we add a config option to enable/disable this form of output so that it doesn't bog down normal operation.

Also, if you're OK with it, I suggest that you own the input part and let me take this issue.

**Comment by moldover** [comment]
Oh, just seeing this now.  Yeah sure that's probably easier... you take output, I'll take input.  And yes, that is my understanding from talking to everyone at the working group meeting, very specifically about exactly this.

**Comment by tarheel** [comment]
Cool. Are you still working on a sample output file? I think I understand most of it from what you've already written, but I don't know the details on how to group the rounds etc.

And we need this by Friday?

**Comment by moldover** [comment]
Haven't gotten to the sample output file yet, still working on input.  If that's not blocking you, great.  As for round grouping: snapshots are stored in an array.  The order of the snapshots IS the order of the rounds.

**Comment by moldover** [comment]
Oh, and as for due date, @gngilbert said "end of this week", so that sounds like Friday.  Probably some wiggle room if we need it.

**Comment by tarheel** [comment]
I'm looking at your sample input: https://jsoneditoronline.org/?id=5d86609ee5bf408488bded5e3f0bded7

So I should output one huge array of snapshots? In the input, each element of that array has the following fields:
BallotPrePrintedId
CurrentSnapshotId
CVRSnapshot
ElectionId
@type

I think I understand how to populate BallotPrePrintedId, CVRSnapshot, ElectionId, and @type. Are you saying that I should indicate the round number using the CurrentSnapshotId?

A really simple sample output would be very helpful.

**Comment by moldover** [comment]
Sure.  Here's an example file with a single cvr showing two rounds of tabulation.  In practice you will need to replicate the structure here for every cvr, for all rounds of full tabulation.  

You will notice, each cvr has (among other things) an array of snapshots.  In the sample INPUT file, there is only one element in this array: the original snapshot.  For each cvr, your output code will append snapshots to this array, one for each round of tabulation.  Thus the order of the snapshots in each cvr's snapshot array implies the order of rounds.  In this example I've named them "ballot-1-round1" "ballot-1-round2"  but it is the order which indicates the sequence of tabulation.   


[CVR_example_output.txt](https://github.com/BrightSpots/rcv/files/3038893/CVR_example_output.txt)
 rounds.

**Comment by moldover** [comment]
As for CurrentSnapshotID that indicates the most recent snapshot.  In your case it should point to the final round snapshot.

**Comment by tarheel** [comment]
OK, I took your example and duplicated the single ballot to produce an example with two ballots. Does this look right to you?

https://jsoneditoronline.org/?id=ed7f9c4b20684019ba17c3514d7e8f4e

**Comment by moldover** [comment]
Yes!  Note, the "type" of the new snapshots you add should be "interpreted" (the input ones are "original").  I did that in the sample, and you have copied it over, so it is correct.

**Comment by tarheel** [comment]
In your example, NumberVotes is always 1. How exactly does it work when we do a fractional transfer? Let's say my ballot has 1 = A, 2 = B, 3 = C. At some point A wins and we transfer .25, so now NumberVotes = .75 for A and .25 for B. But what should I set NumberVotes to for the C selection? Does it even make sense to include NumberVotes when IsAllocable is false or unknown?

**Comment by moldover** [comment]
> But what should I set NumberVotes to for the C selection?

I can't say authoritatively.  If it wasn't extra work, I would probably leave it at 1. 

> Does it even make sense to include NumberVotes when IsAllocable is false or unknown?

Again, I can't say authoritatively.  If it isn't extra work I would leave it in.

In general my sense is NIST is not going to be rigorous with how we implement this.  For now we should make a reasonable effort but not sweat smaller things.

**Comment by tarheel** [comment]
Don't sweat the petty things and don't pet the sweaty things.

**Comment by gngilbert** [comment]
I brought this up yesterday during the voting methods working group
meeting.  Turns out that John Dzuirlaj was not aware of the existance of
fractional votes.  He is working on an answer.

George Gilbert
RCV Resource Center
george.gilbert@rankedchoicevoting.org
336-906-0047
