### ISSUE TITLE
Add unit tests for NIST RCV tabulation

### ISSUE THREAD

**Issue by moldover** [BrightSpots/rcv#244]
@gngilbert has already tested these successfully.  Adding them as unit tests involves add the source files (cvr and config) into the test resources area, and then creating unit tests which run them automatically.

**Comment by tarheel** [comment]
@HEdingfield did you want to grab this? I can do it soon if you won't have time for it.

**Comment by tarheel** [comment]
All of the files are attached to an email from George on 4/1 in the thread "NIST Common Data Format Project."

**Comment by HEdingfield** [comment]
Slammed for the next week catching up with budget stuff and doing taxes, but if this is still kicking around in a couple weeks I can.

**Comment by tarheel** [comment]
I'll update all of the test sets to check the CDF output also once that logic has stabilized a bit more. Right now we're still getting feedback from John et al on things we need to change.

**Comment by moldover** [comment]
@tarheel working on this today, good progress, (basically adding precinct ids, which is what GpUnit is for) but hit a snag: there's some error when running 2017 Minneapolis Mayor Precinct when enabling CDF output.  Seems like some CVRs never get recordSelectionForCastVoteRecord called on them, hence they never get logCdfSnapshotData called, hence ResultsWriter has a failed assertion when it can't find any cdf data at all.  I'm working around it for now, will circle back if you don't figure it out before I do.  Maybe they are just exhausted in the first round?

**Comment by tarheel** [comment]
Hmm, interesting. Yes, I'll debug.
