### ISSUE TITLE
consistent casing for initialisms

### ISSUE THREAD

**Issue by tarheel** [BrightSpots/rcv#248]
We've been inconsistent about this, e.g. `fullCVRData` vs. `textFieldCvrFilePath` or `setIdColumnIndex` vs. `rankToCandidateIDs`. Let's pick an approach and stick with it.

**Comment by tarheel** [comment]
I vaguely recall that @HEdingfield had an opinion on this topic...

**Comment by HEdingfield** [comment]
Yeah, I definitely prefer `fullCvrData`, `rankToCandidateIds`, etc. This is recommended in Effective Java. Here's [a good example](https://stackoverflow.com/questions/1176950/acronyms-in-camel-back) of why to do it that way.

**Comment by tarheel** [comment]
Works for me. Heads up to @moldover. I can send a PR later that cleans up all the existing cases, but let's follow @HEdingfield's suggestion for all new code.

**Comment by gngilbert** [comment]
Again, I don't understand the issue but if it involves inconsistencies in our code, we probably need to address it now.

**Comment by freedomcounts** [comment]
Cleanup for certification.

**Comment by HEdingfield** [comment]
Closed via #380 and #381.
