### ISSUE TITLE
Update copyright dates throughout code and docs - see if there's an intelliJ macro which updates automagically

### ISSUE THREAD

**Issue by HEdingfield** [BrightSpots/rcv#269]
Should probably put a range, like 2017-2019.

**Comment by moldover** [comment]
Yeah good call.  Also, having read my name in the header so many times it feels a bit awkward.  How would you guys feel about changing it to say something like "Copyright (c)  2017-2019 Bright Spots Developers" which could be inclusive of other future contributors?

**Comment by moldover** [comment]
And maybe add an "acknowledgements" section to the documentation somewhere which does call out contributors by name, cause that is important :)

**Comment by tarheel** [comment]
Sure.

**Comment by gngilbert** [comment]
Wouldn't call this a certification requirement but I think it would be best if done before then.

**Comment by freedomcounts** [comment]
It would be nice to be included in certification.

**Comment by HEdingfield** [comment]
Should probably switch to using IntelliJ's built-in tag for this, e.g. `2017-${today.year}`:
https://stackoverflow.com/questions/48173062/intellij-update-copyright-year
