### ISSUE TITLE
Update to Java 12 and fix link in README to Oracle Java SE

### ISSUE THREAD

**Issue by HEdingfield** [BrightSpots/rcv#270]
We should be linking to and using OpenJDK, per [this article](https://medium.com/@javachampions/java-is-still-free-2-0-0-6b9aa8d6d244).

#239 is likely a blocker for this.

The most straightforward thing to link and use would probably be Oracle's [open source builds of the JDK here](https://jdk.java.net/).

**Comment by HEdingfield** [comment]
Counterpoint: we may want to stick with Java 11, since it's LTS until 2022 per [the table here](https://en.wikipedia.org/wiki/Java_version_history). In either case, we're still updating to a new version of Java.

**Comment by tarheel** [comment]
Any particular downside to going straight to 12?

**Comment by HEdingfield** [comment]
See my previous comment. Means we'd need to stay on top of new versions every 6 months, whereas 11 is LTS until 2022. It's probably still worth going to 12 and beyond, but we need to have a discussion about the certification process, who's responsible for building the code, if we need to stick with images frozen in time, etc.

**Comment by HEdingfield** [comment]
Addressed via #272. Now the tabulator _only_ works in JDK 11+. When distributed using Gradle's `distZip` task, it requires that the user have the JDK installed. When distributed using Gradle's `jlink` task, it doesn't even require that the user have the JDK installed (the zip is 48 MB vs. 26 MB with `distZip`).
