### ISSUE TITLE
Add recommendations to some error messages

### ISSUE THREAD

**Issue by HEdingfield** [BrightSpots/rcv#271]
E.g. "Failed to start system logging!" error message should include recommendation(s) on how to fix, e.g.  "check to make sure you have write access in the current working directory".

Audit existing error messages and see if any others could benefit from this.

Loosely related to #141 and #267.

**Comment by gngilbert** [comment]
This sounds like one we need to do.

**Comment by HEdingfield** [comment]
Tagging as essential, but may just make a narrow-scoped first pass on it, and do a broader, more descriptive pass after certification.

**Comment by moldover** [comment]
Fixed with #287
