### ISSUE TITLE
Update rankedchoicevoting.org page and find better hosting spot

### ISSUE THREAD

**Issue by HEdingfield** [BrightSpots/rcv#273]
[This page](https://www.rankedchoicevoting.org/universal_rcv_tabulator) has outdated instructions and also links to my personal Google Drive account, which I'd prefer to avoid.

**Comment by HEdingfield** [comment]
Detailed discussion on this in email thread with subject "Presentation follow-up" started on 2018-04-24.

**Comment by chughes297** [comment]
I can copy the compiled version over to RCVRC's google drive folder, if that's helpful. The Dropbox links I had been using stopped working properly, sorry for not reporting that back when it happened.

What instructions need updating? The one about which version of JDK to use?

**Comment by HEdingfield** [comment]
This is a bit of a blocker on #58 and #86.

@chughes297 could you please create a folder on the RCVRC Drive and give me, @tarheel, and @moldover write access to it? I'll take care of uploading the compiled bins over there, and I'll update the instructions accordingly.

**Comment by chughes297** [comment]
Replied to your email but thought I should reply here too: 

Thanks, just made the folder and gave you, Louis, and Jon edit permissions. I uploaded the most recent compiled version of the software that I have (20190426) to the folder, too. https://drive.google.com/drive/u/1/folders/1vYYJa5-oJe0lpaVnI_ELn9foZIVZ54pL

**Comment by chughes297** [comment]
[Page](https://www.rankedchoicevoting.org/universal_rcv_tabulator) has been updated

**Comment by chughes297** [comment]
Is there anything else I need to do to help resolve this issue?

**Comment by HEdingfield** [comment]
@chughes297 I recently submitted PR #315, which moves all the download and installation instructions to the README, which is displayed prominently on the front page of the GitHub. We'll merge this into the master and it'll be live within the next week, so if you want to go ahead and update [the page](https://www.rankedchoicevoting.org/universal_rcv_tabulator) now, that'd be cool.

Basically, you just need to change the second paragraph to something like this:

> Instructions on how to download, install, and use the tabulator are available on the project's [GitHub page](https://github.com/BrightSpots/rcv/).

You also might want to get rid of the "features to be added" thing at the bottom and rely on our README to convey that information since it's going to be a pain to keep multiple lists like this up-to-date at the same time. If you think it's important to convey the bit about only supporting ES&S voting system vendor data currently, I can add it to the README, just let me know.

**Comment by chughes297** [comment]
Just updated the page.

**Comment by HEdingfield** [comment]
Nice, thanks! Closing this issue; feel free to re-open if you want us to add the "features to be added" info or at least a note that only ES&S and CDF are supported currently.
