### ISSUE TITLE
raise fatal error if CVR contains vote for unrecognized candidate

### ISSUE THREAD

**Issue by tarheel** [BrightSpots/rcv#277]

**Comment by gngilbert** [comment]
Retrieving candidate names from the CVR, as we do with the CDF CVR, would alleviate this problem. Not sure we can get that done for this cert. round.  

I we cannot accomplish that now, it would be good to have an error message identify the unrecognized candidate name(s) so it(they) could be copied and pasted into the candidate names list easily.

**Comment by HEdingfield** [comment]
FTR, retrieving candidates names from the CVR is outlined in issue #60.

**Comment by tarheel** [comment]
We're actually already doing this for XLSX CVR sources. Perhaps we'll add it for CDF sources in the future, but I'm not going to worry about that now.

**Comment by HEdingfield** [comment]
Want to file a new issues for CDF and tag it with the Future milestone, or just convert this one over to that?

**Comment by tarheel** [comment]
#309
