### ISSUE TITLE
CLI bug with paths in current directory in config

### ISSUE THREAD

**Issue by tarheel** [BrightSpots/rcv#278]
If you run from the command line and specify a config file with no path (i.e. in the current dir), and that config files also lists a CVR source with no path, we end using the string "null" as the directory.

**Comment by HEdingfield** [comment]
Confirmed and noted this in #272: 

> I also discovered a minor weird CLI bug when running with Gradle rcv.bat (and possibly otherwise, and possibly only in Windows): directories specified for CVRs (and output) inject \null\ before... workaround requires using a path like "..\\2013_minneapolis_mayor_cvr.xlsx" instead of "2013_minneapolis_mayor_cvr.xlsx"

**Comment by moldover** [comment]
Fixed with #287
