### ISSUE TITLE
Decide if Gradle distribution should include test files and docs

### ISSUE THREAD

**Issue by HEdingfield** [BrightSpots/rcv#281]
Currently using `distZip` and `jlink` to create distributions doesn't include any of the test configs / CVRs or docs, which we may want to include somehow in the distribution. Do we want to include these and, if so, which specifically?

Some info on adding static files here:
https://docs.gradle.org/4.10.3/userguide/application_plugin.html#sec:the_distribution

**Comment by tarheel** [comment]
Yes, but let's limit it to the smaller tests, maybe?

**Comment by HEdingfield** [comment]
Makes sense to me. Maybe we only need to include a couple of them? Enough to get coverage of most of the tabulator's functionality? I'll rely on you and/or George to make the call on which to include. Just list them here, along with the docs that should be included (guessing README and UserGuide at least).

**Comment by freedomcounts** [comment]
I agree - README, UserGuide, and to be determined test configs & CVR's.

**Comment by HEdingfield** [comment]
#78 is a partial blocker.

**Comment by HEdingfield** [comment]
I've made progress including files with the `distZip` method, but we're probably going to want to rely on `jlink` instead, and I haven't had any luck so far figuring out how to include files in the `jlink` image. Filed a question on SO [here](https://stackoverflow.com/questions/56778477/how-to-bundle-extra-files-with-jlink-image).

**Comment by HEdingfield** [comment]
Closed with #316.
