### ISSUE TITLE
add option for batch winner election

### ISSUE THREAD

**Issue by tarheel** [BrightSpots/rcv#288]
The current behavior in the code is to elect all candidates exceeding the winning threshold simultaneously (i.e. in a single round). However, some jurisdictions (e.g. Eastpointe) have rules stating the only the candidate with the highest total should be elected in a given round. We need a boolean config param for this.

I figure we should call this "batch winner election" or something, because it's the counterpart to batch elimination. But let me know if you have a better suggestion for the name.

**Comment by HEdingfield** [comment]
Sounds good! Just remember to keep the default behavior state to have a false boolean, i.e. the option to turn it on would be something like "disable batch processing of winners".

**Comment by tarheel** [comment]
Not actually sure which way should be the default here. I'll defer to @chughes297 and @gngilbert.

**Comment by gngilbert** [comment]
Let's default to the "batch" process we currently have and add the "elect one winner per round" as an option.

**Comment by tarheel** [comment]
I just realized there's an edge case for which the correct/desired behavior isn't obvious. Clearly the winner that we select when this option is enabled should be the candidate who has the highest vote total. But what if two or more candidates are tied with the highest total? Do we need tiebreaker logic here? The stakes are lower than in an elimination tiebreak, since in this case they're all going to win anyway... but I need to make the behavior deterministic somehow, even if it's just "pick randomly based on the random seed supplied to the application." (See #170.)

**Comment by chughes297** [comment]
Yes, the same tie-breaker procedure would apply (unless the law as written requires a different procedure for electing tied candidates than the one used for eliminating candidates, in which case I'd suggest handling all ties outside of the system/having tabulation pause at all ties for manual entry of the winner/loser of that tie-breaker).

**Comment by tarheel** [comment]
OK, thanks. I'll just hook into our existing tie-breaking logic for now.

**Comment by tarheel** [comment]
Closed with #311.
