### ISSUE TITLE
Sequential IRV tabulation only produces precinct-level results for the final instance of IRV 

### ISSUE THREAD

**Issue by chughes297** [BrightSpots/rcv#291]
When running a sequential IRV election (as will be used in Utah this fall), precinct-level reports are only produced for the tabulation of the final seat being filled. Need to produce precinct reports for each seat being filled. 

(same example file as in Issue #290)
[2019-06-18_14-36-55_MINNEAPOLIS_W-2_P-05_precinct_summary.xlsx](https://github.com/BrightSpots/rcv/files/3303329/2019-06-18_14-36-55_MINNEAPOLIS_W-2_P-05_precinct_summary.xlsx)

[2017-park-district-1-cvr.xlsx](https://github.com/BrightSpots/rcv/files/3303347/2017-park-district-1-cvr.xlsx)

[Utah Test 2.json.zip](https://github.com/BrightSpots/rcv/files/3303378/Utah.Test.2.json.zip)

**Comment by tarheel** [comment]
Oops. Yeah, need to fix this. Is there a specific deadline? Can I revisit it after we finish the work for the Eastpointe deadline?

**Comment by freedomcounts** [comment]
Utah requires EAC Certification for all voting systems.  Based on that requirement we need to make this a certification-deliverable-essential,  Deadline to complete and fully test is June 30, 2019.

**Comment by HEdingfield** [comment]
I believe this was fixed with #300.
