### ISSUE TITLE
Interactive tiebreaker bug with sequential multi-seat tabulation

### ISSUE THREAD

**Issue by HEdingfield** [BrightSpots/rcv#317]
I found a bug with the interactive tiebreaker sequential multi-seat example using the files I included in PR #316.

Load: `rcv\src\test\resources\network\brightspots\rcv\test_data\sample_interactive_tiebreak\sample_interactive_tiebreak_sequential_config.json`

Tabulate, eliminate Yinka Dare; then the entire thing runs a second time for some reason. If you choose Yinka Dare again, it ends after the second time.

**Comment by moldover** [comment]
@HEdingfield this is expected for a sequential race. If you look closely at the output you'll see the first time through Mookie is elected to the first seat, and the second time through he is excluded, and Geroge is elected to the second seat.  I'll add some logging so this is clearer.

**Comment by HEdingfield** [comment]
#329 makes this much better, thanks.
