### ISSUE TITLE
"Successfully loaded contest config" appears right after you save a config

### ISSUE THREAD

**Issue by HEdingfield** [BrightSpots/rcv#321]
Minor issue: "Successfully loaded contest config" appears right after you save a config, e.g.

> 2019-06-29 00:12:59 PDT INFO: Saved object to: C:\blah\2018_maine_governor_primary_config.json
> 2019-06-29 00:12:59 PDT INFO: Successfully loaded contest config: C:\blah\2018_maine_governor_primary_config.json

We can probably set a `silentMode` boolean for `loadContestConfig` that suppresses this message in the save use case.

**Comment by tarheel** [comment]
Good catch. Not directly related, but it's also a little weird that we say "Saved object" instead of "Save config."

**Comment by HEdingfield** [comment]
Closed with #323
