### ISSUE TITLE
Validating overflowing integers provides confusing error message

### ISSUE THREAD

**Issue by HEdingfield** [BrightSpots/rcv#334]
Consider making text box integer inputs all "must be between %d and %d" validation messages, where the max is Integer.MAX_VALUE. Otherwise, if you set the value super high in the GUI and try to validate, you get the somewhat misleading messages like:

> Integer required! Illegal value "9999999999999999999999999999999999999999" found.

Or:

> maxSkippedRanksAllowed must either be "unlimited" or an integer!

Both of which may confuse the user who may not realize an integer has an upper bound.

**Comment by tarheel** [comment]
I agree with this proposal.

**Comment by HEdingfield** [comment]
Closed with #366.
