### ISSUE TITLE
Clean up VVSG 1.0 comments

### ISSUE THREAD

**Issue by HEdingfield** [BrightSpots/rcv#378]
Since we're certifying to VVSG 1.1 now, no more need for extraneous comments describing what variables do and inputs / outputs of functions. Woohoo! Obviously leave comments in if they add value, but let's purge the cruft otherwise.

**Comment by moldover** [comment]
Closed via https://github.com/BrightSpots/rcv/commit/572cfb02f87087b57e7f72124379fc60fb9602f0
