### ISSUE TITLE
support Clear Ballot format

### ISSUE THREAD

**Issue by tarheel** [BrightSpots/rcv#400]
[Clear_Ballot_BEN_QA_Gen_Res_WITTesting1.cvr.zip](https://github.com/BrightSpots/rcv/files/3909283/Clear_Ballot_BEN_QA_Gen_Res_WITTesting1.cvr.zip)

Louis's notes from the sample:
- Uses a separate CSV file for each different entity type (contests, parties, choices, precincts, and CVRs).
- Is this an example of an RCV contest? I can't find any rankings, so I'm not sure I understand how we would parse this.

**Comment by tarheel** [comment]
More questions from @moldover:

How are entity files named?
Will we need to add config parameteres to specify these files?

Do we need to apply any logic to determine precincts, as multiple precinct Ids (from precincts.csv) seem to map to a single precinct:
 "Precinct 6 (Generic Use with CounterGroup EV) Ballot, Precinct 6 (Generic Use with CounterGroup EV) Standa

What do the different "choices" from choices.csv mean?

csv Column headers look like: "Choice_11_1:Contest 1 (Candidate):Vote For 1:Write-in:Non-Partisan"  How do these encode rankings?
The Choice id seems to be the in the first part.  
Do we need to apply logic to choice Ids?  To determine a ranking?  There are ALL KINDS of interesting choices one can reference.

Do we need to handle multiple contests?  How?
 - User specified contest ID?
 - Multiple contests from a single config?

**Comment by HEdingfield** [comment]
This is now implemented in the GUI. @moldover Any last things we need to address (e.g. from the above comments) or can we safely close this now?

**Comment by moldover** [comment]
closed via #475
