### ISSUE TITLE
support Hart format

### ISSUE THREAD

**Issue by tarheel** [BrightSpots/rcv#401]
[Hart CVR Folder.zip](https://github.com/BrightSpots/rcv/files/3909284/Hart.CVR.Folder.zip)

Louis's notes:
- Each CVR is in its own XML file.
- They seem to use a hacky approach in which each ranking is treated as its own contest. E.g. “Council Member Ward 1 1st choice” is a contest, and “Council Member Ward 1 2nd choice” is another contest. I guess we can parse it fine if they're consistent about that approach, but it feels kind of brittle.

**Comment by tarheel** [comment]
More questions from @moldover:

how are input CVR files named and specified in config?  

what are the subfolders used for?  "1st Choice" etc..?  Spot checking, the files seem to be identical.

**Comment by moldover** [comment]
closed via #458
