### ISSUE TITLE
support Unisyn format

### ISSUE THREAD

**Issue by tarheel** [BrightSpots/rcv#402]
[RCV_WriteIns_1_UNIOVS22585_cvr_1_of_1.zip](https://github.com/BrightSpots/rcv/files/3909287/RCV_WriteIns_1_UNIOVS22585_cvr_1_of_1.zip)

Louis's notes:
- Since it uses the CDF, it should be fairly easy for us to handle, I hope.
- The sample you shared is strange, though, as each ranking is represented as a separate CVR entity... which seems wrong. Based on all the work we did earlier with the CDF, I'm fairly confident that the proper way to represent multiple rankings is to have multiple CVRContestSelection entities (one per ranking) inside the CVRContest, which is inside CVRSnapshot, which is inside CVR.

**Comment by HEdingfield** [comment]
Unisyn output is supposedly equivalent to .xml CDF support, so we should be able to build that in and just expand the CDF provider in the GUI to be able to accept .xml files in addition to .json files.

**Comment by moldover** [comment]
This is ostensibly closed as we can now support reading and tabulating example CDF XML CVR reports from Unisyn.  Woof.
