### ISSUE TITLE
export Dominion CVR in generic CSV format

### ISSUE THREAD

**Issue by tarheel** [BrightSpots/rcv#404]
The tabulator needs functionality to export in-memory CastVoteRecords to a generic .csv file for human-friendly verification of the CSV import process with non-trivial processing (Dominion, ClearVote, ?) (#407).

@CalebKleppner and @moldover defined this spec around the 2020 Democratic Primaries in Kansas, Alaska, and Wyoming.

The tabulator exports a csv for each contest.
The export file location is the same folder as the input cvr json file.
  The export file name is:
CvrExport-[contestId].csv.  (if there is no contest ID just omit that portion).

For each contest, the exported .csv file is like this:
Header:
ContestId | TabulatorId | BatchId | RecordId | PrecinctId | Rank 1 | Rank 2 |  ... | Rank N

If contestId is NULL (ES&S) use Contest Name.

N = maxRanks for that contest.  maxRanks values for each contest are parsed from ContestManifest.json.

Columns #1 .. #n are populated with:
candidateID selected (marked) at that rank OR 
the string "over" / "under" if an under/over vote occurred

**Comment by tarheel** [comment]
Should we also export a config file with some of the values (e.g. the candidates and the CVR source) prepopulated?

**Comment by HEdingfield** [comment]
#434 filed to account for only lingering question in this issue.
