### ISSUE TITLE
split CVR based on jurisdiction

### ISSUE THREAD

**Issue by tarheel** [BrightSpots/rcv#405]
Nice to have: command-line option to read in a CVR file and export a set of files split by jurisdiction (e.g. precinct, congressional district, or county). This would facilitate the jurisdiction-based tabulation of the Dem primary contests in Kansas (CDs) and Wyoming (counties).

**Comment by moldover** [comment]
@tarheel I chatted with @CalebKleppner and splitting by jurisdiction will not be done by the tabulator.
