### ISSUE TITLE
Add user interface to support Dominion conversion process

### ISSUE THREAD

**Issue by moldover** [BrightSpots/rcv#408]
After talking with @CalebKleppner we arrived at the following:

The tabulator needs to ingest and process Dominion json data for various elections (Wyoming, Alaska, Kansas Democratic primaries, and eventually NYC local).  

To allow users to input, convert (verification / auditing - #404) and tabulate, we need a way for users to specify Dominion as a data provider.  For Dominion data providers, the user needs to specify an input Dominion folder location.  (First Vote Column Index, etc... are not needed)

**CLI support for conversion** this can be run from CLI: user supplies input Dominion data folder location.  Tabulator will input Dominion cvr json data from this folder.
Tabulator will export generic cvr csv to the same folder (#404) with a file per contest.

**GUI support for conversion**

User can click a "convert dominion cvr json to generic csv" button on the main panel.  This opens a file chooser.  User can select a file to convert.  Exported files will be written to the same folder as the input file.  Per @CalebKleppner no need to select an export folder.

Moved the Tabulation support tasks to a new ticket: #418

**Comment by tarheel** [comment]
Should there also be an arg for the output file path?

**Comment by moldover** [comment]
@CalebKleppner what do you think about Louis' question above?

**Comment by CalebKleppner** [comment]
A few comments:  1. The format from SF in Nov 2019 is different from the format going forward in SF and the Dem primaries.  The Dem primaries are using version 5.10.11.24.

**Comment by HEdingfield** [comment]
Relevant code that was used to temporarily test the new functionality:

```
    // for testing	
    String wyoming = "/Flair/Downloads/Dominion/Wyoming";	
    String sf = "/Flair/Downloads/Dominion/SF";	
    List<CastVoteRecord> castVoteRecords = new ArrayList<>();	
    DominionCvrReader test = new DominionCvrReader(wyoming);	
    try {	
      test.readCastVoteRecords(castVoteRecords);	
    } catch (CvrParseException e) {	
      e.printStackTrace();	
    }
```

**Comment by moldover** [comment]
Lol!  So I was looking for this sample code yesterday and the squash commit didn't have it. Sadness.  Going forward I'm going to use my judgement to squash or not.  Good to have in the toolbox.

Check out TabulatorSession.convertDominionCvrJsonToGenericCsv for the higher level functionality the UI / CLI code will tie into.  It just takes an input file to convert.  Per @CalebKleppner because Dominion data is always packaged with canonical names we can just export to the input folder.  If it's easy enough to collect an export file name from the user, I can incorporate that.  

As for UI, a (better?) idea is to just have a "convert dominion cvr" button on the main panel which opens a file chooser.  That sounds a lot cleaner than my suggestion in the ticket description :)

**Comment by HEdingfield** [comment]
It's right [thurr](https://github.com/BrightSpots/rcv/pull/411/commits), breh! Even if you squash, the PR still has a record of every commit that went into it.

**Comment by HEdingfield** [comment]
Per Slack conversation, decided to create a new panel in the UI that has the CLI-only functionality (`convert-to-cdf` and `convert-dominion-to-generic-csv`). Added #420 for the former.

**Comment by HEdingfield** [comment]
Also confirmed with @moldover that it's fine to change the conversion function to output in an "output" directory inside the folder with the JSONs instead of in the level above them (in the GUI the user will be able to specify where to save it), and to also include the timestamp as part of the filename.

**Comment by HEdingfield** [comment]
Relevant discussion from Slack:

> @HEdingfield: 
> Isn't our end goal to make the Dominion conversion process kind of behind-the-scenes? So instead of creating a separate button / area in the GUI for it, wouldn't it be better to just make the normal load function handle Dominion files? Or is this too advanced / too much work?
> 
> @moldover 
> so you’re right that, we do want to support Dominion as a first-class data source (just as we do for ES&S)
> however, we expose the conversion process as a way to verify the conversion process itself.
> we’ll need to do the same for any data source which has non-trivial input logic.
> so to your question, ‘wouldn’t it be better to just support it as a data source’ …
> yes, that would be better.
> we could read from data sources AND export the converted csv files for verification
> best of both worlds
> 
> @HEdingfield 
> Couldn't that just include providing the converted file as another output along with the results?
> 
> @moldover 
> right
> but there’s a few more wrinkles to consider -
> Dominion data sources specify multiple contest Ids
> Dominion data sources specify multiple contests (by Id)
> and tabulation process is done against for a single contest at a time
> (yes, one could tabulate all the contests for an election “at once”, but in actual practice, that is not what election admins do.  at least according to Caleb.)
> so actually getting all that figured out in a reasonable way is I think, a much bigger chunk of work, than just… plugging in a new fileReader to a new data source
> but that said, I do think we should do it
> so to recap: the “convert cvr” functionality is needed on it’s own right.
> 
> @tarheel 
> so if we wanted to support Dominion as a regular input, we would need the user to specify a contest ID param in the config also
> 
> @moldover 
> something like that, yes
> the dem primaires only have one contest, but take SF - it has like 20 or 30 contests
> Maybe it’s not that much work?

**Comment by HEdingfield** [comment]
Went with outputting to the input directory for now. Filed #437 for choosing output folder (and maybe also which contests are converted), and #438 for direct Dominion tabulation.
