### ISSUE TITLE
Add test(s) for Dominion parsing

### ISSUE THREAD

**Issue by HEdingfield** [BrightSpots/rcv#415]
Per the discussion in PR #411, we'll need to created automated tests (using provided input files) for Dominion once we receive verification of the expected results from @CalebKleppner. I believe #406 and #407 are blockers for this.

**Comment by HEdingfield** [comment]
This should also test the `convert-dominion-to-generic-csv` CLI option.

**Comment by moldover** [comment]
@HEdingfield what do you want to test about the CLI option?  It's pretty simple, right?

**Comment by HEdingfield** [comment]
I think this is fully covered by #425. We should do something similar for the `convert-to-cdf` functionality.
