### ISSUE TITLE
Add support for generic csv Tabulation

### ISSUE THREAD

**Issue by moldover** [BrightSpots/rcv#418]
Usability improvement:  per @CalebKleppner can work around this by using Excel to import .csv and save as an .xlsx for each cvr file:

1) User can specify "Generic" as the "source" in config file. (maybe make it a drop-down in GUI)
2) Tabulator will parse generic .csv file and tabulate as usual.

Maybe combine work with #251

**Comment by HEdingfield** [comment]
Happy to handle the GUI part of this.

**Comment by HEdingfield** [comment]
Not sure why this is showing as opened still...
