### ISSUE TITLE
NPE when using convert Dominion on a bad directory

### ISSUE THREAD

**Issue by HEdingfield** [BrightSpots/rcv#431]
When attempting to run the "Convert Dominion to Generic Format..." functionality, if you choose a bad directory, it fails in a slightly ungraceful way:

> 2020-03-24 21:29:23 PDT SEVERE: Error opening file: C:\BadPath\PrecinctPortionManifest.json
> java.io.FileNotFoundException: C:\BadPath\PrecinctPortionManifest.json (The system cannot find the file specified)
> Check file path and permissions and make sure they are correct!
> 2020-03-24 21:29:23 PDT SEVERE: Error parsing precinct manifest:
> java.lang.NullPointerException
> 2020-03-24 21:29:23 PDT SEVERE: No precinct data found!
> 2020-03-24 21:29:23 PDT SEVERE: Failed to convert Dominion CVR to CSV:
> network.brightspots.rcv.CastVoteRecord$CvrParseException

**Comment by tarheel** [comment]
will be fixed by #476
