### ISSUE TITLE
Dominion conversion: choose output folder and which contests are converted

### ISSUE THREAD

**Issue by HEdingfield** [BrightSpots/rcv#437]
This should probably be considered pretty low priority (if we even want to implement it at all), but @CalebKleppner mentioned in #408:

> I like the idea of having the Universal Tabulator read in a CvrExport.json file and spit out the rankings in .csv format. Because it takes a lot of time to read and export 3 million records, I think it'd be better to [use this option]: specify contest to export and output path (which for me will probably be the same input folder but nice to have the flexibility to specify output file).
>
> Is it too much to ask for the option to convert and export a single contest, specified by [contestId] or all contests, specified by [*]?

Right now, the conversion function outputs the converted files into the input directory, and automatically outputs all contests.

**Comment by moldover** [comment]
No longer relevatn.
