### ISSUE TITLE
Output should only use open file formats

### ISSUE THREAD

**Issue by HEdingfield** [BrightSpots/rcv#44]
* Migrate away from outputting .xlsx files towards .csv, .ods, or another open format.
* Make sure the results visualizer tool is able to use the chosen format.

**Comment by HEdingfield** [comment]
Make sure to fix any specific xls references in code, e.g.:
`ExtensionFilter("Excel files", "*.xls", "*.xlsx")`

**Comment by moldover** [comment]
Done.  Existing xlsx references are for input cvrs and should remain.
