### ISSUE TITLE
Support For Multiple Contests 

### ISSUE THREAD

**Issue by moldover** [BrightSpots/rcv#456]
Dominion and Hart CVR data supports the notion of multiple contests.  To support tabulating these data sources we need to:
- add contest ID field to the config (validation logic should require it when ingesting Hart or Dominion, otherwise ignore)
- allow user to specify contest ID in the GUI.  
- during tabulation filter input RCV data sources by contest ID 

It's worth considering if the existing Contest Name field could simply be used as-is.

update call site at // TODO: use contest Id (blocked by #456)

See #438 Dominion tabulation

**Comment by HEdingfield** [comment]
Re-opening to change `contestId` to a per-CVR field, per emails:

@HEdingfield 
> We're wondering now if Contest ID (which we'd probably label "Contest ID to Tabulate") should actually be a per-CVR setting, since it's required by Hart, Dominion, and maybe Clear Ballot, but shouldn't be populated for other CVRs?
>
> It doesn't seem to make sense to group Contest ID with Contest Name, since the former is more like an input setting than an output setting, since it's used to filter CVRs. This would also allow us to handle a potential situation where provider A uses contestId X and provider B uses contestId Y, even though they're referring to the same contest.

@chughes297 
> That makes sense to me, especially as users pull that info from each CVR.

**Comment by chughes297** [comment]
Could the label be Contest ID Number (is it always a number/would we expect it to always be a number)? 
And leave Contest Name the same?

**Comment by tarheel** [comment]
@moldover said that for Clear Ballot it might be a human-readable string instead of a number.

**Comment by HEdingfield** [comment]
Closed with #474.
