### ISSUE TITLE
Enable batch processing of multiple config files

### ISSUE THREAD

**Issue by HEdingfield** [BrightSpots/rcv#46]
Longer term goal: e.g. if Maine is tabulating 300 races in the same election, it's tedious to need to run the tool that many times.

* Maybe design ability to input a "config control file" that lists multiple configs to batch
* Maybe also allow batch creation of config files (e.g. if most parameters are the same between them, and just the input / output file names change)
* GUI should also support this

**Comment by CalebKleppner** [comment]
For v 1.0, we can stick with a batch file using command line to run multiple tabulations.

**Comment by HEdingfield** [comment]
Confirmed that all the functionality I originally outlined is actually in the application now, since you can specify multiple `cvrFileSources` in any given config now. Also building this into the config creator GUI.

**Comment by CalebKleppner** [comment]
That's good, but keep in mind that loading multiple CVR files in a 
single election is different from batch processing of multiple config 
files (each of which might contain multiple CVR files).

Caleb Kleppner
MK Election Services, LLC
203-376-4080

**Comment by HEdingfield** [comment]
Deleted comment from @CalebKleppner because it had PII in it. Original text:

> That's good, but keep in mind that loading multiple CVR files in a
single election is different from batch processing of multiple config
files (each of which might contain multiple CVR files).

This is true. I didn't think it would be worth building in the ability to run multiple config files at once (beyond using the CLI via batch file), as it seems like anyone running an election would likely only need to use a single config file. If this is an incorrect assumption and you think there'd be value in building this into the GUI though, feel free to re-open.
