### ISSUE TITLE
Load CVRs in .csv generic format

### ISSUE THREAD

**Issue by HEdingfield** [BrightSpots/rcv#464]
It would be great to be able to add a "Generic format" option to the provider dropdown, and then allow the user to specify .csv files (such as those output by the Dominion conversion process) to run a tabulation with them.

**Comment by HEdingfield** [comment]
Should also make sure to add a test for this (e.g. with one of the converted Dominion inputs).

**Comment by tarheel** [comment]
Merging this into #549 because that issue has a bit more detail.
