### ISSUE TITLE
Output generic CVR .csv format for Hart and Clear Vote and CDF as well

### ISSUE THREAD

**Issue by HEdingfield** [BrightSpots/rcv#468]
These formats aren't exactly easy to read, so it'd be nice to have that file available to make the more CVRs human-readable.

@moldover via Slack:
> The current generic csv format (and writer code) is based around what Caleb needed to verify the Dominion reader logic.  To generalize across the other formats would not be hard, but (for example) some Id names differ slightly between vendors (e.g. precinctPortionId vs. precinctSplit).  Some have data which others don't (tabulatorId). So there would be a task to figure out how those things can fit together, and update the generic csv format if needed.

**Comment by tarheel** [comment]
Proposal: don't output converted CSV files automatically, but instead add this an option in the app's Conversion menu (and offer a command-line equivalent) so that this feature is independent of the input format.

**Comment by chughes297** [comment]
We should do this for all CVRs (ES&S and the generic .csv mentioned in #549 and #599 would be functionally identical but still feels like a valuable auditing tool to have this)

**Comment by ggilber1** [comment]
Agree with @chughes297

**Comment by artoonie** [comment]
1. Is there any issue with just doing this every time we tabulate, like is done with Dominion already? (I lean yes.)
2. If we do, then it seems we won't need any CLI interface or option in the app's conversion menu. Shall we skip that? (I lean yes.)
3. Should we test that the conversions worked in every test in the test suite? (I lean no -- let's just have one test per format that tests this conversion).

**Comment by chughes297** [comment]
> 1. Is there any issue with just doing this every time we tabulate, like is done with Dominion already? (I lean yes.)
This may be me being pedantic but you mean just automatically producing this file every time we tabulate, right? I think that's the right idea too. 
> 2. If we do, then it seems we won't need any CLI interface or option in the app's conversion menu. Shall we skip that? (I lean yes.)
+1
> 3. Should we test that the conversions worked in every test in the test suite? (I lean no -- let's just have one test per format that tests this conversion).
Defer to you guys.
