### ISSUE TITLE
menu bar is sometimes unresponsive in Catalina

### ISSUE THREAD

**Issue by tarheel** [BrightSpots/rcv#469]
Sometimes when I first open the app, nothing happens when I click the menu bar items within the app. This persists until I switch to another app and back, and then it's fine.

Possibly related to this: https://bugs.openjdk.java.net/browse/JDK-8233678

Suggested workaround: https://stackoverflow.com/questions/58624764/javafx-global-menu-of-javafx-applications-unresponsive-on-macos-10-15-catalina

I saw one comment claiming that this only happens within an IDE. If that's true, this is definitely not a high priority.

**Comment by HEdingfield** [comment]
It also sounds like from the comments on that SO post that it would go away if we switch back from the menu to the buttons (which might be fine to do now that we probably don't need the Dominion conversion to generic functionality pretty soon?). Could you please verify if a version you create with `jlink` and run outside the IDE doesn't have the issue?

**Comment by tarheel** [comment]
I haven't seen this anymore, so I'm closing it.
