### ISSUE TITLE
Make sure all providers work with the CLI

### ISSUE THREAD

**Issue by HEdingfield** [BrightSpots/rcv#471]
This will likely include adding support for Hart, Dominion, and Clear Ballot.

**Comment by moldover** [comment]
@HEdingfield I just tested these and no problems.  Is there something in particular you think will fail when running from command line?

**Comment by HEdingfield** [comment]
Great, thanks! For some reason I had it in my head that these alternate providers would need special CLI flags, but that was just for the conversion functionality.
