### ISSUE TITLE
add support for overvote candidate delimiter

### ISSUE THREAD

**Issue by tarheel** [BrightSpots/rcv#482]
String config field for ES&S CVR sources.

**Comment by HEdingfield** [comment]
Before closing this bug, can we get @chughes297 's take on what the hint should be in the new hint panel for this?

**Comment by chughes297** [comment]
How will it function? The field is labeled
"Overvote Delimiter" and asks the user to put in what sort of character separates out the candidates selected at an overvote? 
In that case I think something like:
"Overvote delimiter: If using a CVR in ES&S format, overvotes can be reflected in a CVR by displaying all candidates marked at a ranking. Those candidate names will be differentiated from each other by a delimiter, something like a vertical bar | or a slash /. If your overvotes are delimited like this, enter the delimiter used in this field."

**Comment by HEdingfield** [comment]
Here's what @tarheel currently has in the .txt file in PR #503:

> "overvoteDelimiter" optional and used if and only if provider is ES&S
> string that will be used to split a cell into multiple candidate strings in the case of an overvote
> example: //
> value: any string that contains no backslashes and at least one character that is not a letter, number, hyphen, period, comma, apostrophe, quote, or space
> must be blank when overvoteLabel is provided

He's also fleshed this out:

> "overvoteRule" required
> how the program should handle an overvote when it encounters one
> value: "alwaysSkipToNextRank" | "exhaustImmediately" | "exhaustIfMultipleContinuing"
>   "alwaysSkipToNextRank": when we encounter an overvote, ignore this rank and look at the next rank in the cast vote record
>   "exhaustImmediately": exhaust a ballot as soon as we encounter an overvote
>   "exhaustIfMultipleContinuing": if more than one candidate in an overvote are continuing, exhaust the ballot; if only one, assign the vote to them; if none, continue to the next rank (not valid with an ES&S source unless overvoteDelimiter is supplied)

1) Do you think the hint you provided above explains what's in the .txt well enough?
2) Do we need to update the hint you provided for exhaustIfMultipleContinuing in #461?

> Exhaust if Multiple Continuing - if a voter has an overvote but only one candidate at that overvote is still in the race when that overvote is encountered, the ballot counts for that candidate. If multiple candidates at the overvote are still in the race, the ballot exhausts.]

**Comment by HEdingfield** [comment]
Ready to close this via PR #503 once we get the final word for you on the above, @chughes297.
