### ISSUE TITLE
Disable invalid Checkstyle warnings

### ISSUE THREAD

**Issue by HEdingfield** [BrightSpots/rcv#489]
When running Checkstyle on `HartCvrReader`, we get a number of errors like:

> Member name 'ImageId' must match pattern '^[a-z][a-z0-9][a-zA-Z0-9]*$'. [MemberName]

Checkstyle is complaining because it doesn't like the capitalized first letter, but if we don't do this, the Hart input won't parse properly. We need to disable these warnings for this file.

I've attempted to do this in one branch, but it's proving to be extremely painful for the reason outlined [here](https://stackoverflow.com/questions/62989823/suppressing-google-checkstyle-warnings-via-checkstyle-suppressions-xml).

**Comment by tarheel** [comment]
Maybe for the moment we should just update `google_checks.xml` directly?

**Comment by HEdingfield** [comment]
Closed with #526 

Ended up creating a separate `checkstyle-suppressions.xml` file to handle this. The downside is that `google_checks.xml` needed to be manually updated to load this properly, but I left instructions on this in `build.gradle` which should hopefully be a sufficient reminder to update this again in the future.

Ideally, I'd get an answer to my SO question (linked above) that would remove the need to manually modify `google_checks.xml`; hopefully we can do this in the future.

**Comment by HEdingfield** [comment]
Received a response to [this SO post](https://stackoverflow.com/a/64703619/3846321) that shows the way I originally hoped to resolve this.

**Comment by HEdingfield** [comment]
Fixed properly with #544.
