### ISSUE TITLE
Add support for interactive tiebreaking in the GUI

### ISSUE THREAD

**Issue by HEdingfield** [BrightSpots/rcv#49]

**Comment by CalebKleppner** [comment]
I think we are good, since we have interactive, previous round then interactive, previous round then random and permutation in config file.

**Comment by HEdingfield** [comment]
@tarheel @moldover can one of you please verify that this code is all in place and WAI, then re-close if so?

**Comment by HEdingfield** [comment]
Actually, I know for sure this isn't in the GUI yet, so we should keep this issue open. Would still appreciate confirmation if it works on command line.

**Comment by CalebKleppner** [comment]
So just ran test of interactive and random from GUI and command line.  Looks to me like random works from GUI and command line, and interactive only works from command line.  You have to select the candidate to eliminate in the console, and it  you run it in GUI, the tabulator chokes on the interaction.  Here's output from successful (command line) run followed by choke:

Thu Aug 09 12:46:19 EDT 2018 INFO: Yinka Dare lost a tie-breaker in round 2 against George Gervin. Each candidate had 3 vote(s). The losing candidate was supplied by the operator.

Thu Aug 09 12:47:24 EDT 2018 INFO: Candidate Yinka Dare got 3 votes.
Thu Aug 09 12:47:24 EDT 2018 INFO: Candidate George Gervin got 3 votes.
Thu Aug 09 12:47:24 EDT 2018 INFO: Candidate Mookie Blaylock got 4 votes.
Thu Aug 09 12:47:24 EDT 2018 SEVERE: ERROR during tabulation: java.lang.NullPointerException
Thu Aug 09 12:47:24 EDT 2018 INFO: Done logging tabulation to test_output\tiebreak_interactive\2018-08-09_12-47-24_audit.log

**Comment by HEdingfield** [comment]
@moldover @tarheel Banged my head against the wall for 8 hours on this. I got it working without multi-threading, but can't seem to do it with (and we need multi-threading so the logging console updates in real-time, and also so the GUI doesn't go inactive when it's tabulating).

The most helpful post I've found so far was [this one](https://stackoverflow.com/questions/14941084/javafx2-can-i-pause-a-background-task-service), but I'm getting an infinite loop when running the tiebreaker test when the window is supposed to pop up. [The docs](https://docs.oracle.com/javase/8/javafx/interoperability-tutorial/concurrency.htm) may also be a little bit useful.

I've pushed [messy commit](https://github.com/BrightSpots/rcv/commit/1bb630d66583e94f6b4dca12d47364e0b5fbc314) to branch gui-interactive-tiebreaking. PLEASE HELP!
