### ISSUE TITLE
use UnrecognizedCandidatesException in ClearBallotCvrReader and HartCvrReader

### ISSUE THREAD

**Issue by tarheel** [BrightSpots/rcv#491]
This would make them more consistent with how DominionCvrReader and StreamingCvrReader work. (Collecting all unrecognized candidate instances and reporting a summary instead of throwing an exception the first time it encounters an instance.)

**Comment by HEdingfield** [comment]
Not super urgent, obviously, but it'd be nice to fit in this iteration if possible.
