### ISSUE TITLE
Disable decimal places for vote arithmetic in non-multi-seat modes

### ISSUE THREAD

**Issue by HEdingfield** [BrightSpots/rcv#500]
* Disable "Decimal Places for Vote Arithmetic" for single-winner, bottoms-up, and multi-pass IRV contests.
* Possibly disable "Non-Integer Winning Threshold" as well. @chughes297 can you please confirm if this makes sense? (This seems to be the case based on #500.)

Full discussion below.

@HEdingfield:
> "Decimal Places for Vote Arithmetic" is currently required for all winner election modes, but it should be disabled for it's only visible in the multi-seat screen in the mock-ups. What's up with this? Should I include it for all other winner election modes as well?

@chughes297:
> Thinking here was that decimal places for vote arithmetic are only important in multi-winner RCV contests (not in single-winner, bottoms up, or multi-pass IRV contests) because the only instance where decimals really come in to play in RCV is during the threshold setting and surplus transfer steps in multi-winner RCV. In statute, too, the decimal place question has only come up in the multi-winner RCV context. It could matter in single-winner, bottoms up, or multi-pass IRV contests when calculating the threshold, but that decimal parameter has never been set in law (that I've seen). so I guess where I am now on this is - if asked this question in a non-multi-winner contest users will not know how to answer because there is no guidance in law, or we need to find a better way to ask the question (maybe just in those contexts? because multi-winner RCV users found "Decimal Places for Vote Arithmetic" made sense to them once they stopped to think about it) or it can be a hidden default setting? but we want to expose all settings, right? 

@HEdingfield:
> Deferring to Louis / Jon on this as well. In my cursory review of the code, it seems like it might be used in non-multi-winner cases too, but they'd have a better understanding than I do. If it is, we currently suggest a default value of 4, so we could keep that populating the box by default as it currently does. Right, I'm really not a fan of hiding things from the user, even if it makes it a little friendlier.

@tarheel:
> There's no scenario in which the value of decimalPlacesForVoteArithmetic would actually affect the outcome for an election that doesn't involve fractional transfers, right? As Chris said, it just affects the threshold calculation, but the difference won't matter when all of the tallies are always integers. So... I'm not sure what to say here.

@moldover:
> I don't have a strong opinion on hiding or not in this case, but perhaps changing the text to 'Decimal Places for Fractional Vote Transfers (Multi-Seat Only)' might help.   

@tarheel:
> So, it's what I said earlier. Technically it's used to set the precise winning threshold in those other modes. It just doesn't affect the outcome because the precision of the threshold is irrelevant when all of the vote tallies are integers.

@chughes297:
> Two things:
> 1) Confirming that we need only have this setting modifiable for the two multi-winner RCV variants (elect one at a time and elect multiple per round). 
> 2) From user tests people were confused by this setting/option in the non-multi-winner context. We would prefer to hide it in non-multi-winner election modes even if the tabulator is using it there because in practice this setting does not meaningfully impact the round-by-round count in non-multi-winner elections. If that's a no-go, can we have it be a non-modifiable setting in those elections (aka single-winner, multi-pass IRV, bottoms-up, % threshold bottoms-up)? Or like Jon suggests say something that communicates "important only in multi-winner, feel free to not worry about this" when in a non-multi-winner context? Could be as simple as "Decimal Places for Vote Arithmetic (important only in multi-winner RCV contests)."

@tarheel:
> Do we need to support non-integer winning thresholds for single-winner elections at all? Our understanding previously was that we did because of how certain jurisdictions specified their election rules, even though it shouldn't have an impact on the outcome. If we don't need to support this, we can hide both the "non-integer winning threshold" and the "number of decimal places" options whenever it's a single-winner contest.

@HEdingfield:
> What's the verdict on all of this? I've currently left it a required field for all Winner Election Modes with a suggested default value of 4.

@chughes297:
> This works. I would prefer to hide it for non-multi-winner options because it can confuse users, but my sense is auto-filling will do a pretty good job of avoiding confusion. Is making it uneditable for single-winner/multi-pass/bottoms-up methods confusing if also required?

**Comment by chughes297** [comment]
Hi yes disable non-integer for single-winner, bottoms-up, and multi-pass IRV.

**Comment by HEdingfield** [comment]
Fixed with #509.
