### ISSUE TITLE
computer name and user name aren't logged properly on macOS

### ISSUE THREAD

**Issue by tarheel** [BrightSpots/rcv#521]
Two issues:
- It should check USER in addition to USERNAME
- Java doesn't seem to be getting the env vars anyway

**Comment by HEdingfield** [comment]
Recommend first trying [this](https://stackoverflow.com/questions/473446/java-current-machine-name-and-logged-in-user) out.

If that still doesn't work, try [this](https://stackoverflow.com/a/17956000/3846321).
