### ISSUE TITLE
Open Help Menu does not work on Mac

### ISSUE THREAD

**Issue by moldover** [BrightSpots/rcv#528]
When running from the distribution build using the GUI, the Open Help Menu option fails with an error.
We need to convert the internal resource URL into a full file path, and specify the full path to the open utility (we are not running via a shell, so PATH is not defined, and simply calling 'open' fails to find the open utility)

**Comment by HEdingfield** [comment]
Doesn't work in Windows either :(

![image](https://user-images.githubusercontent.com/8259446/95025211-f699a180-063c-11eb-9f19-7b8f0a857668.png)

**Comment by moldover** [comment]
Turns out we are storing the file as a resource (packed with other resources) which is not available as a file without unpacking or some other strategy.

**Comment by moldover** [comment]
I pushed updates to halp_menu: it now simply shows a message directing the user to the config_file_documentation file.  Not a great user experience, but it’s an improvement.  IMO the big structural change we need would involve writing a comprehensive help document with context links from various UI elements.
