### ISSUE TITLE
Consider showing all log output in GUI text box

### ISSUE THREAD

**Issue by HEdingfield** [BrightSpots/rcv#53]
... rather than a few critical messages.

Should at least show the location of the output results and log files.

**Comment by HEdingfield** [comment]
Also (maybe this should be filed as a separate issue), change existing code to use Java default logging as much as possible, following best practices such as [these](https://stackoverflow.com/a/16448421/3846321).

**Comment by moldover** [comment]
We could show all log output in the GUI, but it gets pretty unwieldy for any real data.  I think the more useful course is your first suggestion, tell user where we are logging and show execution highlights in the GUI console.

As for class level logging, that's fine by me, though not critical (pun intended).

**Comment by HEdingfield** [comment]
Per PR #72 notes by @moldover :

> I tweaked the basic logging structure so that it is aligned with the hierarchical logging package as designed. There is still room for improvement but this achieves the goals of separating execution from audit logging and adds logging levels.
> 
> We now have a default logger with does console and "execution" logging to file. This is the root/parent logger, and ALL log messages will eventually get recorded here.
> 
> Above that is the "tabulation" logger, which has FileHandlers added/removed every time a tabulation runs.
> 
> Static helper functions (info, warn, severe) send log messages here (weather a tabulation is running or not) thus they will get logged to the tabulation file if it is installed, and propagated to the root handler.
> 
> @HEdingfield we could also add a custom Handler class which sends output to the GUI console. Maybe that gets broken out like: Logger.logGUI(Level, message) in code, and it would be childed to the Tabulator logger.

**Comment by HEdingfield** [comment]
Doing this would probably help address or solve #82.

**Comment by HEdingfield** [comment]
This looks promising for implementing a custom handler:
https://stackoverflow.com/questions/29927212/javafx-and-streamhandler

**Comment by HEdingfield** [comment]
From comments in #101:

> HEdingfield 2 days ago  Member
> My intuition is telling me that there's a more elegant way to implement the loggers so we can just make calls like executionLogger.warn("Blah!") instead of Logger.executionLog(Level.WARN, "Blah!"). In other words, maybe instead of having these four separate functions for logging in various permutations, it makes more sense to maintain four separate loggers with different permutations of handlers?
> 
>   @moldover
> moldover 2 days ago  Member
> I did think about this for a while and I could not come up with a simpler structure which still achieves the functionality we need. Not to say one doesn't exist, but I am satisfied with what I have here. I'm not sure entirely what you're suggesting, but having four loggers instead of 3 doesn't seem like an improvement.
> 
>   @HEdingfield
> HEdingfield 2 days ago  Member
> No problem, I'll think about it more and reassess once we get this merged in.
> 
>   @moldover
> moldover a day ago  Member
> I'm gonna keep thinking about it too. I think at least "auditLog" can simply be a log call to tabulationLogger with level = verbose, and we use level filter to keep that out of the GUI. This stuff isn't critical, but it's nice to keep it tight :)

**Comment by HEdingfield** [comment]
Fixed with #156.
