### ISSUE TITLE
Mention STV / multi-winner elections in the README

### ISSUE THREAD

**Issue by cjerdonek** [BrightSpots/rcv#545]
I noticed that the README doesn't mention that multi-winner elections are supported. I think it would be good to say this somewhere in the Overview section. I think it would also be good if STV could appear somewhere in the README for people searching for that term. Currently, it's hard to confirm that STV is supported.

**Comment by tarheel** [comment]
Thanks for the suggestions! I'll update the README.

**Comment by HEdingfield** [comment]
Addressed in #547. It's in the `develop` branch and will end up in `master` next time we do an official release.
