### ISSUE TITLE
optimize memory footprint of cast vote records

### ISSUE THREAD

**Issue by tarheel** [BrightSpots/rcv#552]
We're finding that the tabulator runs out of heap space as the number of ballots or the number of rankings per ballot increases. There's no simple way to support an infinite number of ballots or rankings, but we have plenty of ways to increase the ceiling quite a bit.

Some ideas (please add to the list):
- stop storing `fullCvrData` in the `CastVoteRecord` class (just print this to the log when the CVR is first read)
- call `String.intern()` for candidate names (I believe that right now we're allocating a brand new string in memory for each ranking in each CVR)
- simplify the CVR class for single-winner elections (there's some complexity that's only relevant to multi-winner but still ends up expanding the footprint of CVRs when we're processing single-winner contests)

**Comment by chughes297** [comment]
same comment as what I just put on #559

**Comment by artoonie** [comment]
Left comments on the PR, but to summarize here:
1. Removed fullCvrData
2. Changed a data structure
3. string.intern() had no effect
4. I'm not sure what we can simplify for the single-winner CVRs, but I'm not sure more is needed. Is there a "good enough" condition here?

**Comment by artoonie** [comment]
# Audit Log questions
There are some minor improvements to the audit log. They were made to optimize memory, but I think they also make the audit log nicer. I'd like to run them by some stakeholders.

These logs have been trimmed to the relevant sections and had timestamps removed for easier side-by-side comparison.

## Previous Audit Log
[previous-audit-log.log](https://github.com/BrightSpots/rcv/files/11201609/previous-audit-log.log)
Note: The Raw Data sort of clutters Round 1 data, and makes Round 1 look different than the other rounds.

## New Audit Log
[new-audit-log.log](https://github.com/BrightSpots/rcv/files/11201608/new-audit-log.log)
Note: the [Raw Data] is now in a separate section, and not tied to the Round 1 audit. The log is longer, but IMO cleaner.

@rrojas350 @chughes297 can you confirm the new audit log format is acceptable?

**Comment by chughes297** [comment]
This looks good to me too! Definitely more readable.
