### ISSUE TITLE
Hare quota is calculated incorrectly

### ISSUE THREAD

**Issue by tarheel** [BrightSpots/rcv#557]
With the Hare quota, a candidate should be elected if their vote total is greater than *or equal to* the calculated threshold. Our code is incorrectly requiring the total to be greater than or equal to `floor(numVotes / numSeats) + 1`.

Short term: document this bug.

Next release: fix it (quick update to `setWinningThreshold` in `Tabulator`).

**Comment by NCGThompson** [comment]
I was already editing setWinningThreshold() in #560 so I went ahead and fixed this in that pull request. See the commit notes for explanation.

**Comment by NCGThompson** [comment]
How, precisely should hare quota be calculated with finite precision? My first thought was simply threshold = config.divide(currentRoundTotalVotes, divisor), but it might make sense to do threshold = currentRoundTotalVotes.divide(divisor) and manually specify a high degree of precision. By a "high degree of precision" I mean we approximate the exact value to >40 digits. It isn't mathematically but it could work.

**Comment by NCGThompson** [comment]
Pull request #562 fixes this.
