### ISSUE TITLE
Using % in config crashes (it is technically a valid windows path name)

### ISSUE THREAD

**Issue by moldover** [BrightSpots/rcv#561]

**Comment by moldover** [comment]
When config contents are initially logged passing a path with % causes UnknownFormatConversionException

**Comment by andyanderson** [comment]
Issue [#564](https://github.com/BrightSpots/rcv/issues/564#issuecomment-822174275) provides more detail about the source of this bug.

**Comment by moldover** [comment]
Fixed with PR #601
