### ISSUE TITLE
Multiple return statements

### ISSUE THREAD

**Issue by moldover** [BrightSpots/rcv#567]
VVSG coding standards forbid multiple return statements.  Remove from:

ContestConfig.java:
function ContestConfig.loadContestConfig
line 123

Tabulator.java: 
function Tabulator.shouldContinueTabulating
lines 392, 396

Logger.java
line 141
Logger.addGuiLogging

**Comment by rrojas350** [comment]
According the SLI, who reported the previous issue, [#581](https://github.com/BrightSpots/rcv/issues/581), this is considered a "Moderate Risk." SLI is one of two EAC accredited Voting System Test Labs (VSTL), and responsible for certification of RCTab, so I would consider it a hard requirement as they may not let it slide in future certifications. 

On the flip side, I would hate to fix something only to have it cause more issues.

**Comment by tarheel** [comment]
Yeah, it's a counterproductive/silly requirement, but it seems to be non-negotiable, so we just have to hold our nose and do it.

**Comment by andyanderson** [comment]
Too bad Java doesn’t have a goto statement, it would make it so much easier 😂

**Comment by tamird** [comment]
Also too bad that Java is not expression-oriented; this would be a natural pattern in e.g. Kotlin.

**Comment by tarheel** [comment]
> Too bad Java doesn’t have a goto statement, it would make it so much easier 😂

I should have listened to my original instinct to write this application in QuickBASIC.

**Comment by moldover** [comment]
Closed via PR #600
