### ISSUE TITLE
Create installer / standalone executable

### ISSUE THREAD

**Issue by HEdingfield** [BrightSpots/rcv#57]
Determine the workflow needed to create a platform-independent installer and/or standalone executable for each serious release.

**Comment by gngilbert** [comment]
This would be very good to have but I have no idea how much work is involved.

**Comment by HEdingfield** [comment]
Now that we use Gradle, we can look into using `jpackage` to create separate installers for each platform.

If we can do this, it will probably effectively fix #282 also.

**Comment by rrojas350** [comment]
Originally removed to make room for other issues but this request has popped back up. Updating as a lower priority item and a nice-to-have if possible.

**Comment by HEdingfield** [comment]
@artoonie was able to close this after years with #660! 🥳

**Comment by yezr** [comment]
trying to see if i can associate the PR if it is open
