### ISSUE TITLE
Improve documentation and create tutorial

### ISSUE THREAD

**Issue by HEdingfield** [BrightSpots/rcv#58]
Create a tutorial to help users install the software, tabulate the example data, etc.

**Comment by HEdingfield** [comment]
In the current zipped-up version we have for distribution, there's zero guidance on installation and how to run the tabulator.

**Comment by gngilbert** [comment]
I know we have done some of this.  Need to identify what more is needed.

**Comment by chughes297** [comment]
Happy to help draft/review any tutorials or other documentation for the tabulator.

**Comment by HEdingfield** [comment]
Related to #281.

Add to README: CLI instructions for cloning repo locally, running javac with gradle, etc. to build it.

Also update UserGuide as needed.

**Comment by HEdingfield** [comment]
Closed with #315.
