### ISSUE TITLE
Incomplete Module Headers

### ISSUE THREAD

**Issue by rrojas350** [BrightSpots/rcv#582]
Pulled this from SLI's testing report of RCTab. Their source code review findings are as follows:

VVSG 1.0 Requirement: In addition to the unique name, the modules shall include a set of header comments identifying the module’s purpose, design, conditions, and version history, followed by the operational code.

Comment: "Non-functional issue related to ability to read/maintain the source code itself."

Number of Findings: 23
Risk Level: Low

**Comment by tarheel** [comment]
Adding the version history within the files themselves wouldn't make sense given that this code repository is publicly visible and anyone can easily view the full history. But we can add brief comments to the top of each file.

**Comment by moldover** [comment]
The actual VVSG text from section 5.2.3:

b. Each module shall be uniquely and mnemonically named, using names that differ by more than a single character. In addition to the unique name, the modules shall include a set of header comments identifying the module’s purpose, design, conditions, and version history, followed by the operational code. Headers are optional for modules of fewer than ten executable lines where the subject module is embedded in a larger module that has a header containing the header information. Library modules shall also have a header comment describing the purpose of the library and version information.

**Comment by moldover** [comment]
closed via #606
