### ISSUE TITLE
More than 5 nested scopes: VVSG Vol 2: 5.4.2.r

### ISSUE THREAD

**Issue by rrojas350** [BrightSpots/rcv#583]
Pulled this from SLI's testing report of RCTab. Their source code review findings are as follows:

Description: More than 5 levels of indented scope. 
Comment: Non-functional issue related to ability to read/maintain the source code itself.

Number of Findings: 22
Risk Level: Low

**Comment by tarheel** [comment]
This is a pretty arbitrary and counterproductive standard, but I guess it's easy enough to meet it by just factoring out logic into helper functions when necessary.

**Comment by rrojas350** [comment]
That's Louis, as we work on new builds, I want to clear up anything that'll rustle SLI's feathers, to make our next certification as seamless as possible.

**Comment by tarheel** [comment]
Yep, makes sense.

**Comment by moldover** [comment]
@rrojas350 @tarheel I looked into this today.  Intellij has a code inspection plugin which checks for this sort of thing:

Preferences::Editor::Inspections::Java::Method Metrics::Overly Nested Method.  Using this inspection I confirm that our code does not in fact have six (or more) levels of scope anywhere.  I made a fake deeply nested scope to make sure the inspection actually does what I think, and indeed it picked up my fake deeply nested scope.

This makes sense to me, because we've been good about keeping our function size and complexity reasonable.  

So I don't really know what SLI is complaining about, and I'm not sure how to proceed here.

**Comment by tarheel** [comment]
> Is it possible they are just complaining about visual indentation (tabs / whitespace) ? That's not really "scope" as I understand it.

Maybe? Are there examples that would fit that description? If so, how? I guess if you're at level 5 and then you have a multi-line statement that indents the lines after the first one? But I agree that that's not "scope."

Is there a document that shows the specific cases they flagged?

**Comment by rrojas350** [comment]
Sorry for the late reply, I had to take care of an exploding sunroof issue. It was a Monday for sure...

SLI didn't offer any examples or more detail than what was listed above, but feel free to take a look at their report. If needed, I can reach out to them and get some clarification on this point, but their response time varies. 
[SLI RCVRC RCV Universal Tabulator Test Report v4.0.pdf](https://github.com/BrightSpots/rcv/files/8855212/SLI.RCVRC.RCV.Universal.Tabulator.Test.Report.v4.0.pdf)

**Comment by moldover** [comment]
I looked up the rule cited and indeed they are claiming we have 6 (or more?) nested levels of scope (not whitespace / indentation)   I think this is bunk.  I don't think we come close anywhere.   @rrojas350 can you ask for clarification as to where these findings actually are in the code?  Like, file+line numbers.   If they could show at least one example that would probably be enough.

**Comment by moldover** [comment]
@rrojas350 ... I worked on this some more today, and I figured out I wasn't using the inspection tool correctly before.  I was able to find 3 instances of this problem in our code.   Sorry for the confusion.  Should be straight forward to fix.  Now I still don't know where they get 22 infractions from, so it's worth getting whatever specifics they can provide, to keep things seamless.

**Comment by rrojas350** [comment]
Great to hear Jon! I'll reach out to SLI and see if I can find out why they marked 19 additional infractions and get some clarification on the issue as a whole.

**Comment by tarheel** [comment]
@moldover what are the 3 that you found?

**Comment by moldover** [comment]
Tabulator.java line 483
ResultsWriter.java line 556
CDFReader.java line 241

**Comment by moldover** [comment]
Closed via #602.

**Comment by HEdingfield** [comment]
@rrojas350 did you ever hear back about the other 19 alleged infractions?

**Comment by rrojas350** [comment]
@HEdingfield I haven't heard back from SLI, but I could pester SLI a bit more. To be honest, beyond the initial email I sent, this issue got pushed back on my tasks list due to some conferences and other projects. I'll get on it this week and see if we can't squeeze some more information from SLI.

**Comment by rrojas350** [comment]
Update, I was able to get a hold of someone from SLI and they're forwarding our SLI report and questions to their certification team for clarification. Stay tuned.

**Comment by rrojas350** [comment]
SLI responded to this issue with the following:

"It looks like the differences can be attributed to how levels of indented scope are counted. Typically we would count file level as 0(this would be the left margin), then each time a line is physically indented for things like Classes, functions/methods, if statements, or loops would be counted as +1.

Many of the instances that RCVR is counting as 5 or 6 depends on whether you start with the class level as 0 or 1.

For example, in the file CommonDataFormatReader.java on line 128 we see the function parseXml(). Inside of this function from line 177-264 we see a clear example. This function is inside of the class that the file contains.

So counting logical levels, we have the file level as 0, class level as 1(this is based of the physical indentation away from the left margin for the class scope), the function as 2, the first ‘for’ block at line 186 as 3, the nested ‘if’ at line186 as 4, the next nested ‘for’ would be 5. This means that every level of indentation past this point is in violation. So if statement on lines 188, 195, 201 and 237 are nested 6 levels.

The ‘if’ statement on lines 208, 214, 222, 229, and 231 are at 7 levels. All the if statements between lines 239 and 258 are then indented even further.

We can reduce the levels of indented scope by 1 if we count the class level as 0 since java is a class based language and does put the class declaration against the left margin. The contents of the class will have to be indented because this is how scope is defined, in which case many of the issues would have been non issues.

So outside of the example given it I think we can safely say that we just counted differently and those issues can be closed. "

**Comment by moldover** [comment]
Thanks Rene.  This explains why they flagged so many violations.  I think their reading on how to count nested scopes does not line up with the intent of the rule (the actual text is somewhat vague) and that in fact the _class level scope should not count towards function complexity_.  They seemed ok with that reading at the end of their feedback so I think we are in agreement.  Following is the actual text for reference.

From the VVSG 2005 1.0 Vol2, section 5.4.2 Assessment of Coding Conventions (page 86):

Has functions with fewer than six levels of indented scope, counted as follows:

int function()
{
      if (a = true)
_1_ {
            if ( b = true )
_2_      {
                  if ( c = true )
_3_            {
                        if ( d = true )
_4_                 {
                              while(e > 0 )
_5_                       {
                                    `code`
                             }
                       }
                  }
            }
       }
 }
