### ISSUE TITLE
Static CVR Provider and File Path

### ISSUE THREAD

**Issue by rrojas350** [BrightSpots/rcv#592]
Related to #589 

Having CVR Provider and File Path saved and carried over by a JSON config file. This will help jurisdictions create a complete JSON config file for easy election night tabulation and the addition of new CVR files. Could be solved by #589.

**Comment by HEdingfield** [comment]
To clarify this: the ask is that, when a user loads an existing config file and then they attempt to add a path to a new CVR file, it will attempt to open the dialog box at the location of the last CVR file that's already in the list? And also pre-populate provider with the same one as the last one in the list?

**Comment by rrojas350** [comment]
Correct Hylton.

**Comment by HEdingfield** [comment]
Given the resolution of #589, I don't think this should necessary any longer. Feel free to re-open if anyone disagrees.
