### ISSUE TITLE
Visual Indicator for Mandatory Fields

### ISSUE THREAD

**Issue by rrojas350** [BrightSpots/rcv#593]
A visual indicator that a mandatory field has been completed by the user. Example, empty mandatory fields' text background could be filled with red when empty and switch to green when filled in. 

Related to #137

**Comment by HEdingfield** [comment]
We already do have a visual indicator for mandatory fields in the form of * next to the name of the field (these are also labeled as "required" in the hint pane on the right).

Is this request specifically to highlight fields that fail validation in red? I don't think it's a standard UX pattern to pre-emptively make fields red before the user has even attempted to enter data in them.

**Comment by rrojas350** [comment]
The request was specific to pre-validation, but highlighting the field after a failed validation makes more sense. Even if required fields are only highlighted after validation, the users should still get the message.

**Comment by HEdingfield** [comment]
Sounds good, I'll close this in lieu of #137 then (tagged that with 1.3 Nice-to-Have).
