### ISSUE TITLE
"Hints for this tab" Improvements/Tool Tips Improvements

### ISSUE THREAD

**Issue by rrojas350** [BrightSpots/rcv#595]
Highlight or bold the hint relevant to the field the user is working in. E.g. If the User is entering info in Contest Name, the Hint "Contest Name (Required):..." is bolded for quick reference. 

Alternatively, Hints could be removed and an icon for more information "ⓘ" could be placed in each field with a hint available.

**Comment by HEdingfield** [comment]
Duplicate of #513.
