### ISSUE TITLE
CSV copy of Results JSON

### ISSUE THREAD

**Issue by rrojas350** [BrightSpots/rcv#597]
RCTab should produce a csv version of the Results JSON for easy inspection/auditing.

**Comment by HEdingfield** [comment]
I don't understand this request -- we already output both a CSV version and a JSON version of the results, and the CSV version is much more readable. E.g.:

* 2022-08-07_11-01-42_MINNEAPOLIS_W-1_P-01_precinct_summary.csv
* 2022-08-07_11-01-42_MINNEAPOLIS_W-1_P-01_precinct_summary.json

Both of the above our output when I run the `2013_minneapolis_mayor_config.json` test data set.

**Comment by chughes297** [comment]
I am also confused by this request. I just looked at our notes from the user group meeting and it's not any clearer. I think the person making the request may not have realized that the JSON and CSV summaries are essentially the same file.

**Comment by rrojas350** [comment]
Agreed. I considered not posting this issue for those reasons, but wanted to get all user requests up. 

The user that requested this wanted an easier to read version of the JSON but the CSV results accomplishes that. I'll close this issue for now, and maybe this could be solved by adding a line or two to documentation.
