### ISSUE TITLE
Support hash verification for CVR files

### ISSUE THREAD

**Issue by tarheel** [BrightSpots/rcv#61]

**Comment by HEdingfield** [comment]
Context from email conversation:

> @HEdingfield
> Looks like there are a number of GUI utilities out there, but I'd be inclined to encourage people to use OS-specific ones like [Microsoft's](https://www.microsoft.com/en-us/download/details.aspx?id=11533). It may even be something that we can build into the tabulator.
> 
> @tarheel 
> The way I'd envisioned it is that the hash would be generated on the machine that originally produced each CVR file... and then the election config would include the expected hash for each source file, and the tabulator would compute the hash for each file and compare that to the expected hash in the config. So the challenge would be to get administrators to generate hashes properly on the source machines. Does that sound right?

**Comment by gngilbert** [comment]
Since generating hash values for CVRs is not currently a standard practice in any voting system, it is unlikely that this issue will arise in this round of certification.

**Comment by yezr** [comment]
fixed with #746
