### ISSUE TITLE
Bring test data back into main RCTab repo

### ISSUE THREAD

**Issue by HEdingfield** [BrightSpots/rcv#612]
Per discussion in #576, we should consider moving the data from https://github.com/BrightSpots/rcvtests back into the main repo.

**Comment by tarheel** [comment]
@moldover @HEdingfield OK, how about we go ahead and do this now? I wouldn't mind having a simpler process for finishing my open PRs...

**Comment by moldover** [comment]
@tarheel you sure you dont want to learn more about submodules first?

**Comment by HEdingfield** [comment]
The sass is off the charts. @moldover do you have any availability to do this? I'm working on a few other issues at the moment and I think @tarheel is too.

**Comment by moldover** [comment]
Twould be my pleasure.

**Comment by HEdingfield** [comment]
Before closing this issue, could you please let us know if there are any Git commands we need to run locally to undo [these steps]()?

Also, let's delete the repos [here](https://github.com/BrightSpots/rcvtests) and [here](https://github.com/artoonie/rcvtests) (CC @artoonie) as soon as we verify that the tests are running successfully locally.

**Comment by artoonie** [comment]
I've archived the repo, effectively marking it as stale/out-of-date. LMK if you prefer a full deletion.

**Comment by HEdingfield** [comment]
@artoonie Ok, sounds good. I think it's safe to delete on your end; I'll archive our fork of it and plan to delete it in a month or so if everything is still going smoothly.

@tarheel noted, after the above PR:

>  I reverted any changes I had made inside the test dir, then checked out develop, ran `git submodule deinit --all`, then `git pull`, and it appears to have worked

**Comment by HEdingfield** [comment]
Just deleted BrightSpots/rcvtests.

**Comment by tarheel** [comment]
Good night, sweet prince,
And flights of angels sing thee to thy rest.
