### ISSUE TITLE
Hart CVR fails in v1.3 

### ISSUE THREAD

**Issue by rrojas350** [BrightSpots/rcv#629]
When trying to tabulate a new CVR from Hart RCTab v1.3 produces this error: "Error during tabulation:
"javax.xml.stream.FactoryConfigurationError: Provider for javax.xml.stream.XMLInputFactory cannot be found
Tabulation failed!"

The same file tabulates in v1.2 without issue.  
[2023-02-06_13-29-36_audit_0.log](https://github.com/BrightSpots/rcv/files/10680045/2023-02-06_13-29-36_audit_0.log)

**Comment by tarheel** [comment]
also a dupe of #625!
