### ISSUE TITLE
Handle multiple Candidate IDs in CDF

### ISSUE THREAD

**Issue by artoonie** [BrightSpots/rcv#645]
A CDF can have multiple candidate IDs. Currently, there is a warning:
```
"CandidateSelection \"%s\" has multiple CandidateIds. Only the first one will be processed.",
```
Once we support aliases (https://github.com/BrightSpots/rcv/pull/639), we won't need this limitation.

```
  "Election" : [ {
    "Contest" : [ {
      "ContestSelection" : [ {
        "CandidateIds" : [ "id0", "id1" ]
      },
```

**Comment by artoonie** [comment]
Note: will wait for https://github.com/BrightSpots/rcv/pull/639 to merge before working on this to avoid creating a too-long PR chain.

**Comment by HEdingfield** [comment]
@chughes297 could you please comment on the questions raised in #684?

**Comment by HEdingfield** [comment]
@chughes297 commented in #684:

> If I'm understanding things correctly, the only time a candidate will have multiple IDs in the CDF is in a party ticket context? If my understanding is correct, I'd say yes we don't need to support this. Nowhere using RCV now (or in the near term) combines it with party ticket, so this doesn't seem necessary/valuable to include.

@artoonie if what Chris says is the case, should we close that PR and this issue?

**Comment by artoonie** [comment]
Note: abandoned this; not something we need. See discussion in #684
