### ISSUE TITLE
require output directory (config validation)

### ISSUE THREAD

**Issue by tarheel** [BrightSpots/rcv#66]

**Comment by HEdingfield** [comment]
Context, PR #64 conversation regarding precinctOutputDirectory field:

> @HEdingfield
> I think that we should have a general outputDirectory field (i.e. where the log and visualizer files go) in each config file instead of a special one for precincts only. Been wanting to make this happen for a little while now. Think we can work it into this branch before the merge?
> 
> @moldover
> This is fine, and I'm thinking maybe we should go one step further and stop letting the user specify output file names entirely to simplify things. They just enter the output folder, and we generate names for the outputs like _visualizer.xls, _audit.txt and so on (new guid for every tabulation)

Conversation regarding `if (outputDir != null)`:

> @HEdingfield
> What if outputDir == null?
> 
> @moldover 
> we should validate that in the config settings validate call, then this code can assume a valid output.
> 
> @tarheel 
> I'm not currently requiring that they specify an output dir. (It just defaults to the current directory.)

Conversation regarding `Logger.log("Failed to create precinct output dir: " + outputDir);`:

> @HEdingfield
> Should we throw an exception here?
> 
> @moldover 
> I'd propose validate and make the directory in config.validate as well.

**Comment by HEdingfield** [comment]
Also in PR #72:

> src/com/rcv/Logger.java
> -for (Handler h : logger.getHandlers()) {
> -logger.removeHandler(h);
> +// throws: IOException if unable to open loggerOutputPath
> +static void addLogger(String loggerOutputPath, Boolean logToConsole) throws IOException {
> 
>   @HEdingfield
> HEdingfield 5 days ago  Member
> Can we validate the loggerOutputPath first? i.e. make sure it's actually a place that exists and we have permission to write there?
> 
>   @moldover
> moldover 10 hours ago  Member
> i agree we should validate, but I would prefer to do all the validating "up front" in one function called when a config file is first loaded, and when a tabulation run is started.

**Comment by HEdingfield** [comment]
@tarheel is this issue officially resolved now with [your cowboy commit](https://github.com/BrightSpots/rcv/commit/5fc4d4d0d32603df8d26f5bae1f7da0015e9e764) to master last night? 😈

**Comment by tarheel** [comment]
Er, no. Currently we default to the current working directory if outputDirectory isn't specified. Should we make it required?

**Comment by moldover** [comment]
... on reflection, I think yes.  Output files are essential to the operation, and if we default to current dir, it is pretty "buried" for most users.  My suggestion is as the PR states, require an output dir and otherwise validation fails.

**Comment by HEdingfield** [comment]
Agree with this. In the UI I'll probably set up a nice FileChooser to handle this.
