### ISSUE TITLE
Allow selection of multiple CVR files at once

### ISSUE THREAD

**Issue by chughes297** [BrightSpots/rcv#673]
Received a request to make it possible to select multiple CVR files at once when selecting them via the "Select" dialog on the CVR files tab.

**Comment by chughes297** [comment]
Looking through other issues and I think this is resolved by #617. I'm going to close this given that.

**Comment by chughes297** [comment]
I think that's fine, we can put it in a user guide and mention in the info box on the CVR tab?

**Comment by HEdingfield** [comment]
Re-opening this issue to fulfill the two items @chughes297 outlined above.

**Comment by yezr** [comment]
confirmed that this is in the info box on the CVR tab and I've updated the TDP to be more explicit about what each vendor's CVRs should look like



![Image](https://github.com/BrightSpots/rcv/assets/8996546/c0e4b1a5-a4a5-41d9-82b8-0d08f36404e3)
