### ISSUE TITLE
List total number of CVR files added on CVR Files tab

### ISSUE THREAD

**Issue by chughes297** [BrightSpots/rcv#674]
so admins have another way to check that they've uploaded their full set of CVRs

**Comment by yezr** [comment]
Where do we want this? I was thinking as a second line of text "CVR File Count: X" or "Number of Configured CVR files: X" under the current "Double-click to edit." text? Or right after? That would update every time a CVR file was added. 

![Image](https://github.com/BrightSpots/rcv/assets/8996546/2032ce0d-85c3-4421-a66e-4de2f1599f68)

**Comment by yezr** [comment]
also could make the CVR table shorter and put the configured count below the table and above the log

**Comment by artoonie** [comment]
How about this instead? I think this style is a more commonly-used UI:

![Image](https://github.com/BrightSpots/rcv/assets/537316/61be2f73-1a62-4b54-9fba-f0b69670e035)

**Comment by yezr** [comment]
lol! so simple! That is perfect

**Comment by artoonie** [comment]
Cool! Want it for the Candidate list too? It's one line of code to add it to any table now.

**Comment by yezr** [comment]
Yes, candidate list as well please!
