### ISSUE TITLE
Notify users that candidate names must match names in CVR files exactly

### ISSUE THREAD

**Issue by chughes297** [BrightSpots/rcv#677]
I imagine this should be right at the start of the info box on the candidates tab. 

Not sure how this interacts with #60 (or #591 ,#628 ,  #663 , and #645) (I just looked for all issues mentioning candidates that seemed relevant).

**Comment by HEdingfield** [comment]
@chughes297 Is this as simple as adding a sentence in the UI that says "Candidate names must match names in CVR files exactly."?

**Comment by chughes297** [comment]
Honestly yes I think that's all it needs.

sent from my phone
