### ISSUE TITLE
Add "Total votes cast" to summary results files. 

### ISSUE THREAD

**Issue by chughes297** [BrightSpots/rcv#678]
This specific information is included in the results report suggested in #633. This is a much smaller request to just add a single additional piece of info with the total votes counted in the contest (all active + inactive ballots + undervoted ballots). I'm not sure if we want to do this separately because it's very simple or just do the whole results report overhaul.

**Comment by HEdingfield** [comment]
@chughes297 Do you want this to appear just before starting tabulation and display the number of CVRs picked up? Or do you want it display at the end, with the actual number of CVRs tabulated? Or both?

**Comment by chughes297** [comment]
This should be in the results output files in the location suggested in #633.

**Comment by chughes297** [comment]
and it should be full number of CVRs picked up.
