### ISSUE TITLE
Fix final-round tiebreaker

### ISSUE THREAD

**Issue by artoonie** [BrightSpots/rcv#694]
https://github.com/BrightSpots/rcv/pull/646#discussion_r1224709054

As seen in `tiebreak_seed_test`, the tiebreaker should occur on the winner, not the elimination, when it occurs in the final round of a single-winner election

**Comment by chughes297** [comment]
in thinking about this more it might be good to give a user both elect and eliminate options in the case of this tie occuring. I'm not sure how, exactly, people will draft law here and want to stay flexible. is that realistic to implement?

**Comment by artoonie** [comment]
Seems reasonable -- only downside of offering too many options is just that: it can overwhelm the UI, and complicate ongoing maintenance. (Perhaps we could eventually consider an "Advanced Options" section or similar, to hide away the rarely-used options, like this, where we believe no municipality actually uses that option?)

**Comment by tarheel** [comment]
Agree about burying all of the obscure options like this one. Maybe make an issue for next release?

And I agree that just adding one more setting (a checkbox) is probably appropriate here. One question about that: would that setting apply only to the final-round tiebreaker case, or would it also apply to the "two candidates left and neither met the threshold" case?

Also note that this setting kind of overlaps, at least conceptually, with the existing "continue until two candidates remain" option. Maybe there's a way to consolidate these into a single setting (dropdown or boolean)... or maybe not.

**Comment by chughes297** [comment]
It should apply to "two candidates failed to cross threshold" as well - I think of that in the same breath as the final round in a dynamic threshold contest. 

I think conceptually this does overlap with continue until two, but in practice people will not necessarily make consistent policy choices in law between tabulation and tiebreaking.
