### ISSUE TITLE
Convert to CDF throws NPE on test data

### ISSUE THREAD

**Issue by HEdingfield** [BrightSpots/rcv#703]
Load up the `2013_minneapolis_mayor` test data and attempt to "Convert CVRs in Current Config to CDF" , and observe that it fails:

```
...
2023-06-13 23:55:56 PDT INFO: Parsed 50000 cast vote records.
2023-06-13 23:55:56 PDT INFO: Parsed 80101 cast vote records successfully.
2023-06-13 23:55:56 PDT SEVERE: Error when attempting to convert to CDF:
java.lang.NullPointerException: Cannot invoke "java.util.Set.iterator()" because "this.precinctIds" is null
Conversion failed!
```

**Comment by HEdingfield** [comment]
Same thing happens with `2013_minneapolis_park_hare`, `2015_portland_mayor`, `dominion_wyoming`, etc. I couldn't find any test data where this was actually _working_.

**Comment by artoonie** [comment]
Yikes! Perhaps worth adding a test here :) will take a look!
