### ISSUE TITLE
Clarify Undervotes vs Skipped Votes in UI, config files, and comments

### ISSUE THREAD

**Issue by artoonie** [BrightSpots/rcv#718]
See comments in #633 

The phrase "undervotes" is used to mean both "voter did not rank anything" and "voter skipped too many rankings."

Clean this up.

**Comment by tarheel** [comment]
We also erroneously use it to refer to a single skipped ranking in the context of the "undervote label," as @chughes297 noted.

**Comment by chughes297** [comment]
Noticed that ES&S CVRs now automatically load the label "skipped ranking" in the skipped ranking field but, annoyingly, ES&S will probably continue to refer to them as "undervotes" in the CVR. I realize it's non-intuitive, but can software will automatically load the label "undervote" in the skipped ranking field for ES&S CVRs?

**Comment by artoonie** [comment]
Yep! Done.
