### ISSUE TITLE
Switch tests over to use `dict` comparisons

### ISSUE THREAD

**Issue by HEdingfield** [BrightSpots/rcv#723]
I noticed a new line appearing in all our test summaries / outputs: `"generatedBy" : "RCTab 1.4.0-alpha",` which seems brittle to me.

Discussed with @artoonie and he recommended that we switch our tests over to doing a `dict` comparison rather than a line-by-line file comparison. Advantages include:

* You can comment test files
* Different OSs might have different HashMap implementations, which would output different orders in dictionaries, leading to different line-by-line JSONs that are actually the same
* You can easily specify fields to ignore, without accidentally doing something silly, like saying "ignore all lines that have generatedBy then outputting all JSONs on one line so the entire comparison is ignored

**Comment by artoonie** [comment]
Note: this won't totally solve the problem, since the `CSV` writer also has a `generatedBy`.
