### ISSUE TITLE
make RawElectionConfig fields private

### ISSUE THREAD

**Issue by tarheel** [BrightSpots/rcv#73]
http://www.baeldung.com/jackson-field-serializable-deserializable-or-not

**Comment by tarheel** [comment]
Once we do this, we may just want to combine RawElectionConfig and ElectionConfig.

**Comment by HEdingfield** [comment]
@tarheel so do you think method 3 in the article is the best way to go (i.e. make public getters for everything)?

**Comment by HEdingfield** [comment]
Cool, out of curiosity, what's the rationale?

**Comment by tarheel** [comment]
If we have public getters for all the raw fields, but then the non-raw version is something else (e.g. the raw config has a string, but in the ElectionConfig object that string gets converted to an enum), it'll be confusing to have both mixed into the same class. So it feels cleaner to keep these separate.

**Comment by tarheel** [comment]
(You'd end up having, say, getOvervoteRuleRaw and getOvervoteRule.)

**Comment by HEdingfield** [comment]
I guess I fundamentally don't understand the difference between the two classes; i.e. why have the "middleman" class of RawElectionConfig in the first place, instead of just sucking it up from the JSON and processing it directly into ElectionConfig?

**Comment by tarheel** [comment]
But how exactly would you implement it as one class?

We have to make the fields public to make the Jackson stuff work. So we'd have publicly accessible raw fields, plus a set of getters for the normalized values. That's confusing.

Alternatively, we could make the fields private and add getters. But then we'd have two getters for some of the fields (raw and normalized). Again, that would be confusing.

**Comment by CalebKleppner** [comment]
Just commenting to get subscribed to this and see if it's still an active issue.

**Comment by HEdingfield** [comment]
@CalebKleppner Yep, still active. FYI, you can just click "Subscribe" under the notifications section in the top right of the issue; no need to comment unless you want to.

**Comment by HEdingfield** [comment]
I was considering getting rid of the getters and setters entirely today, in favor of method 5 in the original article posted in this thread, but realized that, although they seem trivial, public getters and setters are necessary in the GUI for loading candidates and CVR file sources (it's a quirk of the `TableView` object).

Maybe we should just close this issue out at this point and leave `RawContestConfig` as-is?

If so, we'll need to remember to remove:
`// TODO: add getters and setters for everything to address issue #73`

**Comment by CalebKleppner** [comment]
Hyton -- You're a monster -- you never stop.  I'm at Louis and 
Charlotte's house.  We expect Jon in a bit.  Are you on your way?

Cheers,
Caleb

Caleb Kleppner
MK Election Services, LLC
203-376-4080
