### ISSUE TITLE
When tabulating multiple CVR files post-tabulation CVR conversion export does not include all data

### ISSUE THREAD

**Issue by chughes297** [BrightSpots/rcv#734]
And for some reason the errors aren't appearing in any of my log files, either? I was running the scale test [from here](https://github.com/BrightSpots/rcv/tree/develop/src/test/resources/network/brightspots/rcv/test_data/2013_minneapolis_mayor_scale) and got the attached CVR conversion on the other end. 
[2023-07-13_12-44-52_dominion_conversion_contest_.csv](https://github.com/BrightSpots/rcv/files/12069595/2023-07-13_12-44-52_dominion_conversion_contest_.csv)

I'm guessing this is because we've made files generated by RCTab read-only - it looked like RCTab created the CVR conversion file after reading in the first CVR and then couldn't update that file after it had made it read only.

**Comment by yezr** [comment]
could potentially be closed as unnecessary pending #753
