### ISSUE TITLE
Post-tabulation converted CVR export is always labeled "Dominion conversion"

### ISSUE THREAD

**Issue by chughes297** [BrightSpots/rcv#735]
We should change the name of the export to either a generic name "cvr_conversion" or to a vendor-specific name "[vendor name from CVR tab]_conversion." I lean towards a generic name because then we don't have to think about how to handle multi-vendor CVRs (though we could just call such a conversion "multi-vendor_CVR_conversion" or something like that?).

**Comment by yezr** [comment]
will be fixed with #785
