### ISSUE TITLE
Revise the instructions on CVR tab telling a user how to select multiple files

### ISSUE THREAD

**Issue by chughes297** [BrightSpots/rcv#736]
Read through this and found it a bit unclear. Here's a revised version (with original below). I mostly just changed the flow of information. I also replaced the word "directory" with "folder" - that's still accurate, right? I found directory not immediately obvious. Also, is it at all possible to allow users to select multiple directories/folders? 

Thoughts on the revisions? 

Path (required): Location of the CVR file. 
  * Example: /test data/2015-portland-mayor-cvr.xlsx
  * Example: C:\test data\2015-portland-mayor-cvr.xlsx
NOTE: You can select multiple consecutive files by holding down Shift when you click filenames in the dialog (or multiple non-adjacent files by holding down Ctrl or Cmd). You can also manually add multiple if you enter the values in the Path input box, each separated by two semicolons:
  * Example: C:\test data\precinct14.json;;C:\test data\precinct15.json;;C:\test data\precinct16.json
Please ensure none of your file paths contain double semicolons within them, or they'll get split and treated as separate file paths.

NOTE: For providers that require folders to be selected, it's not possible to select multiple using the dialog. However, if you manually enter the values in the Path input box, separated with double semicolons, this will work:
  * Example: C:\test data\Dominion Input 1;;C:\test data\Dominion Input 2;;C:\test data\Dominion Input 3
****

Here's the original version: 
Path (required): Location of the CVR file. Please ensure none of your file paths contain double semicolons within them, or they'll get split and treated as separate file paths (see below).
  * Example: /test data/2015-portland-mayor-cvr.xlsx
  * Example: C:\test data\2015-portland-mayor-cvr.xlsx
NOTE: You can select multiple consecutive files by holding down Shift when you click filenames in the dialog (or multiple non-adjacent files by holding down Ctrl or Cmd). You can also manually add multiple if you enter the values in the Path input box, each separated by two semicolons:
  * Example: C:\test data\precinct14.json;;C:\test data\precinct15.json;;C:\test data\precinct16.json
NOTE: For providers that require directories to be selected, it's not possible to select multiple using the directory chooser dialog. However, if you manually enter the values in the Path input box, separated with double semicolons, this will work:
  * Example: C:\test data\Dominion Input 1;;C:\test data\Dominion Input 2;;C:\test data\Dominion Input 3

**Comment by chughes297** [comment]
Also can anyone think of an elegant way to tell users what sort of file RCTab expects when you've selected a specific vendor? We could include in the hints tab maybe? According to my notes this breaks down as:

Standalone files: 
ESS
CDF
CSV

Folder/Directory: 
Clear Ballot
Dominion
Hart

**Comment by yezr** [comment]
Showing how it was implemented by @artoonie. Select button now has explicit description of what type of file(s) or folder(s) it is expecting. perfect!
<img width="858" alt="image" src="https://github.com/BrightSpots/rcv/assets/8996546/c472bf32-7b29-412b-800c-2b831b4fbd4f">

<img width="774" alt="image" src="https://github.com/BrightSpots/rcv/assets/8996546/bf7eb4ed-6f9e-4a2c-a7f9-6df9027f7d50">

<img width="878" alt="image" src="https://github.com/BrightSpots/rcv/assets/8996546/e8a71217-5322-4d97-b755-c9bb78dd3b80">
