### ISSUE TITLE
Generate hash for output files

### ISSUE THREAD

**Issue by yezr** [BrightSpots/rcv#746]
To increase security, along with #696, we've been asked to generate a hash of each output file to verify that the output files have not been edited.  For now, can RCTab generate a read only hash for the following output files

- each audit\__N_.log
- summary.csv
- summary.json

Does it make sense to also include the hash of each summary file into the text of the audit log?

**Comment by artoonie** [comment]
The main issue with including the hashes in the audit log is, well, we're hashing the audit log too -- i.e. we can't include a file's hash into the file itself.

we can rename audit logs to `audit_N_hash.log`, or we could have a separate `audit_hashes.log` file. I'll opt for the latter, unless there are other suggestions.

**Comment by yezr** [comment]
I like the `audit_N_hash.log` because it is all contained in one file: the data and the hash. 

I am thinking of the process of a user manually checking the hash of the summary files. They would ctl+f each of the audit\__N_\__hash_.log files for something to find the line where we put the hash? How would they know what to search for? We would have something written in the TDP and they would have to find it and remember part of that message text. 

That makes me appreciate simplicity of the hash in the filename for each file. But then I worry that a long, non-english string like a hash in the filename is going to confuse or scare your average RCTab county clerk user.

That makes me lean towards a separate file like you mention, something like the `audit_hashes.log` file. Hart for their hashes has a separate `[fileName].hash` file for each of the files they are hashing. The text of that `.hash` file is the hash for the corresponding file. That leaves the original files intact with an obvious hash file that corresponds to its original. 

 Let me talk it through with Chris since he knows the average user better than I do right now.

**Comment by yezr** [comment]
After talking with Chris he's also concerned that the hash in the filename will confuse the average user. Can we implement the following

- for each of the three+ files mentioned, when done writing can we create a corresponding `[filename].[extension].hash` file. The text of that file will be `[hash algorithm description] [hash value]`. So for example we'll have a `summary.csv.hash` and the text of that file will be 
> sha512 767c96e2c169184f8874df5a9ec7ab6b36c3c75f1e0b89d1907395599fe0cbc7b46564ffde9f340c9e70388bc2d24b777f4816a7b93df4fe76d098402fb66f65
- can we still log the hashes for files that are not `audit.log` files into the audit log as an extra measure of security. So that if a malicious actor wanted to change the summary files they would also have to change the audit logs and their corresponding hash files

**Comment by artoonie** [comment]
Yep! Easy peasy.

**Comment by artoonie** [comment]
I'm using `.sha` instead of `.hash`, and the file contains just the hash value, as that seems to be more standard than a `.hash` with a description inside. Let me know if you prefer another way!

**Comment by yezr** [comment]
Here is the benefit I see to having the algorithm name in the file. I'm working through the TDP right now and there are some mixed uses of SHA256/SHA512. I'm not sure if using both are expected or if it just an artifact of a TDP update that didn't update everything it should have. I would hate to see a manual hash check fail just because of confusion over exactly which algorithm was used to derive the hash. 

Looking at examples in our repo I do see the releases have `.sha512` hash files. That also works to positively identify the hash algorithm. My reasoning for `.hash` as the file extension is for making documentation easier. As I've been working through the TDP for this 1.3.2 release I'm noticing that the document has a lot of gory, specific details that make it quite brittle to code changes. I'm trying to think of how best to make the TDP a little more robust so those details don't become stale or out of date with code changes.

In the docs I could generically say "There will be a `.hash` file. Inside the file is the algorithm and hash text." If we do end up changing the algorithm in the future I wouldn't risk the documentation becoming stale - updating the algorithm description in the `.hash` file documents itself!
