### ISSUE TITLE
add support for permutation-based tie-breaking

### ISSUE THREAD

**Issue by tarheel** [BrightSpots/rcv#75]
This is somewhat connected to #60. If we allow the operator to specify the tie-breaking permutation in the config file, they need to list out the candidates, of course.

For simplicity, my recommendation is to punt on #60 for now and rely on the candidate ordering in the config file to define the permutation for tie-breaking when this tie-breaking mode is enabled.

**Comment by moldover** [comment]
Sounds right.  #60 is also something we should run past Caleb and George before doing, I suspect there may be good reasons not to do it at all (like, it could incorrectly treat undeclared write-ins like declared candidates for some cvrs)

**Comment by CalebKleppner** [comment]
I think this is a great example of you guys coming up with a very efficient way to interpret something (permutation based tie-breaking) that most vendors aren't even thinking about.  Nice job.
