### ISSUE TITLE
Reimagining Dominon Conversion file as rctab_cvr

### ISSUE THREAD

**Issue by yezr** [BrightSpots/rcv#753]
Further reflection of the bug #734 and its corresponding PR #751 forced the conversation of what exactly we want out of this file, currently labeled `dominion_conversion`. The result changes a little how we want the file to work. It will make #734 moot and fix #735 

I removed all of these related issues from 1.3.2. This file isn't generated for Hart in 1.3.x, which is the only vendor that 1.3.x will be used for. 

### Goal
So we do we want from this file? We want to create a list of all input CVRs stripped only to their essential information. Those essentials will provide two things. 
- **Reproducibility** anyone should be able to take the information in there and use it to recreate RCTab's results. 
- **Transparency** Those essentials will also provide more transparency into how exactly we interpreted the raw CVRs. This will aide troubleshooting and auditability. 

### What needs to change from the current implementation
- Let's refer to this file as the `simple_cvr` format. (Open to other ideas. Also discussed was `basic_cvr` or `essential_cvr`) To fix #735  the file should be named `[dateTime]_simple_cvr_conversion_[contestId|contestName]`. If we don't have `contestId` can we use the `contestName` from the Contest Info tab. 
- There should be a single file that contains all of the input CVRs, regardless of the number of input files that they come from. This will make #734 moot since all input CVRs will be appended to the same file.
- To help with auditability now that all input CVRs are in one file, let's add a new column to the `simple_cvr` file: `input_file`. This will contain the full filename and extension of the input file that the CVR was converted from.

**Comment by yezr** [comment]
Some other questions about simple_cvr since it now applies to all vendors and not just Dominion
- What would we expect for a skipped ranking? Right now it shows an empty cell. Do we need to be explicit that it is a skipped ranking? Can an empty string ever be a valid vote, or will anyone know that this is a skipped ranking. 
<img width="1344" alt="image" src="https://github.com/BrightSpots/rcv/assets/8996546/fe751787-8032-4ee3-9bd1-46334cc0bf37">

- Following up on #777 What would we expect for an overvote that is marked in the input CVR as two candidates with the same ranking? I think this can happen in a CVR but I don't have any examples..... Would it be just `overvote` or something like `CandidateA|CandidateB`. I would think we would want to provide as much information as possible, therefore the second option that shows as close as possible the raw CVR.

**Comment by artoonie** [comment]
1. I don't think emptystring is ever considered a valid candidate name. I'm not sure that's a case we've handled. If it becomes an issue, we can handle it by using aliases and alias empty string to the word "emptystring" or something. I'm happy leaving as-is.
2. Great question. I suppose we do need to handle this: if we want to be a truly generic CSV, it's possible that future municipalities allow overvotes. (e.g. "I like all three of these candidates equally, and these two equally.") I believe the only character not allowed in candidate names is a newline, so let's newline-separate them?

**Comment by artoonie** [comment]
[2024-01-16_19-52-13_essential_cvr_0.csv](https://github.com/BrightSpots/rcv/files/13957169/2024-01-16_19-52-13_essential_cvr_0.csv)
How's this file look? It's got examples of overvotes represented on multiple lines, and it's got the source on the first line.

If this works, I'll:
1. Update the CSV reader to parse overvotes in the CSV (not currently supported)
2. Add a "Convert to Basic CVR" (or essential, or whatever).

A note on phrasing: I like "essential" but it could be misinterpreted to mean "mandatory". Maybe "fundamental CVR" instead?

**Comment by yezr** [comment]
> Would it make sense to instead write the following CSV format, which we can already read: https://github.com/BrightSpots/rcv/wiki/CVR-Formats ?

I think we keep the current `simple_cvr` format of ranks at the top and candidates in the cells. This more closely mirrors most original ballot formats. We can wait for #671 to start dog-fooding the `simple_cvr` in as input. 

>phrasing

I can get on board with essential. In that, it has everything essential/required to recreate a contest. 

>If this works, I'll:

> - Update the CSV reader to parse overvotes in the CSV (not currently supported)
> - Add a "Convert to Basic CVR" (or essential, or whatever).

Sorry I'm confused what exactly these mean. Is the first one to enable #671? If so, can we keep it separate. I want to be vigilant about it's scope creeping into this ticket. For the second bullet point, do you mean an option in the RCTab configuration so a user has to opt-in to this file?

**Comment by artoonie** [comment]
> Sorry I'm confused what exactly these mean. Is the first one to enable #671? If so, can we keep it separate. I want to be vigilant about its scope creeping into this ticket. For the second bullet point, do you mean an option in the RCTab configuration so a user has to opt-in to this file?

Oops! # 1 was written before I realized we can't actually read this format, so scratch that. That will be done as part of #671. #2 meant to say "add a button" (forgot the word "button")

**Comment by yezr** [comment]
No button necessary, this file will be included in the output for every tabulation.

**Comment by yezr** [comment]
Created [this issue](https://github.com/orgs/BrightSpots/projects/1/views/1?pane=issue&itemId=54054733) to figure out how a two candidate overvote shows up currently in the `simple_cvr`. If it shows up as "overvote" I would be ok with that for now. We can put in another ticket to make it explicit which candidates were included in the overvote.

**Comment by artoonie** [comment]
done!
