### ISSUE TITLE
Update 1.3.2 TDP to address CA 9.6.7 Cryptography requirements

### ISSUE THREAD

**Issue by yezr** [BrightSpots/rcv#754]
California Voting System Guidelines section 9.6.7 requires disclosures related to Cryptography used in RCTab. Those requirements are 
![image](https://github.com/BrightSpots/rcv/assets/8996546/241eff27-5c35-4ece-9171-96e75459c3b6)

I asked Hart if they could send over the pertinent parts of their TDP. The file they sent over is in slack [here](https://bright-spots.slack.com/archives/CBYMQRYEQ/p1695407584046479). 

Can we work together to draft this section of our TDP for 1.3.2. I've created a draft document [here](https://docs.google.com/document/d/1h1mYPxro6p6K3uciBrjdFr1aZnwqDrM7G63idyiN204/edit?usp=sharing).

**Comment by artoonie** [comment]
I took a pass at this -- not sure if I put too much or not enough details, and not sure if I made it too technical or not technical enough. @yezr can you take a look?

**Comment by yezr** [comment]
I put some comments in for you Armin. I'm also inviting Jared Bernal, Hart's principal regulatory engineer, to review and provide any guidance. He was super helpful with the System Hardening portion of the TDP.

**Comment by yezr** [comment]
Completed and included in the latest TDP included in the [1.3.2 release](https://github.com/BrightSpots/rcv/releases/tag/v1.3.2)
