### ISSUE TITLE
Auto-Loading Candidates from ES&S not working

### ISSUE THREAD

**Issue by yezr** [BrightSpots/rcv#760]
@joshadaniels had [issues auto-loading candidates](https://github.com/BrightSpots/rcv/issues/733#issuecomment-1772846562) with ES&S CVRs. 

@joshadaniels can you share the CVRs that are not loading correctly. That will help us recreate the problem and squash this bug.

**Comment by joshadaniels** [comment]
Here's the sample CVR I was using. I made it in the same format as ES&S. Perhaps there are specific data fields or data labels assumed by RCTab in order to read it that I omitted?
[Dem POTUS Sample.xlsx](https://github.com/BrightSpots/rcv/files/13078519/Dem.POTUS.Sample.xlsx)

**Comment by joshadaniels** [comment]
Here is the config file I was using for this example when I kept getting a failure to autoload candidates and then also would have issues if I manually input the candidates. [R14POTUSConfig.json](https://github.com/BrightSpots/rcv/files/13125273/R14POTUSConfig.json)

**Comment by yezr** [comment]
Looking through the code this is the same issue as https://github.com/BrightSpots/rcv/issues/766 and should be fixed already in https://github.com/BrightSpots/rcv/pull/786
