### ISSUE TITLE
Reconcile GitHub Wiki and `contributor_guide.md`

### ISSUE THREAD

**Issue by HEdingfield** [BrightSpots/rcv#771]
Options:

* Move `contributor_guide.md` info into the GitHub Wiki (e.g. [here](https://github.com/BrightSpots/rcv/wiki/Notes-on-Development)) and link to the Wiki from the `.md`
* Write a quick summary in the Wiki [here](https://github.com/BrightSpots/rcv/wiki/Notes-on-Development) and link to `contributor_guide.md`

Maybe method 2 is preferable, since it makes us less dependent on GitHub?

**Comment by artoonie** [comment]
Not sure how expansive you were thinking -- is this sufficient? https://github.com/BrightSpots/rcv/wiki/Notes-on-Development

**Comment by artoonie** [comment]
Done: https://github.com/BrightSpots/rcv/pull/841
