### ISSUE TITLE
[2.0-RC] CVR Overvotes show up as blank in RCTab_CVR

### ISSUE THREAD

**Issue by yezr** [BrightSpots/rcv#777]
RCTab Version: 1.4.0
Config file: [overvote test 1.2.json](https://github.com/BrightSpots/rcv/files/13663406/overvote.test.1.2.json)
CVR file: [Book2.xlsx](https://github.com/BrightSpots/rcv/files/13663411/Book2.xlsx)

## What happened
Testing how RCTab handles overvotes I loaded the CVR that @chughes297 whipped up. I compared the [simple_cvr](https://github.com/BrightSpots/rcv/issues/753) to the original CVR and noticed that what was marked explicitly as an overvote in the CVR was blank in the simple_cvr
![image](https://github.com/BrightSpots/rcv/assets/8996546/212a681c-716a-4ccd-8131-ea015d882a98)

## What I Expected
I would expect that the overvote be marked in the simple_cvr. In this example, basically for it to match exactly the text of the CVR itself. For example, I would expect 'overvote' in 

- Round 1 for CVRs 1-4
- Round 2 for CVRs 11 & 12

**Comment by yezr** [comment]
I looked into the code because I was curious and found some stuff that might point the future fixer of this issue in the right direction! Once I knock the rust off my IDE in the future maybe I could just fix it while I'm in there...
`selection = config.getNameForCandidate(selection);` returns null for 'overvote' in ResultsWriter line 643
`contestconfig processCandidateData` probably needs to add an 'overvote' -> 'overvote' like for UWI

**Comment by yezr** [comment]
Now that 2.0 creates this file everytime once #753 is complete, I think we should ensure that the output is correct. Tagged w/ `needs-rcvrc-clarification` to confirm

**Comment by artoonie** [comment]
#753 didn't fix this before, but has now been updated to fix this
