### ISSUE TITLE
Support for multiple CVR formats

### ISSUE THREAD

**Issue by openbrian** [BrightSpots/rcv#779]
Is there support to tabulate CVRs of multiple formats in the same contest?

In Virginia we're considering legislation to support RCV.  It was shot down in session last year due to this issue.

**Comment by yezr** [comment]
Yes Brian! It will be available in 1.4.0. There were a couple of code updates that enable candidate 'aliases' ([#639](https://github.com/BrightSpots/rcv/pull/639), [#697](https://github.com/BrightSpots/rcv/pull/697), [#690](https://github.com/BrightSpots/rcv/pull/690)) which can be used to aggregate a single candidate's votes across CVRs from different vendors. 

I'm working on making a more explicit list of the feature updates that will be in 1.4.0. Development is still ongoing, but it will look a lot like [this dev pre-release](https://github.com/BrightSpots/rcv/releases/tag/dev-2023-06-30)
