### ISSUE TITLE
Update hotfix/1.3.2 branch to officially stamp the code as version "1.3.2"

### ISSUE THREAD

**Issue by yezr** [BrightSpots/rcv#787]
Getting the latest commit [e6c8bd9](https://github.com/BrightSpots/rcv/commit/e6c8bd99c2ee804e61d0f155d19eb87d85965457) for the [v1.3.2 tag](https://github.com/BrightSpots/rcv/releases/tag/v1.3.2) the logger is showing the version number as `1.3.1`!

![image](https://github.com/BrightSpots/rcv/assets/8996546/3aade2a4-9b2e-4904-9863-813a31a04563)

Can we update the relevant code sections to bump this to `1.3.2`? Then, can we update the v1.3.2 tag to point at that new commit? 

Once the update is in and the tag is moved I will attempt to confirm that a `git fetch` alone will update my local tag.

**Comment by artoonie** [comment]
done!
