### ISSUE TITLE
Possible to Remove Minimum Vote Threshold?

### ISSUE THREAD

**Issue by hanksims** [BrightSpots/rcv#792]
Setting minimumVoteThreshold to zero will, in the first round, eliminate not only candidates who have received zero first-place votes but also the candidate with the lowest number of first-place votes. See the following:

[config.json](https://github.com/BrightSpots/rcv/files/14089959/config.json)
[results.csv](https://github.com/BrightSpots/rcv/files/14089961/results.csv)
[2024-01-29_11-45-08_summary.json](https://github.com/BrightSpots/rcv/files/14089964/2024-01-29_11-45-08_summary.json)

In a five-way race, two candidates with zero first-place votes are eliminated, but so is a candidate with only one first-place vote.

Admittedly, this is probably not a scenario you'd often find in an actual election, where you'd assume people would at least vote for themselves. But in my case -- and perhaps in more conventional use cases too, for all I know -- it seems like there should be an option to turn off the minimum vote threshold, or at least to treat one or more of the candidates who failed to reach that threshold as the eliminated candidate in a round.

I did try setting minimumVoteThreshold to -1, which threw an error.

**Comment by hanksims** [comment]
**UPDATE:** Looking a little further, I do believe this is some sort of a bug. In a case where only **one** candidate receives zero votes, that candidate is eliminated _and_ is treated as the candidate eliminated by that round. See the following:

[config.json](https://github.com/BrightSpots/rcv/files/14090145/config.json)
[results.csv](https://github.com/BrightSpots/rcv/files/14090147/results.csv)
[2024-01-29_11-45-07_summary.json](https://github.com/BrightSpots/rcv/files/14090149/2024-01-29_11-45-07_summary.json)

In a six-way race, the single candidate with zero first-place votes is eliminated, and the candidate with only one first-place vote is _not_ eliminated.

When contrasted with the behavior in the original post, I have to believe this is unintentional and some kind of bug.

**Comment by yezr** [comment]
@hanksims thank you for the extra research and repro config. We'll recreate in house and prioritize it!

**Comment by hanksims** [comment]
Upon reflection and further study, this is an artifact of batchElimination being set to true, which I had not intended. Apologies.
