### ISSUE TITLE
review 1.3.2 enhancements for inclusion in 2.0

### ISSUE THREAD

**Issue by yezr** [BrightSpots/rcv#803]
review all the 1.3.2 enhancements and see how they can go into 2.0

Need to review everything in here https://github.com/BrightSpots/rcv/compare/v1.3.1...v1.3.2
#### Should Be Included in 2.0
- https://github.com/BrightSpots/rcv/issues/748 needs confirmation that it sets correctly on mac & linux and see if there are any gotchas like the Windows user folder. 
- https://github.com/BrightSpots/rcv/issues/746 fixed with https://github.com/BrightSpots/rcv/pull/752 which was merged into `develop`

#### Needs clarification from RCVRC
- https://github.com/BrightSpots/rcv/issues/747 will fail on all Hart Verity versions other than 3.2 in California.  Also, is a little brittle since the cryptographic key can be changed at any time from within Verity but is hard coded in RCTab. How to proceed? Compiler flag to build a stricter CA version + more permissive general version? I want to avoid keeping `hotfix/1.3.2` around. We have flexibility, but need to set expectations with Hart.  
- https://github.com/BrightSpots/rcv/issues/757 is required, along w/ properly setting up permissions in the RCTab output folder detailed in [Section 22 of the TDP](https://docs.google.com/document/d/1phFkgz7FnSRv1gx-1yYUtc0jy4YSWHFd0vAa8hLHTw4/edit#bookmark=id.4vvrwagz2e9z), to ensure read-only outputs. This comes at the expense of ease of use for election admins. Need to confirm that is a price we are willing to pay. Exception text they will see if trying to save to My Documents, My Desktop or any other Windows User folders is 
>To ensure read-only access to RCTab output files, users must not set the output path to user account folders like Documents, Desktop, etc. -- any path under C:\users\`theirWindowsAccountName` is prohibited. Please specify a new path outside this folder in the Output tab of the app (e.g. C:\\RCTab\\output).

#### Needs clarification in devland
- https://github.com/BrightSpots/rcv/issues/767 involves a couple commits in `hotfix/1.3.2`. Trying to remember where exactly we landed on BouncyCastle...
- Once we get clarification on https://github.com/BrightSpots/rcv/pull/755 need to address that it is already merged into `develop`, might need to back that out...
-  https://github.com/BrightSpots/rcv/issues/748 was merged with https://github.com/BrightSpots/rcv/pull/749 into `hotfix/1.3.2`. Did it make it anywhere else? `git branch -r --contains 0c9bd877ddb26b40b37d4db7e72f6011876f2776` says that commit doesn't exist

**Comment by yezr** [comment]
#757 and #747 should be toggled OFF in 2.0. Should jurisdictions want those included we can create an `UPDATE_PATH` for them with these features toggled on. 

@artoonie does that mean we are all good then? I think all the required stuff has been merged...

**Comment by artoonie** [comment]
Given what's in this Issue, it seems like we are good. The few outstanding issues (bouncycastle, whether read-only works cross-platform as intended) have open issues and can be considered outside the scope of this merging.

**Comment by yezr** [comment]
sweet. closing this
