### ISSUE TITLE
UI doesn't effectively convey tabulation failure

### ISSUE THREAD

**Issue by HEdingfield** [BrightSpots/rcv#82]
If filePath in config file isn't pointing to a valid file, the audit log will correctly show the problem, e.g.:

> Tue Jul 17 08:17:46 PDT 2018 INFO: Reading CVR file: test/benton-commissioner-2.xlsx (provider: ES&S)
> Tue Jul 17 08:17:46 PDT 2018 SEVERE: failed to open CVR file: test/benton-commissioner-2.xlsx, test\benton-commissioner-2.xlsx (The system cannot find the file specified)
> Tue Jul 17 08:17:46 PDT 2018 SEVERE: ERROR during tabulation: java.io.FileNotFoundException: test\benton-commissioner-2.xlsx (The system cannot find the file specified)
> Tue Jul 17 08:17:46 PDT 2018 INFO: Done logging tabulation to test_output\benton_comm_2\2018-07-17_08-17-46_audit.log

However, the UI seems to convey that tabulation was completed successfully. The UI needs to properly convey why tabulation failed (including all the possible validation errors that can pop up).

**Comment by tarheel** [comment]
This should be pretty easy to do now that #81 is closed.

**Comment by tarheel** [comment]
(I mean, to give different messages depending on what went wrong.)

**Comment by HEdingfield** [comment]
Confirmed that it says "successful" after unrecognized candidate error is triggered as well, so guessing this is a general problem. It should also say exactly where it's writing the log file and the results out to.

**Comment by tarheel** [comment]
One alternative approach that came to mind: we could return the ElectionConfig object even when it fails validation, and the config itself would provide a method that returns a list of its validation errors. Just an idea.

**Comment by HEdingfield** [comment]
And the validation method would get called as part of the constructor and / or method that fills out the config? I think that might make more sense. Still might not get around the "how do we communicate these errors to the GUI user" issue though.

**Comment by CalebKleppner** [comment]
Presuming that we get a separate "validate config" function in v 0.8 GUI, this issue should become moot.

**Comment by moldover** [comment]
+1
I would propose a modification on Louis' idea.  Conceptually, load and validate are kept separate (but equal!): 
loadElectionConfig returns a tuple of 
1) List<String> configLoadErrors (empty if it loads and parses) 
2) ElectionConfig (null if load fails)
These messages get displayed to user and GUI says config is not loaded if this fails.
If it loads, user can then trigger validation (or have it happen automatically, or when they tabulate, etc..)

we move the createOutputDirectory call into the validate config method.
