### ISSUE TITLE
[Undefined Behavior] How does a CVR with a two candidate overvote show up in simple_cvr

### ISSUE THREAD

**Issue by artoonie** [BrightSpots/rcv#822]
Following up on [this conversation](https://github.com/BrightSpots/rcv/issues/753#issuecomment-1854410758) in #753 double check what an actual two-candidate overvote shows up as in the `simple_cvr`

(written by @yezr)

**Comment by artoonie** [comment]
Confirmed that this shows up as a newline. Shall we adjust this behavior? I think most CVR readers can handle this, but it's possible that it'll lead to strange behavior.

I could imagine wanting a delimeter specified in a config. Unfortunately, I don't think any character other than a newline is safe, as every other character could theoretically be a part of a candidate's name? We could also start escaping candidate names if needed, or just replace this with the word "overvote".

[2024-03-31_20-17-03_rctab_cvr.csv](https://github.com/BrightSpots/rcv/files/14818062/2024-03-31_20-17-03_rctab_cvr.csv)

**Comment by yezr** [comment]
A newline works. Now that we've confirmed this I'll document it and make sure it gets into the documentation. Thanks @artoonie!
