### ISSUE TITLE
Schedule a dev release build every two weeks

### ISSUE THREAD

**Issue by artoonie** [BrightSpots/rcv#827]
We're getting occasional emails from non-developers who want to use the latest RCTab without installing Java. I've been linking them to files in my google drive and trying to keep up-to-date with the latest develop, but having a recurring build would be helpful. If needed we can adjust this to once a month or whatever, but it's currently set to twice a month.

**Comment by yezr** [comment]
When this does its automatic dev build will it remove the previous auto-build that it is taking the place of?

**Comment by artoonie** [comment]
It should, yes -- that is a configurable option that I have set.
