### ISSUE TITLE
When output folder doesn't exist, error shows in UI 

### ISSUE THREAD

**Issue by yezr** [BrightSpots/rcv#846]
RCTab Version: 1.3.999

## What Happened
I was doing some testing and set the output folder to a folder that didn't yet exist `~/Downloads/vmwgoutput-with_one_undervote`. Usually, RCTab creates the output folder for me if it doesn't exist. During this round of testing, however, when calculating ballot numbers I saw an error in the log when writing the `rctab_cvr` saying that the file didn't exist (I think the real issue was the folder didn't exist). I was able to continue on and tabulate. Tabulate worked successfully, correctly created the new folder, and successfully wrote the `rctab_cvr`. 
![image](https://github.com/BrightSpots/rcv/assets/8996546/373a70a6-adcc-4bab-ac84-fe3816c91f8a)

I confirmed later by configuring to a folder that does exist that the `rctab_cvr` is being written twice if the configured output folder exists: once during ballot counting and once during tabulation. 

## What I Would Expect
I would expect RCTab not to attempt to write a `rctab_cvr` during the ballot counting step. If it does, I would expect the same logic that creates the folder during tabulation to create the folder during ballot counts.

**Comment by artoonie** [comment]
I will update to not write an rctab_cvr. In the process, I've noted that logs that get ouput to the GUI window during "Check Ballot Counts" are not written to an audit log. Should they be? Perhaps in a separate file? I think I prefer that they are.

Here's a demo: the audit log is separated into "check ballot counts" and "tabulate" sections.

https://github.com/BrightSpots/rcv/assets/537316/45ce1c99-0b59-447d-b88e-98972389c0e2
