### ISSUE TITLE
UI logs aren't always scrolled to the latest

### ISSUE THREAD

**Issue by yezr** [BrightSpots/rcv#850]
**RCTab Version** 1.3.999
## What Happened
While researching #846 I had the ballot count modal open while some logs were being written to the UI. For some reason, the UI logs weren't auto-scrolling to the bottom. I tried to scroll but couldn't because the modal had focus and I couldn't scroll the UI logs without exiting out of the ballot count modal. I think it was especially noticeable during this because there was an error writing the `rctab_cvr` which makes you think something is wrong, but in fact the parsing of the CVRs to get the ballot count worked fine (which you would see if the logs were fully scrolled down). 

![2 0  after checking ballot count, log doesn't show latest](https://github.com/BrightSpots/rcv/assets/8996546/be4ec637-584c-41a8-8fee-6681a33d2503)

## What I Would Expect
The UI log would always be scrolled to the bottom to ensure I see the latest information.

**Comment by HEdingfield** [comment]
This seems similar to what we addressed with #840. Can you verify that you can repro it in the current `develop` branch?
