### ISSUE TITLE
Two different results report files, one with ALL details and one with a summary of the data

### ISSUE THREAD

**Issue by yezr** [BrightSpots/rcv#856]
We’ve been adding more granular inactive ballot buckets to help with reporting. These granular buckets are important for reporting on RCV contests, but are starting to take a lot of real estate and grab maybe too much attention in the `summary.csv`. So we’re proposing to split the current `summary.csv` into two separate files…

### summary_report.csv
Will include most of the 2.0 updates like round by round vote percentages and round by round transfers but will NOT include the split out inactive buckets. It will have just one "Inactive Ballots Total" row similar to all output before 2.0.
- Number of undervotes in round 0
- For each candidate, each round
  - % of total votes for each round
  - Number of ballots transferred from eliminated candidate(s) in the previous round
- ~Inactive ballots in each round broken down by category~
  - ~Overvote~
  - ~Skipped Ranking~
  - ~Repeat Ranking~
  - ~Exhausted Choices~
- Per-Round winning threshold
- RCTab version number
- Contest Summary
- Number to be Elected
- Number of Candidates
- Total Number of Ballots

### detailed_report.csv 

will include all of the current 2.0 updates.

### detailed_report.json
`summary.json` will include everything and be renamed `detailed_report.json`.

### Tabulate by Slice
 Tabulate by slice files will include everything and be renamed `[sliceId]_[sliceType]_detailed_report.[csv|json]`

**Comment by artoonie** [comment]
Should an extended summary, a simplified summary, or both be generated for slices?

**Comment by yezr** [comment]
tabulate by slice file name shouldn't change and should include all the information as it currently does. So as it is right now, no updates to tab by slice are necessary

**Comment by artoonie** [comment]
Noted. Flagging potential confusion as `x_summary_extended.csv` will correspond with `x_by_slice_summary.csv`

**Comment by yezr** [comment]
> Noted. Flagging potential confusion as `x_summary_extended.csv` will correspond with `x_by_slice_summary.csv`

Noting this, can we rename the current tabulate by slice files `x_by_slice_summary_extended.csv` to prevent this confusion.   The original motivation for this ticket was at the contest level: for jurisdictions that don't want to have to be responsible for inactive bucket data explanations they would have an option to just post the summary file and not the summary_extended file. My thinking is that if someone is already digging into the tabulate by slice files they are going to want extended information no matter what.

**Comment by artoonie** [comment]
done!

**Comment by yezr** [comment]
title and original description updated based on conversations with RCVRC HQ
