### ISSUE TITLE
Add installation instructions to ReadMe

### ISSUE THREAD

**Issue by CalebKleppner** [BrightSpots/rcv#86]
Universal RCV Tabulator installation instructions
From Caleb’s experience on Win 7 and Win 10
July 24, 2018

First, you gotta make sure you have at least version 9 of Java Runtime Environment (jre).  Current version is 10.0.2  Get it at:

http://www.oracle.com/technetwork/java/javase/downloads/jre10-downloads-4417026.html

Download the version for your operating system and install it.  Pretty quick and easy to do.  Probably need to have a 64 bit machine, but that’s pretty standard now.

Second, create the folder:

C:\Program Files (x86)\Bright Spots\RCV Tabulator

Third, download the zip file for the latest RCV tabulator.  As of July 24, 2018, it was rcv 2018-07-18.zip , which was available by visiting https://drive.google.com/file/d/1xfm2kdEr59-y7yiO-JkLQNnI19P8hdBo/view (this link may change, but the key is to get a zip file that contains the latest rcv.jar as well as test, doc, src and libs directories, which aren’t necessary for running the program but have all the source code, sample configuration files and documentation of the configuration file format).

Unzip rcv.jar and the other directories into C:\Program Files (x86)\Bright Spots\RCV Tabulator

Third, click on rcv.jar in the folder C:\Program Files (x86)\Bright Spots\RCV Tabulator and the program should be running.  You simply click on the button to load a config file (find samples in the C:\Program Files (x86)\Bright Spots\RCV Tabulator\test directory) and then you click a button to tabulate.  When the tabulation completes, you should find a summary file (vote by candidate by round) and audit file (how each ballot was counted in every round, and more).

If, when you click on the rcv.jar, you get a list of the files in rcv.jar instead of the application, you’ll need to right-click on rcv.jar, choose “Open with” and then select, “Java ™ SE Platform Binary” (and use “Set default program” to make it open every time you click a .jar file)

Lastly, if the tabulator doesn’t seem to be producing results in the output directory, the problem may be that the application doesn’t have permission to write to the directory, C:\Program Files (x86)\Bright Spots\RCV Tabulator or subdirectories, such as output_test.

The solution is to go to the properties of the RCV Tabulator directory, select the Security tab, and then Edit to change permissions.   You may need to give Full Control to Users and/or Administrators.

See attached files for screenshots of changing properties

[Universal RCV Tabulator Installation July 2018.docx](https://github.com/BrightSpots/rcv/files/2229199/Universal.RCV.Tabulator.Installation.July.2018.docx)

**Comment by CalebKleppner** [comment]
I think this duplicates another issue.

**Comment by HEdingfield** [comment]
Yes, it's related to #58. The problem here is that your instructions describe how to deal with the final compiled binary, whereas the README in our base directory should be about the raw source files.

We'll need to reassess all this once we get our project structure finalized (#110) and come up with a consistent, reliable methodology for releasing final compiled versions.

**Comment by gngilbert** [comment]
Sounds as if we might need to address this now.

**Comment by HEdingfield** [comment]
Preliminary instructions on how to run it directly from the repo code (will add Windows info after going through the process on my Windows machine):

1) Install JDK 11 or higher (https://jdk.java.net/), and make sure your Java path is picking it up properly by verifying that following command returns the expected version:
$ java --version

If the expected version isn't getting returned, you'll need to follow the instructions here on how to set your Java path:
https://www.java.com/en/download/help/path.xml

2) Download the zip from GitHub and unzip it, or install git and use the following command to clone a local copy on your machine:
$ git clone https://github.com/BrightSpots/rcv.git

3) Use the provided version of Gradle to build and run the code:
$ cd rcv
$ ./gradlew run

If you get a "Permission denied" error in MacOS or Linux, you need to mark the script as executable with:
$ chmod 777 gradlew

**Comment by chughes297** [comment]
Should I add this to page on rcv.org? Or wait for these to be finalized?

**Comment by HEdingfield** [comment]
Yes please, that'd be great! Note: this is in response to #273.

>

**Comment by HEdingfield** [comment]
Oops, sorry, I meant update the link on the page per #273, but hold off on these instructions until we finalize. They actually don't apply to the compiled bins.

**Comment by HEdingfield** [comment]
Closed with #315. @chughes297: better to have the page point to these instructions rather than duplicate them on your page, as they're subject to change. See the comment I left in #273 with my specific recommendation.
