### ISSUE TITLE
EOL issues w/ git clone

### ISSUE THREAD

**Issue by yezr** [BrightSpots/rcv#863]
when we clone and immediately do a git status have a long list of files that are marked as modified. I attached my list of files which is very similar but a little different from Malachi's.

It looks like it's a line ending issue of some kind. I think maybe since [#790](https://github.com/BrightSpots/rcv/pull/790) we checked in a new `.gitattributes` that sets line endings for certain files. I attached the list of files that are different right when I clone and then git status. Malachi's are similar but a little different.

[mathew's git-status.txt](https://github.com/user-attachments/files/16072537/git-status.txt) immediately after clone
[malachi's git-status.txt](https://github.com/user-attachments/files/16072542/git-status.1.txt)

What I see for git status. Notice the warning about CRLF
![image](https://github.com/BrightSpots/rcv/assets/8996546/5f9526aa-3748-44ab-be11-f0b1a8c2882b)

I'm leaving this out of 2.0 until we test the golden hash generation. I think this will affect getting the correct golden hash. If so, I'll add it in to 2.0.

**Comment by yezr** [comment]
jon says deleting the .gitattributes fixed it on his machine

**Comment by artoonie** [comment]
Deleting .gitattributes will fix this but break golden hash generation -- I think this may be fixed by simpling cloning, committing everything, and checking in?

**Comment by yezr** [comment]
>  I think this may be fixed by simply cloning, committing everything, and checking in?
'this' being the golden hash generation? I have on the 2.0 testing plan to retest golden hashing, specifically of the installers, and we can double check that it worked

**Comment by artoonie** [comment]
The issue seems to be that files were erroneously being marked as text files when they were actually binaries. The PR fixes this, so no new files need to be checked in, and the golden hash should continue to work.
