### ISSUE TITLE
Ignore quoted commas when parsing non-header-row CSV values in ClearBallotCvrReader

### ISSUE THREAD

**Issue by ryu-seg** [BrightSpots/rcv#880]
Version: found in 1.3.1 RC2 (but still applies to the current develop branch)

This bug is very closely related to https://github.com/BrightSpots/rcv/issues/793 (that issue had to do specifically with the header/first row of the CSV file; this issue applies to the rest of the rows) 

- Config File: [RCTab-City_of_Portland__Auditor_2024_08_20_15_04_22.json](https://github.com/user-attachments/files/16696176/RCTab-City_of_Portland__Auditor_2024_08_20_15_04_22.json)

- CVR File: (Clear Ballot format): [City_of_Portland__Auditor_2024_08_20_15_04_22.cvr.csv](https://github.com/user-attachments/files/16696178/City_of_Portland__Auditor_2024_08_20_15_04_22.cvr.csv)

When parsing the non-header rows of the Clear Ballot CVR CSV file, values are split by all commas, including commas that are within quoted text.

For example, in the CVR attached above, some of the PrecinctStyleName values include commas (e.g.  "4406 [A, C]"):

- Expected: The non-header row values are only split along un-quoted/un-escaped commas (e.g. (1) 19, (2) RCV-0255, (3) 19, (4) RCV-0255+10039, (5) 2, (6) 2, (7) **_4406[A,C]_**, (8) ScanStation2, etc.) 

- Actual: The non-header row values are split along all commas (e.g. (1) 19, (2) RCV-0255, (3) 19, (4) RCV-0255+10039, (5) 2, (6) 2, (7) **_4406[A_**, (8) **_C]_**, (9) ScanStation2, etc.) This results in the fatal error "Parsing cast vote records failed!" (due to failing to parse strings as integers).

**Comment by nurse-the-code** [comment]
I wanted to see how this bug looks on the current version of `develop`. That will give us a clue as to if the patch needs to be ported to `develop` as well prior to our 2.0 release.

It looks like on the current version of `develop`, the error message has changed a little:

<img width="1139" alt="Screenshot 2024-09-04 at 23 15 37" src="https://github.com/user-attachments/assets/46065b75-2c83-4218-8403-5a7ffc6ec454">

The `config.json` file had to be slightly adjusted for the current version of `develop` to:
```
{
  "tabulatorVersion" : "1.3.999",
  "outputSettings" : {
    "contestName" : "City_of_Portland__Auditor_2024_08_20_15_04_22",
    "outputDirectory" : "./",
    "contestDate" : "2024-11-05",
    "contestJurisdiction" : "City of Portland",
    "contestOffice" : "City of Portland, Auditor",
    "tabulateByBatch" : false,
    "tabulateByPrecinct" : false,
    "generateCdfJson" : false
  },
  "cvrFileSources" : [ {
    "filePath" : "./City_of_Portland__Auditor_2024_08_20_15_04_22.cvr.csv",
    "contestId" : "City of Portland, Auditor",
    "idColumnIndex" : "",
    "batchColumnIndex" : "",
    "precinctColumnIndex" : "",
    "overvoteDelimiter" : "",
    "provider" : "clearBallot",
    "overvoteLabel" : "",
    "skippedRankLabel" : "",
    "undeclaredWriteInLabel" : "",
    "treatBlankAsUndeclaredWriteIn" : false
  } ],
  "candidates" : [ {
    "name" : "Simone test Rede",
    "excluded" : false,
    "aliases" : [ ]
  }, {
    "name" : "Write-in-28",
    "excluded" : false,
    "aliases" : [ ]
  }, {
    "name" : "Invalid",
    "excluded" : false,
    "aliases" : [ ]
  }, {
    "name" : "Lisa Simpson",
    "excluded" : false,
    "aliases" : [ ]
  } ],
  "rules" : {
    "tiebreakMode" : "stopCountingAndAsk",
    "overvoteRule" : "alwaysSkipToNextRank",
    "winnerElectionMode" : "singleWinnerMajority",
    "randomSeed" : "",
    "numberOfWinners" : "1",
    "multiSeatBottomsUpPercentageThreshold" : "",
    "decimalPlacesForVoteArithmetic" : "1",
    "minimumVoteThreshold" : "",
    "maxSkippedRanksAllowed" : "50",
    "maxRankingsAllowed" : "6",
    "nonIntegerWinningThreshold" : false,
    "doesFirstRoundDetermineThreshold" : false,
    "hareQuota" : false,
    "batchElimination" : false,
    "continueUntilTwoCandidatesRemain" : false,
    "stopTabulationEarlyAfterRound" : "",
    "exhaustOnDuplicateCandidate" : false,
    "rulesDescription" : "Single Winner City Wide",
    "treatBlankAsUndeclaredWriteIn" : false
  }
}
```
