### ISSUE TITLE
Apache POI illegal reflective access operation

### ISSUE THREAD

**Issue by HEdingfield** [BrightSpots/rcv#92]
I see these warnings a lot when I run the tabulator; anything we can do to fix them?

> Sun Jul 29 10:29:09 PDT 2018 INFO: Reading CVR file: test/2015-portland-mayor-cvr.xlsx (provider: ES&S)
> WARNING: An illegal reflective access operation has occurred
> WARNING: Illegal reflective access by org.apache.poi.openxml4j.util.ZipSecureFile$1 (file:/C:/Users/Hylton/IdeaProjects/rcv/libs/poi-3.16/poi-ooxml-3.16.jar) to field java.io.FilterInputStream.in
> WARNING: Please consider reporting this to the maintainers of org.apache.poi.openxml4j.util.ZipSecureFile$1
> WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
> WARNING: All illegal access operations will be denied in a future release
> Sun Jul 29 10:29:10 PDT 2018 INFO: Read 99 cast vote records

**Comment by tarheel** [comment]
See question 23 here: https://poi.apache.org/help/faq.html

Also note the next question, where it says that .xlsx parsing won't work in Java 10.

I wonder if there's a better library that we should be using instead.

**Comment by HEdingfield** [comment]
Yeah, that's definitely a cause for worry, since JRE 9 is relatively hard to install. FWIW, I'm using JDK 10 on my computer now and it seems to be running ok.

I guess take this issue as an action item to:
a) look for alternatives for loading .xlsx files
b) keep a close eye on Apache POI releases to make sure we get the newest version before submitting for certification

**Comment by moldover** [comment]
I followed the white rabbit.  The Poi Java10 compile bug is [fixed](https://bz.apache.org/bugzilla/show_bug.cgi?id=62187).
I was able to download bleeding edge POI for Java 10 [build](https://builds.apache.org/view/P/view/POI/job/POI-DSL-1.10/lastSuccessfulBuild/artifact/ooxml-lib/)
With the addition of Apache [Commons](https://commons.apache.org/proper/commons-compress/download_compress.cgi) I was able to build and run a tabulation.

However, I still hit illegal reflective access, but in a different place :(

An illegal reflective access operation has occurred
WARNING: Illegal reflective access by org.apache.xmlbeans.impl.common.SAXHelper (file:/Users/Jon/Documents/rcv/libs/poi-4.0.0-SNAPSHOT/ooxml-lib/xmlbeans-3.0.0.jar) to method com.sun.org.apache.xerces.internal.util.SecurityManager.setEntityExpansionLimit(int)
WARNING: Please consider reporting this to the maintainers of org.apache.xmlbeans.impl.common.SAXHelper

**Comment by HEdingfield** [comment]
Nice, thanks for going to the tea party for us! Sounds like it still might be worth updating the Apache bins in our repo? Or would you rather wait a bit longer and circle back on this issue?

**Comment by moldover** [comment]
It's not an official release and it doesn't solve the warning problem.  I'm inclined to wait till it does, or we need plan B, there may be some commercial options:  Haven't dug into these yet: http://roide-textcube.blogspot.com/2009/02/java-libraries-to-read-and-write-excel.html

**Comment by CalebKleppner** [comment]
I'm also getting those POI error messages, but they only show up in the console, not in the GUI, the audit log or rcv.log.  Program seems to run a lot slower when you have the console open (2 minutes for Maine 2018 primary with console open compared to 30 seconds without)

**Comment by HEdingfield** [comment]
I think what @CalebKleppner meant here was that it ran slower when he had the GUI open? In which case, it's not really rendering anything there during tabulation anyway. If it's a reproducible issue, please open a new one and we can see if it's addressable.

**Comment by chughes297** [comment]
Doesn't seem necessary for certification, but are there any updates to POI that have stopped these error messages?

**Comment by HEdingfield** [comment]
I think this is resolved since we upgraded to Gradle / the newest version of Apache's libraries, but need to verify.

**Comment by HEdingfield** [comment]
Confirmed that this no longer occurs for me, likely because we're using the latest Apache libraries now.

> 2019-06-13 12:22:44 PDT INFO: Reading cast vote record file: C:\Users\MyName\IdeaProjects\rcv\src\test\resources\com\rcv\test_data\2015_portland_mayor\2015_portland_mayor_cvr.xlsx...
> 2019-06-13 12:22:44 PDT INFO: Parsed 99 cast vote records successfully.
