### ISSUE TITLE
automated tests

### ISSUE THREAD

**Issue by tarheel** [BrightSpots/rcv#96]
I've never written any tests in Java, so I don't know which existing libraries to suggest.

I think what we're looking for is the ability to take an input config file, CVR file, and expected output file, and verify that the output file we generate matches the expected file (at least for all the tabulation results cells). Make sense?

**Comment by moldover** [comment]
Yep, sounds right.  Just spitballing here:

0) run batch tests on input files
1) generate summary results in csv format (planning to do this anyways)
2) read summary results from the same csv format
3) read csv reports which are verified correct
4) compare the round by round counts
5) report comparision results

Note: besides steps 0 and 1, the rest of this does not need to be part of the actual Tabulator program which gets certified (though we want to publish whatever we do).  It will be faster if we don't have to comply with all the strict coding standards.

**Comment by gngilbert** [comment]
Not following all your conversation but I have created a set of test data sets in ES&S format and have tabulated the expected results manually.  TestSet1 and TestSet2, which I have shared with you are examples.  I am working on additional ones today.  

Also need to create these test sets in other cvr formats, such as iVotronic,, Dominion (Santa Fe) and Dominion/Sequoia (San Francisco/Alemeda Co).  Not sure what you guys need to do to enable importing these other formats into the tabulator.

**Comment by HEdingfield** [comment]
Welcome, George!

What Jon says makes sense to me. Let's make sure we have our output file format pretty well locked down before diving deeply into this. It'll likely take a chunk of manual work to regenerate / reverify the files we're comparing to in our tests each time we change the format.

**Comment by tarheel** [comment]
I created #104 for iVotronic and included the links that George shared earlier. Do we have good sample CVR data for the Dominion and Sequoia formats? If so, let's create new issues for those.

**Comment by gngilbert** [comment]
For Sequoia you can download any of the San Francisco cvrs from their
website.  I believe the guys at FairVote have the Dominion data from Santa
Fe.  Will check with them Monday.

Gg

George Gilbert
RCV Resource Center
george.gilbert@rankedchoicevoting.org
336-906-0047

**Comment by CalebKleppner** [comment]
I'm putting this on milestone v 0.9 cleanup, but we may decide it's not necessary even for v 1.0 submission.

**Comment by HEdingfield** [comment]
Deleted @gngilbert's comment 6 days ago because it contained PII. Here's the text:

> For Sequoia you can download any of the San Francisco cvrs from their
website.  I believe the guys at FairVote have the Dominion data from Santa
Fe.  Will check with them Monday.

Regarding @CalebKleppner's comment above: I'd argue that getting tests built in is not only essential pre-1.0, but should be very high priority. There are a number of backend issues I'd like to work on right now, but I'm very reluctant to do so without having automated tests that make sure I'm not breaking anything when I do so.

**Comment by gngilbert** [comment]
What is PII?

**Comment by tarheel** [comment]
Personally identifiable information. I think it gets included from your email signature when you comment via email.
