### ISSUE TITLE
Refactor config validation

### ISSUE THREAD

**Issue by HEdingfield** [BrightSpots/rcv#99]
Holding off on implementing the "Validate" button in the UI until we're able to pass a RawElectionConfig object (or something similar) into the validation function, instead of just having validation called and checked by Main.

This is probably a good opportunity to merge RawElectionConfig and ElectionConfig into a single class too, as was mentioned #73. Maybe file this as a separate issue?

**Comment by HEdingfield** [comment]
It should be relatively easy to convert `ElectionConfig.getValidationErrors()` to a stub that injects `this.rawConfig` into a new `static` version of `ElectionConfig.getValidationErrors(RawElectionConfig rawconfig)`. However, changing it to `static` might be a bit tricky.

@tarheel would you prefer that I just instantiate an `ElectionConfig` object and then call `getValidationErrors()` as-is for validation in the config creator GUI? If so, we can probably close this issue.

**Comment by tarheel** [comment]
@HEdingfield: that seems reasonable to me, unless there's a downside that I'm not thinking of...?

**Comment by HEdingfield** [comment]
Agreed that the latter should work fine; filed #120.
